### ISSUE TITLE
cant finish the "barrel" quest

### ISSUE THREAD

**Issue by Meepster007** [NovaMachina/ExNihiloSequentia#102]
I got a wooden barrel and it did not submit the quest I tried to do it manual many times

to finish the quest it says "Any forge:barrel
**To Reproduce**
Steps to reproduce the behavior: craft a barrel and it will not submit your quest
1. Place block '...'
2. Right click on '...'
3. Do thing '...'

**Expected behavior**
A clear and concise description of what you expected to happen. The quest to complete

**Screenshots**

**Version**
Minecraft Version: 1.16.4
Forge Version: i could not find the forge version
Ex Nihilo: Sequentia Version: 1.16-2.0.1.0

**Additional context**
Stack traces and log files are nice to have. Submit all files through [Gist](https://gist.github.com/) or [Pastebin](https://pastebin.com/) and place the links here.

**Comment by Meepster007** [comment]
pls help i cant progess with out it

**Comment by NovaMachina** [comment]
If this is in relation to a modpack, please submit the issue to the modpack creator.
