### ISSUE TITLE
Obsidian Transformation Broken

### ISSUE THREAD

**Issue by Flatts3000** [NovaMachina/ExNihiloSequentia#103]
Version: 2.0.2.0
Modpack: Sky Bees
Single player

I have a crucible feeding into a barrel with Cyclic pipes with a hopper under the barrel. Once the barrel is full, I place water on top of the barrel and the lava in the barrel turns into air. I'm able to get a single obsidian from this setup, but subsequent attempts result in the barrel deleting the lava and replacing it with air.

Even if I remove the Cyclic pipes and use a bucket, this deletion still happens. Even if I remove the hopper under the barrel, the deletion still happens.

Restarting the client allows me to get a single obsidian out of the setup, then it starts deleting lava again.

After breaking and replacing the barrel, the lava is still deleted, even if the hopper and pipes aren't there.

**Comment by Flatts3000** [comment]
If I restart the client without the pipes and the hopper connected to the barrel, then I can manually get all of the obsidian I want out of the barrel.

**Comment by ariosos** [comment]
As a work-around, you can right click the top (maybe an Item User might work?) of the barrel to make the lava appear again (but I don't see the obsidian going into the hopper, storage drawer or my inventory).
EDIT: I just tried it with a brick hopper (mod is called "Brick Hopper") and it seems to work fine (I also closed and re-opened the save before that, too).

**Comment by Jkosio23** [comment]
seems like it's a bug with it changing modes to block on the same tick that the obsidian is being pulled out, and it ends up as the air block instead of the obsidian based on what i'm experiencing and my limited mod programming knowledge

**Comment by remplerus** [comment]
yes i can reproduce it also with wooden barrels and cobblestone (which i think should not do that)

**Comment by allanf181** [comment]
still happens in 1.20.1, mod version 5.0.0
![image](https://github.com/user-attachments/assets/7b7d2556-9778-42df-b8a5-01a9d42f1977)

**Comment by remplerus** [comment]
@allanf181 please open a new issue request with all needed information. this thread is over 3 years old and was a bug back in 1.16.5
