### ISSUE TITLE
Stone Barrel netherrack transmutation with partially filled barrel

### ISSUE THREAD

**Issue by ariosos** [NovaMachina/ExNihiloSequentia#104]
Using the Sky Bees modpack. Placing redstone into a stone barrel with less than 1000mb of lava will give a netherrack block. (consuming all of the lava in the barrel in the process)

I would expect that it takes the entire 1000mb.

![image](https://user-images.githubusercontent.com/7917753/107970713-76d2fa80-6f7f-11eb-94c0-bdf17a837fbf.png)

![image](https://user-images.githubusercontent.com/7917753/107970850-ada91080-6f7f-11eb-846a-8b9a104c1241.png)

**Comment by laod** [comment]
Came to report this as well. The handler for the fluid mode doesn't check how much fluid there is before calling drain and drain's parameter is a maximum.
