### ISSUE TITLE
Game crashes on startup phase

### ISSUE THREAD

**Issue by Blueblob860** [NovaMachina/ExNihiloSequentia#105]
In the Sky Bees modpack, I keep on getting an error stating "The game crashed whilst initializing game Error: net.minecraftforge.fml.ModLoadingException: Ex Nihilo: Sequentia (exnihilosequentia) encountered an error during the common_setup event phase Exit Code: -1" I am currently using chlorine to get a better fps, and I am using version 3.0.3b of the modpack.

Download Sky Bees version 3.0.3b
Load the game, and wait about 2 minutes
The crash should appear as "Error: net.minecraftforge.fml.ModLoadingException: Ex Nihilo: Sequentia (exnihilosequentia) encountered an error during the common_setup event phase"

Screenshots:
![image](https://user-images.githubusercontent.com/50087969/107973525-4c833c00-6f83-11eb-9129-d6874597e15b.png)
![image](https://user-images.githubusercontent.com/50087969/107974925-4c843b80-6f85-11eb-8b20-1c870caf2403.png)

Version:
Minecraft Version: 1.16.4
Forge Version: 35.1.37
Ex Nihilo: Sequentia Version: 2.0.2.0

Crash Report:
https://gist.github.com/Blueblob80/e7c4761c4782f43d8e6a7d0e3c4ee545

**Comment by NovaMachina** [comment]
This was an issue with the Mekanism add on. Please update the Mekanism add on as it will fix this issue.

**Comment by NovaMachina** [comment]
Wait... I might not have released the patches version of it yet. Let me do that.

**Comment by NovaMachina** [comment]
Should be released in a few minutes.

**Comment by Blueblob860** [comment]
Thanks!
