### ISSUE TITLE
sapling tag

### ISSUE THREAD

**Issue by TheNimbleNinja** [NovaMachina/ExNihiloSequentia#107]
**Describe the bug**

**To Reproduce**
exnihlo is trying to get sapling tag before its ready

**Expected behavior**
create a world
**Screenshots**

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.0.29
Ex Nihilo: Sequentia Version:1.16-2.0.2.0

**Additional context**
https://gist.github.com/TheNimbleNinja/44e42b000f419361a081754c4fb63556

**Comment by NovaMachina** [comment]
I don't see in the log where this is Ex Nihilo's fault. Looks to be more of an Ex Compressum Issue.
