### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by CodyEmery** [NovaMachina/ExNihiloSequentia#109]
**Describe the bug**
When launching the mod pack "Sky Bees", this mod seems to be encountering an error and causing the launch to terminate itself

**To Reproduce**
1. Click "Play" on the Overwatch Launcher
2. Click "Play" on the Minecraft Launcher

**Expected behavior**
The game to launch and run

**Screenshots**
![image](https://user-images.githubusercontent.com/32679508/108278378-f2cc6e80-7148-11eb-8af5-7402e10eec42.png)

**Version**
Minecraft Version: 1.16.5
Forge Version: 31.1.37
Ex Nihilo: Sequentia Version: 2.0.2.0

**Comment by NovaMachina** [comment]
This has been fixed in the latest version of the Mekanism Addon (where the bug originates). Please report this to the pack developer.
