### ISSUE TITLE
Couple of the bugs I noticed

### ISSUE THREAD

**Issue by CreatorVilius** [NovaMachina/ExNihiloSequentia#11]
Saplings in wooden crucible have sapling texture, not leave texture.
Saplings in wooden crucible never turn into water.
You can't use
- sand on flint and iron meshes
- dust on flint meshes
- soul sand on iron mesh
- can't use crushed andesite, diorite, granite and endstone on any mesh
- crushed netherrack on string mesh
You can't get bone meal from sieving dust.
No way to know when saplings are going to turn into dirt.(I mean that they don't change colour according to progress

**Version**
Minecraft Version: 1.15.2
Forge Version: 31.2.31
Mod Version: 2020-08-09-11-59-99

**Comment by NovaMachina** [comment]
* The crucible pulls the texture from the item in it. However, I can switch it to a leaf texture.
* In my testing, saplings do turn into water. Four saplings are equivalent to a bucket of water.
* Currently blocks cannot be on meshes that they don't have results for. Also, crushed andesite, diorite, granite, and end stone don't have any results (see the [sieve wiki](https://github.com/NovaMachina/ExNihiloSequentia/wiki/Sieve)).
* In my testing, bone meal comes from sifting dust on a string mesh 20% of the time (see the [sieve wiki](https://github.com/NovaMachina/ExNihiloSequentia/wiki/Sieve)).
* There are particle effects to indicate composting progress. Do you have particles off?

**Comment by CreatorVilius** [comment]
> In my testing, saplings do turn into water.

I dunno. When I tried to test, it didn't do anything. Does it need anything special? Like torch beneath it?

> There are particle effects to indicate composting progress. Do you have particles off?

Yeah, I have particles off.

**Comment by CreatorVilius** [comment]
> Does it need anything special? Like torch beneath it?

Yeah, putting torch works. Thought you didn't torches for wooden crucible.

**Comment by NovaMachina** [comment]
Here are the default [heat sources](https://github.com/NovaMachina/ExNihiloSequentia/wiki/Crucible#heat-sources).
