### ISSUE TITLE
Crashes in the Startup Phase

### ISSUE THREAD

**Issue by easternfps2016** [NovaMachina/ExNihiloSequentia#119]
**Describe the bug**
I have been getting this crash often when trying to run, sometimes I have to try starting Minecraft four or five times to not crash:
[crash-2021-02-20_00.00.09-client.txt](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/6015045/crash-2021-02-20_00.00.09-client.txt)

**Information**
Minecraft Version: 1.16.4
Java: 1.8.0_281 (64bit)
Forge Version: 35.1.37
Ex Nihilo: Sequentia Version: 1.16-2.0.2.1

**Comment by remplerus** [comment]
exnihilomekanism-1.16-1.0.0.0.jar  <---- thats the problem, update mekanism addon

**Comment by NovaMachina** [comment]
Update to exnihilomekanism-1.16-1.0.0.1
