### ISSUE TITLE
Emerald Mesh

### ISSUE THREAD

**Issue by IdkGoodName** [NovaMachina/ExNihiloSequentia#12]
Older Ex Nihilo didn't seem to add this, but what about **emerald mesh**? Emerald mesh would be basically higher tier than diamond one.

**Comment by ToMe25** [comment]
If this gets added a gold mesh might also make sense.

They could be like Iron and Diamond with more luck, meaning they can get the same resources, but more of them.

**Comment by Blackout03** [comment]
> Older Ex Nihilo didn't seem to add this, but what about **emerald mesh**? Emerald mesh would be basically higher tier than diamond one.

Maybe Netherite instead of emerald. But that would only be 1.16.

> If this gets added a gold mesh might also make sense.
> 
> They could be like Iron and Diamond with more luck, meaning they can get the same resources, but more of them.

Gold could be the same resources as Iron but sifts faster.

**Comment by IdkGoodName** [comment]
> Maybe Netherite instead of emerald. But that would only be 1.16.

I mean, you could make emerald mesh which is higher than diamond in tiers and netherite mesh which would be higher than emerald mesh in tiers.

**Comment by NovaMachina** [comment]
Once I get transitioned to using datapacks this will be a lot easier to implement.
