### ISSUE TITLE
[1.16] Dupe of sieving material when cyclic mod is present

### ISSUE THREAD

**Issue by jinkhya** [NovaMachina/ExNihiloSequentia#120]
**Describe the bug**
When you sieve following the steps below you can sieves for days without running out of gravel or sand, or dust or whatever you're using. In my example I used gravel.

**To Reproduce**
1. have a full inventory
2. put a stack of gravel in hand
3. drop gravel blocks on top of sieves 
        -> the amount needs to be at least 1 more gravel than the amount of sieves.
        -> example : if you are using 9 sieves at the time, you need to drop minimum 10 gravel
                                if you are using 25 sieves at the time, you need to drop minimum 26 gravel
4. the gravel is never being picked up completely, you can sieve gravel for days

Here's a video that illustrates the dupe and how to reproduce :
https://streamable.com/7zqvl2

**Expected behavior**
To not dupe the sieving material.

**Version**
- Forge 35.1.37 (same behavior with 36.0.42)
- Cyclic-1.16.5-1.1.6
- exnihilosequentia-1.16-2.0.2.1
Minecraft Version: 1.16.4 (same issue with 1.16.5)
Forge Version: Forge 35.1.37 (same with 36.0.42)
Ex Nihilo: exnihilosequentia-1.16-2.0.2.1

I'll link this to Cyclic's repo as I dunno who would have to fix it :)

**Comment by Darkosto** [comment]
I just tested this using both mods (along with about 80 others) and cannot reproduce this. I did exactly what was described and mimicked the video. Looks like it was fixed on Cyclic's end and not an issue any longer

**Comment by justinrusso** [comment]
This was a bug on Cyclic's end and should be fixed in Cyclic 1.17+. I believe this issue can be closed.

**Comment by jinkhya** [comment]
Cyclic closed the issue on their GitHub. They fixed a dupe bug in 1.1.7 so this issue is probably no longer a thing. Haven't tried the update yet myself.

**Comment by jinkhya** [comment]
I'll close this. Can reopen if this still happens.
