### ISSUE TITLE
[Suggestion] Prevent people from using scripts to sieve instantly

### ISSUE THREAD

**Issue by jinkhya** [NovaMachina/ExNihiloSequentia#121]
**Is your feature request related to a problem? Please describe.**
People can bypass the time it takes to sieve items with autoclickers/scripts

**Describe the solution you'd like**
Could it be possible to not accept more right click actions than needed for the time it needs to sieve?

**Additional context**
This is an example : https://youtu.be/bkIk_NThoWE?t=923

**Comment by ModernGamingWorld** [comment]
I agree this needs to be nerfed or fixed, thats to OP

**Comment by NovaMachina** [comment]
Uhhhh...yeah...that's not ok....

**Comment by NovaMachina** [comment]
So I have a solution, is there anyone with an autoclicker that could test it out for me? I can't seem to find a good autoclicker for linux

**Comment by pdawson** [comment]
> So I have a solution, is there anyone with an autoclicker that could test it out for me? I can't seem to find a good autoclicker for linux

I'm on Ubuntu and you can use `AutoKey`
Create a new script and use the following:
```py
for i in range(100):
    mouse.click_relative_self(0, 0, 3);
```

Then just bind it to a hotkey 😄

**Comment by jinkhya** [comment]
I can test it if you want :)

**Comment by NovaMachina** [comment]
> > So I have a solution, is there anyone with an autoclicker that could test it out for me? I can't seem to find a good autoclicker for linux
> 
> I'm on Ubuntu and you can use `AutoKey`
> Create a new script and use the following:
> 
> ```python
> for i in range(100):
>     mouse.click_relative_self(0, 0, 3);
> ```
> 
> Then just bind it to a hotkey smile

I tried autokey and for whatever reason it doesn't play nice on Fedora

**Comment by NovaMachina** [comment]
@jinkhya Here's the RC: https://jenkins.jacob-williams.me/job/Ex%20Nihilo%20Sequentia/62/

**Comment by jinkhya** [comment]
yup that worked !!! nice :)
My hand is right clicking fast but it's not sieving faster, good job !

**Comment by NovaMachina** [comment]
@jinkhya Sets you on fire right?

**Comment by jinkhya** [comment]
lol I was in creative but after swapping to survival it doesn't set me on fire, no.

**Comment by NovaMachina** [comment]
Ah...That's fine. As long as it prevents the autoclicker
