### ISSUE TITLE
useJson doesn't appear in config 

### ISSUE THREAD

**Issue by DarkAmulek** [NovaMachina/ExNihiloSequentia#122]
I looked in the config file for 1.16-2.0.0.1 and I did not see the option useJson in there.

**To Reproduce**
1. Place mod in mods folder
2. Run Minecraft 
3. Start new world
4. open Config file named exnihilosequentia-common
5. look for useJson, it doesn't appear to exist here.

**Expected behavior**
Open the config file named exnihilosequentia-common after creating a world with mod installed and find the useJson option in the configuration file.

**Screenshots**
![exnihilosequentia-common - Notepad 2_23_2021 8_06_30 AM](https://user-images.githubusercontent.com/65504516/108855393-933deb00-75ae-11eb-8645-220c412ac484.png)
![exnihilosequentia-common - Notepad 2_23_2021 8_08_21 AM](https://user-images.githubusercontent.com/65504516/108855374-8de0a080-75ae-11eb-924e-71c40b3e8951.png)
![exnihilosequentia-common - Notepad 2_23_2021 8_08_40 AM](https://user-images.githubusercontent.com/65504516/108855355-87eabf80-75ae-11eb-9a3f-e3f74f6b2fdb.png)

**Version**
Minecraft Version: 1.16.4
Forge Version: 35.1.37
Ex Nihilo: Sequentia Version: 1.16-2.0.0.1

**Additional info**
I'm not entirely sure if this is considered a bug or error, or if it was intended to be this way, but I figured I would put this info here whether than in the comments on curse forge and be redirected to here.

**Comment by remplerus** [comment]
uhm, yes, you cant use json anymore due to minecraft adding datapacks, but you can overwrite them using datapacks or crafttweaker

**Comment by DarkAmulek** [comment]
Oh, I did not know that data packs affected that. I don't often use mods past 1.12.2, sorry, probably should have just asked in the comments then. Thanks for the help.
