### ISSUE TITLE
[Bug] Custom Crook Recipe Bug

### ISSUE THREAD

**Issue by DevScyu** [NovaMachina/ExNihiloSequentia#123]
**Describe the bug**
When using a custom recipe with the crook, it seems to duplicate the input item.

**To Reproduce**
Use the following custom recipe in a datapack:
```json
{
  "type": "exnihilosequentia:crook",
  "results": [
    {
      "chance": 0.4,
      "item": "minecraft:oak_sapling",
      "count": 1
    }
  ],
  "input": {
    "item": "minecraft:dirt"
  }
}
```

**Expected behavior**
You only get the items in the result.

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.0.42
Ex Nihilo: Sequentia Version: 1.16-2.0.2.1

**Comment by remplerus** [comment]
can confirm that it happens with any crook recipe you add via datapack. i made that example above with logs. its duplicating 3-4 logs and sometimes the sapling.

**Comment by nest4321** [comment]
Can also confirm that after some testing crooks with quadruple harvestable blocks and triple typically non-harvestable blocks.
