### ISSUE TITLE
Change Crook Durability or Allow via Config

### ISSUE THREAD

**Issue by Darkosto** [NovaMachina/ExNihiloSequentia#124]
Hey!

checking back on older versions (skyfactory 1) Ex Nihilo had slightly higher durability for Wooden Crooks. 89 vs. 64 in the new versions. I've found that I'm constantly having to make new crooks because they break so quickly. Getting sticks is easy so it's not an issue of resource management but rather the time spent making a new crook so often. Is it possible to slightly raise the durability to match older versions OR allow a config option to alter this? I think 20-30 more durability would allow ~1 more tree and less frustration in early game.

Thank you!
Darkosto

P.S. - Sorry for not using the template I thought I could get this across quicker this way! <3

**Comment by NovaMachina** [comment]
No worries at all! I've been meaning to do this.
