### ISSUE TITLE
Wooden Crucible Should Not Require a Heat Source 

### ISSUE THREAD

**Issue by Darkosto** [NovaMachina/ExNihiloSequentia#127]
Hello!

I don't think the Wooden Crucible should require a heat source to function. The first concern is you're using lava or fire under a wooden block to power it. It's a game, so that's fine it doesn't have to make sense. But, that leads me into the next concern which is the inconsistency of the Wooden Crucible not matching previous iterations that did not need a heat source to convert leaves and saplings into water. I'm not sure if there is a mix up but the Wooden Crucible also allows cobblestone to be melted down in lava. I wasn't sure if this needed to be reported as a bug or feature.

Thank you!

**Comment by NovaMachina** [comment]
It was my intention that the wooden crucible have a base melting speed and that a heat source could speed it up. I'm surprised this is just now coming up.
