### ISSUE TITLE
Barrel Bug

### ISSUE THREAD

**Issue by lazynessmind** [NovaMachina/ExNihiloSequentia#131]
**Describe the bug**
When inserting items with external mods pipes the item isn't extracted from the inventory.

**Mod used:** Refined Pipes.

**To Reproduce**
1. Place Barrel
2. Place a item pipe beside the barrel
3. Place a chest beside the pipe.
4. Then when the barrel is filling nothing is getting extracted from the inventory that the pipe is connected to.

**Expected behavior**
idk probably the item shouldn't be in the inventory

**Screenshots**
Setup:
![image](https://user-images.githubusercontent.com/52864251/109400364-46f10300-7940-11eb-89b8-9f3e569af557.png)

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.0.42
Ex Nihilo: Sequentia Version: 1.16-2.0.1.0
Refined Pipes Version: 0.5

**Comment by remplerus** [comment]
i think it is fixed with the newest version, can you try it with version 2.0.2.1?

**Comment by remplerus** [comment]
actually, i have recreated your example, it extracts the dirt well, BUT the saplings arent pulled out of the chest if there are more than one sapling.
(tested with Exnihilo 2.0.2.1 and Refined Pipes 0.5 on Minecraft 1.16.5)
But i think thats a bug from refined pipes

**Comment by lazynessmind** [comment]
yeah, something is acting weird.

**Comment by lazynessmind** [comment]
still acting the same in 2.0.2.3
so it maybe is the refined pipes.

**Comment by remplerus** [comment]
it is definitly refined pipes, i dont know whats causing it, but i think it just looks for storage with more than one space

**Comment by lazynessmind** [comment]
yeah, because the pipe is responsible for the extraction and inserting. the barrel only has the inventory.
and if you use hoppers it works fine.
