### ISSUE TITLE
Allow configuring/disabling The One Probe info

### ISSUE THREAD

**Issue by CroshB** [NovaMachina/ExNihiloSequentia#132]
**Is your feature request related to a problem? Please describe.**
In a pack I'm developing I want to display minimal information on the The One Probe hud, however, the info from this mod can't be disabled, so I would like to be able to configure that.

**Describe the solution you'd like**
I suggest adding ways of configuring what shows up or not in the config file, however, I understand that making a full configuration system to tweak everything can be a little too much, so a simple config to turn on/off that integration is probably good enough for my use case.

**Describe alternatives you've considered**
I also tried looking at the TOP configs to see if there was a blacklist of some kind, but I couldn't find any.

**Additional context**
This suggestion can be extended to the WAILA/HWYLA integration as well.

**Comment by NovaMachina** [comment]
There are different levels of probes that I believe I can assign HUD display to. Would this work for you? Or are you looking for more fine grained control over the HUD?

**Comment by CroshB** [comment]
In the configuration for The One Probe I can set each kind of information to either `"NOT"` (0), `"NORMAL"` (1) or `"EXTENDED"` (2). If that's what you mean by levels of probe, it would work for me.

**Comment by NovaMachina** [comment]
I can make that happen. Did you want certain things to be visible at different levels?

**Comment by CroshB** [comment]
In my case I'll probably use the same level for all types of information
