### ISSUE TITLE
ExNihiloSequentia Causes My Game to Crash While Booting up

### ISSUE THREAD

**Issue by BoloYon** [NovaMachina/ExNihiloSequentia#135]
"The game crashed whilst initializing game
Error: net.minecraftforge.fml.ModLoadingException: Ex Nihilo: Sequentia (exnihilosequentia) encountered an error during the common_setup event phase
Exit Code: -1" This is what the crash report says

**To Reproduce**
1. Download SkyBees Modpack through the CurseForge application on Windows 10
2. Click play, you should be in the Minecraft Launcher
3. See error

**Expected behavior**
The game would crash saying "The game crashed whilst initializing game
Error: net.minecraftforge.fml.ModLoadingException: Ex Nihilo: Sequentia (exnihilosequentia) encountered an error during the common_setup event phase
Exit Code: -1"

**Screenshots**
![2021-03-03 (2)](https://user-images.githubusercontent.com/80021130/109910193-918eba00-7c75-11eb-8b74-f0d6460bae12.png)
![2021-03-03 (3)](https://user-images.githubusercontent.com/80021130/109910240-abc89800-7c75-11eb-895b-cc214e0ba88c.png)

**Version**
Minecraft Version: 1.16.5
Forge Version: 35.1.37
Ex Nihilo: Sequentia Version: 2020-08-09-11-59-99

**Comment by NovaMachina** [comment]
This is an issue with the Mekanism add on. Please update to the latest version of the Mekanism add on.
