### ISSUE TITLE
Game crashes when loading up Ex Nihilo: Sequentia with Garden of Glass world type

### ISSUE THREAD

**Issue by CreatorVilius** [NovaMachina/ExNihiloSequentia#14]
**Describe the bug**
Game crashes with `ConcurrentModificationException` while creating a new world(Botania Garden of Glass). Reading the error's stack trace, it seems that something is going on with barrel with fluid on top recipe.

**To Reproduce**
1. Launch Minecraft
2. Create 'Garden of Glass' world
3. Wait

**Expected behavior**
Launch normally.

**Screenshots**

**Version**
Minecraft Version: 1.15.2
Forge Version: 31.2.36
Mod Version: 2020-08-09-11-59-99

**Additional context**
[crash.log](https://github.com/NovaMachina/ExNihiloSequentia/files/5030257/crash.log)

**Comment by NovaMachina** [comment]
Does this error occur only when you reopen a world?

**Comment by CreatorVilius** [comment]
Nope. Only when creating.

**Comment by NovaMachina** [comment]
Fixed in 1.1.0.0 update
