### ISSUE TITLE
Please add some kind of automation

### ISSUE THREAD

**Issue by Ciberbago** [NovaMachina/ExNihiloSequentia#15]
Hello, I really appreciate your work porting this mod to 1.15.2.

Something I'd really love to have is some kind of automation, I don't know if something like Electric Auto Sieves powered by RF or FE is something hard to do. 
But if it's easier... maybe adding functionality to hoppers could do the trick.
How? In vanilla you can use hoppers to pump organic materials into composters to make bone meal. Maybe something similar for the sieves would work. Pumping gravel, sand or dirt with a hopper.

It's only an idea. Would be cool to have! Thank you for reading!

**Comment by BedrockLegends** [comment]
The only issues I see with this is that People like to leave stuff like this on 24-7 and cause alot of lag, I think there has to be away someway to make sure that not only The Electric Auto Sieves but the default sieves dont lag as players dont understand what a kill switch is

**Comment by NovaMachina** [comment]
I'm considering making a second mod to add automation for Ex Nihilo. However, if Ex Compressium is going to update, then I see no need for me to add it.

**Comment by NovaMachina** [comment]
It would appear that Ex Compressium is doing an update to 1.16.x
https://github.com/blay09/ExCompressum/tree/1.16.x
