### ISSUE TITLE
Crucible Rendering Issue Causing Crash

### ISSUE THREAD

**Issue by Yourname942** [NovaMachina/ExNihiloSequentia#153]
**Describe the bug**
Rendering issues are causing the player to instantly crash whenever he  is in the area of the crucible in question. 

**To Reproduce**
1. make a cobblestone generator
2. make a cooked crucible (forgot the name)
2. use cyclic item pipes into the top of the crucible
3. feed cobblestone into it via cyclic item cable
4. feed lava into magmatic dynamo via cyclic fluid cable
4. have a magmatic dynamo from thermal 
5. it worked fine for a few weeks
6. then I  updated my mods and this occurred when he went to that area. 

**Expected behavior**
Crucibles should not cause the player to crash if it errors out

**Screenshots**

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.0.48
Ex Nihilo: Sequentia Version: 1.16-2.0.2.3
Cyclic 1.16.5-1.1.9
thermal_cultivation-1.16.3-1.1.6
thermal_expansion-1.16.3-1.1.6
thermal_foundation-1.16.3-1.1.6
thermal_innovation-1.16.3-1.1.7

**Additional context**
crash log:
https://gist.github.com/Yourname942/ecc4462e41139e7db50022dba2b14ab2
latest log:
https://gist.github.com/Yourname942/cf8e2e671ebac44d342f7647888f1220

I'm hoping this will at least let him play in the meantime:
```toml
    #Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    removeErroringTileEntities = true
```
Someone mentioned this to me:
"looks like it's doing a recipe lookup on an item but not handling "can't find a recipe" properly"

**Comment by ModernGamingWorld** [comment]
According to what your saying is you updated mods and then the crash happened, Id suggest downgrading those mods and updating them 1 at a time and see if what ones cause the crash

**Comment by remplerus** [comment]
actually the crash log says that one block is rendered as a unfired crucible, what should not happen, but i would suggest to do the thing mentioned above
