### ISSUE TITLE
Option for maximum clicks per second on a sieve

### ISSUE THREAD

**Issue by Hoff2567** [NovaMachina/ExNihiloSequentia#154]
Looking to adjust the sieves to slow them down in my pack to make it competitive with other manual options and was hoping for the ability to control it via config similar to how ex compressum does it. Totally understand if it's not possible with the way you're handling anti-auto-clicking just wanted to toss it out there in case it is.

**Comment by Blackbird-Modder** [comment]
Well the conversation got locked on #155 so basically what I meant was that I want to change the cap on 1.16.5 ( sky bees ). What's the solution for this version? Cause i've been looking around github and can't really find a working solution.

**Comment by Blackbird-Modder** [comment]
Could I somehow go into the folders and change it from there?
