### ISSUE TITLE
Can't load CraftTweaker script.

### ISSUE THREAD

**Issue by liuseniubi** [NovaMachina/ExNihiloSequentia#158]
**Describe the bug**
Can't load CraftTweaker script.

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.1.1
Ex Nihilo: Sequentia Version: exnihilosequentia-1.16-2.0.2.3

**Additional context**
The script and the lasted.log is included in following link.
https://paste.ubuntu.com/p/QMJQZ7T9cz/

**Comment by remplerus** [comment]
can you also add crafttweaker version, so we can try that ourselves?

**Comment by liuseniubi** [comment]
CraftTweaker-1.16.5-7.1.0.176

**Comment by liuseniubi** [comment]
> can you also add crafttweaker version, so we can try that ourselves?

CraftTweaker-1.16.5-7.1.0.176
