### ISSUE TITLE
Fire Does Not Appear in JEI Heat Sources

### ISSUE THREAD

**Issue by Darkosto** [NovaMachina/ExNihiloSequentia#159]
**Describe the bug**
When searching JEI for heat types/sources for the Fired Crucible, Fire does not render or appear. I've confirmed this with the mod alone. There is no indication to the player that Fire is a useable heat source.

**To Reproduce**
1. Look it up in JEI

**Expected behavior**
Some type of indication that Fire can be used to heat a Crucible

**Screenshots**
![image](https://user-images.githubusercontent.com/10309699/111821548-05e57200-88a0-11eb-8147-0213b567f30a.png)

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.0.46
Ex Nihilo: Sequentia Version: 2.0.2.3

**Comment by ModernGamingWorld** [comment]
Should be Fixed in Next update

**Comment by NovaMachina** [comment]
I'm having issues rendering fire in the slot, but I've replaced the empty slot with flint and steel
