### ISSUE TITLE
Bucket disappears when placing water in barrel

### ISSUE THREAD

**Issue by Kaylinofhr** [NovaMachina/ExNihiloSequentia#16]
**Describe the bug**
While making clay with the wooden barrel, my bucket disappears when right clicking water on the barrel.

**To Reproduce**
1. Place barrel.
2. Right click bucket on water.
3. Right click full bucket on barrel.
4. End up with a barrel full of water and no bucket.

**Expected behavior**
I think I'm supposed to keep the bucket.

**Version**
Minecraft Version: 1.15.2
Forge Version: 31.2.36
Ex Nihilo: Sequentia Version: 1.1.0.1

**Comment by NovaMachina** [comment]
Fixed in 1.1.0.2
