### ISSUE TITLE
sorting autosieve inventory voids mesh 

### ISSUE THREAD

**Issue by tsuuii** [NovaMachina/ExNihiloSequentia#161]
**Describe the bug**
mesh voiding with inventory sorting

**To Reproduce**
make autosieve
place mesh
sort inventory (usually mouse middle click)
mesh voided

**Version**
Minecraft Version: 1.16.5
atm6 to the sky 1.0.3c

**Comment by remplerus** [comment]
well  that sounds like a bug, but you mentioned not enough information. as far as i can tell, you use ex nihilo, ex compressum and inventory sorter (or some kind of it) and i dont think its a problem of ex nihilo. make an issue on inventory sorter github

**Comment by remplerus** [comment]
https://github.com/reo-ar/InvTweaksRenewed/issues/47

**Comment by NovaMachina** [comment]
Is this an issue with the auto sieve from Ex Compressum or with the sieve from Ex Nihilo?

**Comment by remplerus** [comment]
[this is in autosieve with exnihilo mesh](https://github.com/blay09/ExCompressum/issues/309)

**Comment by remplerus** [comment]
issue is solved by invtweaks, just wait for release of new version.
