### ISSUE TITLE
Sea water does not act like water

### ISSUE THREAD

**Issue by DarkIlluminatus** [NovaMachina/ExNihiloSequentia#167]
**Describe the bug**
As in the title, sea water does not act like a fluid when placed.

**To Reproduce**
1. Place sea water block from bucket or from builder placing liquids shape card
2. Water appears and moves like water, however moving through it is like moving through air.

**Expected behavior**
Water appears and moves like water and can be swam in and sea plants are placeable and ocean creatures spawnable.

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.1.2
Ex Nihilo: Sequentia Version: 1.16-2.0.2.3

**Comment by tyler489** [comment]
I believe this is because water "checks" are hard coded in 1.16. alot of mods have this issue.

it also applies to witch water

**Comment by remplerus** [comment]
until adding them to minecraft tag water, there's no other solution due to mojang's wonderful code

**Comment by DarkIlluminatus** [comment]
Thanks for recommending this fix.
