### ISSUE TITLE
hoppers double item input

### ISSUE THREAD

**Issue by benbenlaw** [NovaMachina/ExNihiloSequentia#168]
**Describe the bug**
making dirt requires 8 blocks of leaves (125/1000) using right click by player
using a hopper only requires 4 blocks making (250/100) instead of 125

**To Reproduce**
1. place barrel
2. place hopper on top with 4 leaves
3. wait
4. get dirt for half the price!

**Expected behavior**
same values as player (8 blocks)

**Screenshots**

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.0.58
Ex Nihilo: Sequentia Version: 1.16 - 2.0.2.3

**Additional context**
this is the case for any block or item used in barrels to make dirt

**Comment by remplerus** [comment]
@NovaMachina this one's fixed too
