### ISSUE TITLE
Will the mod support the Create mod?

### ISSUE THREAD

**Issue by PercyCreeper** [NovaMachina/ExNihiloSequentia#17]
I have already seen the suggestion about JEI and also the one about automation, but if you do the automation, could you make it support the Create mod? I don´t know how difficult it would be, but it would be very cool if you managed to do it.

**Comment by NovaMachina** [comment]
In theory it should be able to support the Create mod. I don't see why it wouldn't, unless the Create mod doesn't use the capability system to interact with objects.

**Comment by PercyCreeper** [comment]
Well, I don´t know how it works, but if it works, great :) I think the steampunk style of the Create mod would fit with ex nihilo

**Comment by NovaMachina** [comment]
I'm going to go ahead and close this suggestion as the other suggestion covers the compatibility needed.
