### ISSUE TITLE
Ex Nihilo instant crash

### ISSUE THREAD

**Issue by ChubbsWasTaken** [NovaMachina/ExNihiloSequentia#175]
**Describe the bug**

**To Reproduce**
1. Place Fired Crucible
2. Right click on Fired Crucible with cobblestone
3. Crash

**Expected behavior**
i expected it to work normally and not crash me

**Screenshots**
none available as it crashed

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.1.0
Ex Nihilo: Sequentia Version: Mar 6, 2021

**Additional context**
this is pain.
[latest.log](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/6298903/latest.log)

**Comment by remplerus** [comment]
the version has a name and not a date, but its fixed in dev branch, wait for release.

**Comment by ChubbsWasTaken** [comment]
@remplerus sorry, the guidelines had a date and not a version number (if i understand correctly).
thanks for fixing it
