### ISSUE TITLE
Lava cannot be placed in a stone barrel

### ISSUE THREAD

**Issue by hermankyhn** [NovaMachina/ExNihiloSequentia#187]
**Describe the bug**
Witch water/Lava cannot be placed in a stone barrel. (the same applies to the wooden barrel, although the wooden barrel should not accept lava)
Note: water can be placed in the barrel and works as intended

**To Reproduce**
Right-clicking a stone barrel with a bucket of lava/bucket of witch water.

**Expected behavior**
The stone barrel should be filled with lava/witch water respectively, as it is used for recipes.

**Screenshots**
Screenshot from a session with only the Ex Nihilo: Sequentia mod (and the fml stuff).
![image](https://user-images.githubusercontent.com/71282715/116000171-595d8500-a5ef-11eb-983f-f3fcbd48e0c3.png)

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.1.4
Ex Nihilo: Sequentia Version: 1.16-2.0.2.5

**Additional context**
Making witch water with mycelium and water still works, but manually placing witch water into the stone (or wooden barrel for that matter) does not fill the barrel.

**Comment by remplerus** [comment]
[this is the pr](https://github.com/NovaMachina-Mods/ExNihiloSequentia/pull/184)
