### ISSUE TITLE
Datapack Question 1-16

### ISSUE THREAD

**Issue by trogarus** [NovaMachina/ExNihiloSequentia#188]
After reading https://ex-nihilo-sequentia.readthedocs.io/en/1.16/data_pack/ and https://github.com/NovaMachina-Mods/ExNihiloSequentia/blob/1.16/docs/data_pack.md I'm still a bit confused about the file structure and json file names needed to affect the datapack over rides. If someone could kindly educate me, and maybe update the pages in question, it would be much appreciated. Sorry if this is already explained and I missed it in the documentation. Thanks.

**Comment by remplerus** [comment]
pretty easy.
the datapack has to be something like this:
/yourdatapackname/data/exnihilosequentia/<folder that shows, what you want to add>/<name of the object you add>.json
e.g. /rempler/data/exnihilosequentia/heat/uranium_block_op.json
just paste the thing you want to add like compost, heat, fluidtransform etc.
you can also look at the resources of exnihilo [here](https://github.com/NovaMachina-Mods/ExNihiloSequentia/tree/1.16/src/main/resources/data/exnihilosequentia/recipes)

**Comment by trogarus** [comment]
> 
> 
> pretty easy.
> the datapack has to be something like this:
> /yourdatapackname/data/exnihilosequentia/<folder that shows, what you want to add>/.json
> e.g. /rempler/data/exnihilosequentia/heat/uranium_block_op.json
> just paste the thing you want to add like compost, heat, fluidtransform etc.
> you can also look at the resources of exnihilo [here](https://github.com/NovaMachina-Mods/ExNihiloSequentia/tree/1.16/src/main/resources/data/exnihilosequentia/recipes)

The link is much helpful. Much appreciated.

**Comment by trogarus** [comment]
To be clear, for example, if I wanted to add a crucible heat source, it would be /yourdatapackname/data/exnihilosequentia/heat/uranium-block.json with the heat data in the json file correct?

**Comment by remplerus** [comment]
yes

**Comment by trogarus** [comment]
Thanks much for your time and assistance.
