### ISSUE TITLE
FluidItem with fluid output

### ISSUE THREAD

**Issue by DrUse1** [NovaMachina/ExNihiloSequentia#189]
I'm making a modpack and I would like to use the FluidItem recipe (with kubejs) to get oil but it's the recipe type only output ItemStack

Recipe example :

{
  "type": "exnihilosequentia:fluid_item",
  "fluid": {
    "fluid": "minecraft:water"
  },
  "input": {
    "item": "minecraft:coal"
  },
  "result": {
    "**fluid**": "pneumaticcraft:oil"
  }
}

**Comment by remplerus** [comment]
use fluid transformation instead of fluid item

**Comment by DrUse1** [comment]
How do I make the transform instant ?

**Comment by remplerus** [comment]
only way is to set it to 1 second in config, just set a number at "secondsToTransformFluid" greater than 1
maybe in the future we add the time to the json but atm the config is the only way

**Comment by DrUse1** [comment]
ok thanks !
