### ISSUE TITLE
Tag support 

### ISSUE THREAD

**Issue by BedrockLegends** [NovaMachina/ExNihiloSequentia#19]
**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like**

I would like to suggest that this mod takes full advantage of the Tag system forge and Minecraft have in place. This would allowed Your mod to work with all other mods that would be released.

**Comment by NovaMachina** [comment]
The mod does support the Tag system. See the [wiki](https://ex-nihilo-sequentia.readthedocs.io/en/latest/). The configuration section of each "machine" contains instructions on how to configure drops an whether it supports tags.
