### ISSUE TITLE
Wooden Crucible crashes my game

### ISSUE THREAD

**Issue by SpeedWeed17** [NovaMachina/ExNihiloSequentia#190]
[crash-2021-04-29_21.49.32-server.txt](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/6401119/crash-2021-04-29_21.49.32-server.txt)

**Comment by remplerus** [comment]
problem is, i cant recreate the issue. if its possible, can you pack the corrupted world and send it to us, so we can investigate and solving the issue? (or atleast make a workaround)
