### ISSUE TITLE
"Carry On" mod allows mesh duplication

### ISSUE THREAD

**Issue by printidentity** [NovaMachina/ExNihiloSequentia#193]
The Carry On mod allows you to duplicate an infinite amount of meshes.

Pick up the sieve with a mesh in it (shift right-click), put the sieve back down, then pick it up again, repeat.
Sieve will drop another mesh every time you pick it up.

Sieve is picked up with mesh, and is put back down with mesh, sieve does not drop any meshes.

Minecraft Version: 1.16.5
Forge Version: 36.1.0
Ex Nihilo: Sequentia Version: 2021-04-17 2.0.2.5

The sieve registers the shift-right click, which is meant to remove the mesh from the sieve, but Carry On also registers it to pick up the block. Carry on copies the sieves data before ex-nihilo causing the mesh to drop, but also pick up a sieve with the mesh still in it.

**Comment by remplerus** [comment]
Duplication of #50

**Comment by ModernGamingWorld** [comment]
Fixed By @remplerus and should be fixed in the Next Release
