### ISSUE TITLE
Fired Crucible shows error instead of smelting information when used on Forge Server

### ISSUE THREAD

**Issue by minutus0815** [NovaMachina/ExNihiloSequentia#200]
When trying to smelt cobblestone in a crucible an error appears when the crucible is focused (Hwyla/TOP). The cobblestone seems not to smelt. If you wait for a while and try to pull lava out, the buckit will not have lava in it. 
Running the server world on client showed me: it worked there and the cobble was about to smelt.

This only appears on a server, client side works pretty fine. 

**To Reproduce**
Set up a server, join world, build crucible and click cobblestone into it. 

**Expected behavior**
Smelting cobblestone like it does client only.

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.1.16
Ex Nihilo: Sequentia Version: 2.0.2.6 (5/1/2021)

I did not find a log entry for it, neither in server nor in client log.

**Comment by remplerus** [comment]
can u screenshot the error?

**Comment by minutus0815** [comment]
Place a crucilbe
right-click with cobblestone in hand
![Before-right click](https://user-images.githubusercontent.com/84126793/119473666-ad24d080-bd4b-11eb-8a2e-19d2afe9e6dd.png)
Error appears, no smelting visible
![After-right-click](https://user-images.githubusercontent.com/84126793/119473735-bd3cb000-bd4b-11eb-9025-589866ba1a09.png)

Hope it helps

**Comment by NovaMachina** [comment]
I've followed the steps that you've given, but I cannot reproduce it. Also, you don't have a heat source below the crucible which is why its not melting the cobblestone.

**Comment by minutus0815** [comment]
It is a pity, but I'd say if you can't reproduce it there is nothing you can do. I fear this might be caused by any other element outside of ex nihilo.

PS: Of course, there is a heat source beneath the crucible ;o)
