### ISSUE TITLE
[Compat] Crooks don't multiply drops from Dynamic Trees leaves

### ISSUE THREAD

**Issue by laceflower** [NovaMachina/ExNihiloSequentia#202]
**Describe the bug**
When crooking leaves from Dynamic Trees trees, the crook doesn't multiply the drops given. 

**To Reproduce**
1. Grow a tree from a DT seed
2. Break leaves from the tree with a crook
3. Most leaves will fall to drop anything

**Expected behavior**
DT leaf drops get rolled multiple times

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.1.7
Ex Nihilo: Sequentia Version: 2.0.2.6
DT version: 0.10.0-beta10

**Comment by NovaMachina** [comment]
The crook only multiplies drops of blocks that are considered "crookable". These blocks are defined by datapacks/CraftTweaker recipes. Any block that has a crook recipe will be considered "crookable". In order for Dynamic Trees leaves to be considered "crookable" you will need to add a recipe for them, for with the results could be empty and it would simply multiply the drops.

**Comment by NovaMachina** [comment]
Otherwise, the standard loot table will apply with no multiplication.
