### ISSUE TITLE
Allow Jsons to be reloaded in game with /reload

### ISSUE THREAD

**Issue by BedrockLegends** [NovaMachina/ExNihiloSequentia#21]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like to suggest that when you use the /reload command that it will reload the jsons file for ex nihilo

**Comment by NovaMachina** [comment]
Added a specific command to reload registries. Allows the individual reload of a registry rather than all at once (although there is a command to reload all at once.
