### ISSUE TITLE
Createmod patch

### ISSUE THREAD

**Issue by ProfessorBustanut** [NovaMachina/ExNihiloSequentia#212]
**Is your feature request related to a problem? Please describe.**
N/A
**Describe the solution you'd like**
limesand is made from crushing sand the same as dust i think it should be sift able the same as dust
**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by NovaMachina** [comment]
A recipe can be created that has limesand as the input that would make it siftable.
