### ISSUE TITLE
Feature Request: Tetra Compatibility

### ISSUE THREAD

**Issue by Angular-Angel** [NovaMachina/ExNihiloSequentia#213]
**Is your feature request related to a problem? Please describe.**
So I like to use both Ex Nihilo and Tetra, but the two have relatively poor compatibility together. In particular, they both have hammers with overlapping recipes, and ex nihilo adds a number of tools that cannot be repaired, upgraded, or customized via Tetra.

**Describe the solution you'd like**
Create a compatibility mod that will remove the ex nihilo hammer when Tetra is present, and add it's functionality to the Tetra hammer. Add a tetra Crook with all the usual tetra functionality, and allow ex nihilo crooks to be upgraded to match.

**Describe alternatives you've considered**
I have also submitted this as an issue with Tetra: https://github.com/mickelus/tetra/issues/436

**Comment by NovaMachina** [comment]
Closed due to comments made in tetra repo.
