### ISSUE TITLE
Possibilty to enchant meshes

### ISSUE THREAD

**Issue by Ancientmelon** [NovaMachina/ExNihiloSequentia#214]
**Is your feature request related to a problem? Please describe.**
I always liked to enchant my meshes in the 1.12 version. It added a different way of upgrading your 
sieves apart from using auto sieves or a big sieve array.

**Describe the solution you'd like**
It would be really nice if you would bring back the enchants from 1.12 like:
-sieve efficiency
-sieve fortune
-sieve luck of the sea

**Describe alternatives you've considered**
Maybe add enchants that have a trade-off, like:
-an enchant that increases the chances for some item categories (for example gems/ ores) but lowers the chances for the others that this mesh can give you
-an enchantment that makes the gaps of the meshes bigger, which gives you more speed, but because of the bigger gaps, you will "miss" some items (for example smaller/ more valuable things).

**Additional context**
I really like your mod, and I am always happy if it appears in a modpack i play. Thank you for your continuing work.

**Comment by remplerus** [comment]
duplication of #136
