### ISSUE TITLE
config reading issue Compost

### ISSUE THREAD

**Issue by niemandvs** [NovaMachina/ExNihiloSequentia#216]
**Is your feature request related to a problem? Please describe.**
there is a configreading  thing thats not so important but its annoying:

#Compost Configs
	[barrel.compost]
		#Number of seconds to spawn mobs (Default: 10)
		#Range: > 1
		secondsToCompost = 10

**Describe the solution you'd like**
#Compost Configs
	[barrel.compost]
		#Number of seconds to **### compost** (Default: 10)
		#Range: > 1
		secondsToCompost = 10

**Comment by remplerus** [comment]
fixed in next version
