### ISSUE TITLE
Crash using Tags in Json

### ISSUE THREAD

**Issue by BedrockLegends** [NovaMachina/ExNihiloSequentia#22]
**Describe the bug**
as soon as I launched with using a tag inside one of the Json, it crashed me to desktop

**To Reproduce**
1. Place block '...'
2. Right click on '...'
3. Do thing '...'

example

[
  {
    "entry": "tag:minecraft:leaves",
    "fluid": "minecraft:water",
    "amount": 250
  }
]
inside the Json and it crashed

**Expected behavior**

**Screenshots**

**Version**
Minecraft Version: 1.15.2
Forge Version: 31.1.61
Ex Nihilo: Sequentia Version: 2020-08-09-11-59-99

**Additional context**
Stack traces and log files are nice to have. Submit all files through [Gist](https://gist.github.com/) or [Pastebin](https://pastebin.com/) and place the links here.

https://gist.github.com/BedrockLegends/ff3ff610c56785213d3817f639aca166

**Comment by NovaMachina** [comment]
The Minecraft tag for leaves is "minecraft:leaves".

See the [Minecraft Wiki](https://minecraft.gamepedia.com/Tag).
