### ISSUE TITLE
Sieve does not exist

### ISSUE THREAD

**Issue by EkaPossi** [NovaMachina/ExNihiloSequentia#240]
**Describe the bug**
The sieve recipe and item don't exist in my personal modpack. I can still craft the mesh.
**To Reproduce**
1. Place block '...'
2. Right click on '...'
3. Do thing '...'

**Expected behavior**
Being able to craft a Sieve and use it to get ore pieces.
**Screenshots**
[2021-06-27_10 35 22](https://user-images.githubusercontent.com/83571241/123543314-83016c80-d756-11eb-88d1-b9213c1b5c2f.png)

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.1.0
Ex Nihilo: Sequentia Version: 2021-06-16-2.0.2.8

**Additional context**
Add any other context about the problem here. The mesh can be crafted but the sieve doesn't even exist.
Stack traces and log files are nice to have. Submit all files through [Gist](https://gist.github.com/) or [Pastebin](https://pastebin.com/) and place the links here.

[AB#65](https://dev.azure.com/novamachina/9b4371f9-393b-4d7d-8cb9-1f6c864e3511/_workitems/edit/65)

**Comment by remplerus** [comment]
sieve does exist, just not with the planks as recipe. idk why it didn't changed it back to planks, but as of version 2.0.2.8 you have to use stripped logs

**Comment by EkaPossi** [comment]
> sieve does exist, just not with the planks as recipe. idk why it didn't changed it back to planks, but as of version 2.0.2.8 you have to use stripped logs

thank you for your helpful tip. Good to know that the sieve exists.

**Comment by NovaMachina** [comment]
The recipes did not get generated again before the update was pushed out. I'll see what I can do to fix this.
