### ISSUE TITLE
Crash with non default wooden crucible heat rate

### ISSUE THREAD

**Issue by truehiddenevil** [NovaMachina/ExNihiloSequentia#244]
**Describe the bug**
Crash on woodHeatRate =/= 2

**To Reproduce**
1. Change woodHeatRate to a number other than 2
2. Attempt to load any world with a wooden crucible in it
3. Minecraft will crash with Error Code 0

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.1.16
Ex Nihilo: Sequentia Version: 1.16-2.0.2.6

see also issue #190 
My server error log is pretty much identical to the one in that issue

[AB#67](https://dev.azure.com/novamachina/9b4371f9-393b-4d7d-8cb9-1f6c864e3511/_workitems/edit/67)

**Comment by remplerus** [comment]
it's already fixed with later versions, try them first before making new issues.
