### ISSUE TITLE
Log is spammed with "Unable to resolve texture due to reference chain texture->texture in exnihilosequentia:block/mesh_base"

### ISSUE THREAD

**Issue by Goldenlion5648** [NovaMachina/ExNihiloSequentia#246]
**Describe the bug**
Console spammed on game startup/ reload

**To Reproduce**
1. Start game with ex nihilo sequentia
2. Look at console when game has finished loading

**Expected behavior**
No console spam

**Screenshots**
[22:11:40] [Render thread/WARN] [minecraft/BlockModel]: Unable to resolve texture due to reference chain texture->texture in exnihilosequentia:block/mesh_base

is repeated hundreds of times

**Version**
Minecraft Version: 1.16.4
Forge Version: 36.1.61
Ex Nihilo: Sequentia Version: exnihilosequentia-1.16-20210628182320.jar (from 6/28/2021)

**Additional context**
game log: https://gist.github.com/Goldenlion5648/3dfbae9c4208e47b008d4af3095eb730

[AB#68](https://dev.azure.com/novamachina/9b4371f9-393b-4d7d-8cb9-1f6c864e3511/_workitems/edit/68)

**Comment by remplerus** [comment]
can we have the modlist? it might be something with mods cause i can't reproduce it

**Comment by Goldenlion5648** [comment]
Apologies, its a bit long: [mod list](https://gist.github.com/Goldenlion5648/d9f8084b32c1241bd182a6b1c916a2f8)

(about 95 mods) If there is more I can do, let me know

**Comment by remplerus** [comment]
i found the mod causing this issue.... and its CTM (used for chisel) and idk why this is happening, but im investigating it

**Comment by remplerus** [comment]
https://github.com/Chisel-Team/ConnectedTexturesMod/issues/149

this seems to be a heavy bug caused by CTM, we can't do anything due to this bug. only thing is disabling ctm and live without chisel or ignoring it...

**Comment by remplerus** [comment]
i found the problem and made a PR for it
