### ISSUE TITLE
Graphical (?) Issue when using Auto Hammers

### ISSUE THREAD

**Issue by xdelphii** [NovaMachina/ExNihiloSequentia#250]
**Describe the bug**
Auto hammers/heavy auto hammers causing graphical errors (?) when actively hammering stone. The error includes a large diamond/square around the sun and makes other items flicker between visible/invisible or remain entirely invisible. 
It remains functional, but the visual impact is persistent and incompatible with playing (as you can't see things around you, but for their thin black outline)

**To Reproduce**
Place auto hammer/heavy auto hammer (no issue)
Power auto hammer/heavy auto hammer (no issue)
Provide or connect to source of cobblestone, machine begins working and graphical errors commence. 

**Expected behavior**
No disappearing items around it.

**Screenshots**
![2021-07-26_14 41 53](https://user-images.githubusercontent.com/87985958/127000856-11c07ecf-7b44-451f-84a6-785da5a43e3f.png)
SCREENSHOT 1: Auto sieve setup, powered and working (no issues)

![2021-07-26_14 42 09](https://user-images.githubusercontent.com/87985958/127000958-b470bf2b-70aa-45a7-9832-f0e4745c3e18.png)
SCREENSHOT 2: Auto hammer placed down, unpowered (no issues)

![2021-07-26_14 42 25](https://user-images.githubusercontent.com/87985958/127001048-b6bb7cda-ca69-496e-9642-c045cd904d5c.png)
SCREENSHOT 3: Auto hammer placed down, powered with solar panel/tested with other power inputs (no issue)

![2021-07-26_14 42 42](https://user-images.githubusercontent.com/87985958/127001224-4443f9a2-563d-4851-8996-68e7568374ed.png)
SCREENSHOT 4: Auto hammer provided with cobblestone, now workings, graphical errors commence: sky altered, surrounding items no longer visible (not removed, just invisible) 

![2021-07-26_14 42 52](https://user-images.githubusercontent.com/87985958/127001513-fcde5699-7a87-4149-89a1-09b62478f74c.png)
SCREENSHOT 5: Auto hammer deleted, items return to visible and sky is normal again.

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.1.63
Ex Nihilo: Sequentia Version: 2021-06-28-18-23-20

**Additional context**
Sorry if this is unrelated to Ex Nihilo, however as the issue seems to arise solely through use of the auto hammer, it felt pertinent to report here first. 

Log report, lots of repeats of:
[14:12:45] [Render thread/WARN]: Unable to resolve texture due to reference chain texture->texture in exnihilosequentia:block/mesh_base

Gist link for log:
https://gist.github.com/xdelphii/0ce94fc653f26f1ca21afe52e92cedb7

[AB#73](https://dev.azure.com/novamachina/9b4371f9-393b-4d7d-8cb9-1f6c864e3511/_workitems/edit/73)

**Comment by NovaMachina** [comment]
Ex Nihilo: Sequentia does not add the auto hammer. That would be Ex Compressum.

**Comment by remplerus** [comment]
1. autohammer isn't from exnihilo, please make report at excompressum
2. the log spam is a incompat with ctm. a fix from exnihilo will come in the new version.

**Comment by xdelphii** [comment]
Drat, sorry for wasting your time reporting on the wrong mod @NovaMachina!
