### ISSUE TITLE
Broken Textures When Sieving Custom Added Blocks

### ISSUE THREAD

**Issue by Darkosto** [NovaMachina/ExNihiloSequentia#254]
**Describe the bug**
The way it is currently setup, Ex Nihilo is looking for a path for block models. If that mod changes anything, then ex nihilo's textures show as broken. This can be resolved by changing how you get the block model and also ensuring you won't have to update your mod every time another mod changes. This most likely will be necessary to change in the Tcon compatibility mod but may also affect every compat mod. @remplerus May need to check this out

Both of these are examples to help you out:
https://github.com/SlimeKnights/Mantle/blob/1.16/src/main/java/slimeknights/mantle/client/model/util/ModelHelper.java#L59

https://github.com/SlimeKnights/Mantle/blob/1.16/src/main/java/slimeknights/mantle/client/model/util/ModelHelper.java#L110

**Expected behavior**
When adding custom blocks, Ex Nihilo should not rely on files existing in the same location for block models to show correctly. 

**Screenshots**
![image](https://user-images.githubusercontent.com/10309699/128400770-4b607965-d344-4d91-9191-10d289c1ac86.png)

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.2.2
Ex Nihilo: Sequentia Version 1.16-20210628182320

[AB#76](https://dev.azure.com/novamachina/9b4371f9-393b-4d7d-8cb9-1f6c864e3511/_workitems/edit/76)

**Comment by remplerus** [comment]
Duplication of #226 but will be fixed in newest Version
