### ISSUE TITLE
Autoclicker Protection Not Functioning Properly

### ISSUE THREAD

**Issue by Darkosto** [NovaMachina/ExNihiloSequentia#258]
**Describe the bug**
Despite not using a macro or an auto-clicker, I am set on fire due to the auto-clicker prevention mechanic. From what I can see, there is no config option to disable this and I feel as if I am being penalized for using the mod correctly (my apologies if this config option exists already and I've missed it). When I sieve, I generally hold the mouse button down. I would attribute this to a low or inconsistent TPS but I have experienced it with 20tps on a brand new void world. Can we please an option to disable this functionality, it's extremely frustrating to be set on fire constantly. 

I also feel as if those with physical impairments or limitations are being penalized by a mechanic meant to dissuade people from cheating. Not everyone is able to click or hold the mouse button down for the long periods that sieving requires.

**To Reproduce**
place down sieves, either 1 or multiple, and hold the mouse button down to sieve blocks. 

**Expected behavior**
I should not be set on fire if I am using the mod in the intended fashion.

**Screenshots**

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.2.2
Ex Nihilo: Sequentia Version: 1.16-20210628182320

**Additional context**
Stack traces and log files are nice to have. Submit all files through [Gist](https://gist.github.com/) or [Pastebin](https://pastebin.com/) and place the links here.

[AB#77](https://dev.azure.com/novamachina/9b4371f9-393b-4d7d-8cb9-1f6c864e3511/_workitems/edit/77)

**Comment by remplerus** [comment]
i'll just leave a comment to my PR i made some months ago with another version of configurable sieve clicks #155 

€: I made a config in my newest PR to disable it. (It's enabled by default. Just refresh config file when released)

**Comment by Darkosto** [comment]
Any luck on getting this added to the mod? Further testing has shown players getting caught on fire for simply holding the mouse button down when sieving.

**Comment by remplerus** [comment]
hmm.. i might have a solution, but i need your help as i cant reproduce this. I'll upload on my repo a modified version, where you have to edit the config file once generated. there'll be a line called testMakroTime where you can modify the number. i just need to know which number it doesn't burns you (and other players too). first try lowering the number, it shouldnt affect anything besides the timing for burning. good luck.
here's the link: https://github.com/remplerus/ExNihiloSequentia/releases/download/debug-makro/exnihilo-burning-makro.jar
(if you don't like to use the jar, you can compile it yourself. just use my repo)

**Comment by Darkosto** [comment]
It might also be helpful that this happens on a server. I don't recall it happening in single-player because it's been a while since I've tested in that way.

**Comment by NovaMachina** [comment]
I've gone ahead and simply removed the part where you get set on fire. Autoclick prevention is still in place.
