### ISSUE TITLE
[1.16.2] Mod Support for the following

### ISSUE THREAD

**Issue by BedrockLegends** [NovaMachina/ExNihiloSequentia#26]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Hi, I was wondering if you could add mod support for the following mods as they update to 1.16.2.  

Ae2, Refined Storage, mekanism, Rftools, Industrial Foregoing, and pneumaticcraft-repressurized. I plan to suggest more mod support as mods update

**Comment by NovaMachina** [comment]
What exactly are you wanting support for from these mods? Are there any ores or resources that cannot be added via the Json registries?

**Comment by BedrockLegends** [comment]
Well yes some of those mods I did list have ores and such, but I figured the ones with the ores and such could have ore chunks for them like other mods that you have supported so far

**Comment by BedrockLegends** [comment]
Thermal Expansion and The other Thermal mods when they come out and I know this might be a dumb suggestion, but could u look at adding support for Extended Crafting to have ore chunks

**Comment by NovaMachina** [comment]
Added for the next update.
