### ISSUE TITLE
Graphical Issue When Sieving Blocks

### ISSUE THREAD

**Issue by Darkosto** [NovaMachina/ExNihiloSequentia#262]
**Describe the bug**
When Sieving blocks (dust, gravel, sand, etc.) The texture of the block shows through the side of the sieve. This seems to only happen on the South and East side of the sieve blocks. See picture below

**To Reproduce**
1. Place down sieve
2. sieve a dust block
3. observe the graphical issue

**Expected behavior**
The block being sieved should not show through the side of the sieve

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.2.4
Ex Nihilo: Sequentia Version: 20210826035238

**Additional context**
![image](https://user-images.githubusercontent.com/10309699/133165671-6a031c49-ca62-467b-ac1c-7591c1c0e7bd.png)

[AB#82](https://dev.azure.com/novamachina/9b4371f9-393b-4d7d-8cb9-1f6c864e3511/_workitems/edit/82)

**Comment by remplerus** [comment]
argh... i tested it and it hasn't happened :( i'll make pr for it. should be fixed in next version

**Comment by captinwill** [comment]
hey i cant make an issue but the mod does not make copper an ore I could sieve if i am using tinkers construct

**Comment by captinwill** [comment]
i cant make a bug report

**Comment by remplerus** [comment]
should be fixed with next version
