### ISSUE TITLE
Compost recipes show wrong GUI

### ISSUE THREAD

**Issue by tahg** [NovaMachina/ExNihiloSequentia#263]
**Describe the bug**
The JEI GUI for Compost is misleading. It shows the crook GUI, when it should be using the generic item <- items GUI.

**To Reproduce**
1. Look at any Compost recipe in JEI

**Expected behavior**
Compost should use the 4th GUI in jei_mid.png and appropriate slots instead of the 3rd.

**Screenshots**

**Version**
Minecraft Version: 1.16.5
Forge Version: 1.16.5-36.2.4
Ex Nihilo: Sequentia Version: 1.16-20210826035238

**Additional context**
Stack traces and log files are nice to have. Submit all files through [Gist](https://gist.github.com/) or [Pastebin](https://pastebin.com/) and place the links here.

[AB#83](https://dev.azure.com/novamachina/9b4371f9-393b-4d7d-8cb9-1f6c864e3511/_workitems/edit/83)

**Comment by remplerus** [comment]
thank you for the bug report. i made a PR for this problem. should be fixed in next version.
