### ISSUE TITLE
Campfires don't provide heat to Crucibles

### ISSUE THREAD

**Issue by moon-st0ne** [NovaMachina/ExNihiloSequentia#265]
**Is your feature request related to a problem? Please describe.**
Two sources of fire do not provide any heat to Crucibles. The Shroomlight, which was added after Campfires, does provide heat - this makes me think that Campfires were missed accidentally.

**Describe the solution you'd like**
Campfires and Soul Campfires should provide the same amount of heat as normal/soul fires do. Because that's literally what they are.

**Describe alternatives you've considered**
N/A

**Additional context**
Tested on latest 1.16.5 versions with just JEI and Ex Nihilo Sequentia.

[AB#87](https://dev.azure.com/novamachina/9b4371f9-393b-4d7d-8cb9-1f6c864e3511/_workitems/edit/87)

**Comment by remplerus** [comment]
that's true. we might add it to next 1.16.5 release. as a workaround, you can make a datapack and add it yourself.
