### ISSUE TITLE
Low Tier Hopper

### ISSUE THREAD

**Issue by papaworld** [NovaMachina/ExNihiloSequentia#27]
Feature: Create a hopper made from wood similar to 1.12.2 Tinker's Construct. 1 slot for 1 stack... slower than MC Iron Hopper. For 1.15.2 and 1.16.x

Delighted to see Ex Nihilo back on forge! Thank You!

**Comment by Blackout03** [comment]
Whenever tinkers construct updates it will probably have it anyway

**Comment by Algester** [comment]
There is already a 1.16 version of tinkers but highly alpha if you do like burning your worlds every so often it might be a good place to start

**Comment by NovaMachina** [comment]
This is kind of outside the nature of Ex Nihilo.
