### ISSUE TITLE
Large Fern Seed only plants half the fern

### ISSUE THREAD

**Issue by Wxrlds** [NovaMachina/ExNihiloSequentia#272]
**Describe the bug**
When you place a large fern seed only half the plant is placed

**To Reproduce**
1. Place large fern seed
2. Look at result

**Expected behavior**
Both blocks of the large fern get placed

**Screenshots**
![image](https://user-images.githubusercontent.com/42120270/139125352-cbcb4d8d-d164-4270-b3e0-422bd889620a.png)

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.2.2
Ex Nihilo: exnihilosequentia-1.16-20211004011236

[AB#91](https://dev.azure.com/novamachina/9b4371f9-393b-4d7d-8cb9-1f6c864e3511/_workitems/edit/91)

**Comment by remplerus** [comment]
added in new version
