### ISSUE TITLE
Copper ingot 

### ISSUE THREAD

**Issue by Bigbeatle** [NovaMachina/ExNihiloSequentia#274]
**Describe the bug**
When creating copper ingot, the item is different (icon and name) as original one in minecraft  for my french version. for other ingot its working Gold ingot = Lingot d'or,  Zinc ingot =barre de zinc etc... except for copper ingot <> lingot de cuivre. to obtain good item I need to split copper ingot and re compact it into lingot de cuivre (see attached picture with the different step to obtain ingot)

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.2.8
Ex Nihilo: Sequentia Version:1.16-20211004011236
Create v0.3.2.f
<img width="384" alt="2021-10-31 10_20_34-Minecraft_ 1 16 5 - Solo" src="https://user-images.githubusercontent.com/93468522/139576087-90844c94-fb10-458c-a1dd-f75f29fabe8a.png">

[AB#94](https://dev.azure.com/novamachina/9b4371f9-393b-4d7d-8cb9-1f6c864e3511/_workitems/edit/94)

**Comment by ghost** [comment]
First ingot in your inventory next to gold chunk isn't even gold, its brass
and the reason why its changing texture cause we didn't add any copper nugget in EXN, so its using other mods ones so its overriding the texture to use the one who match the copper ingot(in this case here, create copper ingot)

**Comment by NovaMachina** [comment]
This does not appear to be a bug, but rather just a mechanic of the recipe system.
