### ISSUE TITLE
Feature Request: Create Compatibillity

### ISSUE THREAD

**Issue by InstSnipe** [NovaMachina/ExNihiloSequentia#276]
I have been trying to use Create mod with ex nihlio and it wouldnt work.

I have seen that enableCreate was listed on the config in the wiki but not when i checked it.

The feature is to enable nuggets from create mod to be obtainable from sieves

[AB#95](https://dev.azure.com/novamachina/9b4371f9-393b-4d7d-8cb9-1f6c864e3511/_workitems/edit/95)

**Comment by NovaMachina** [comment]
As noted on the CurseForge page, the wiki is out of date. That config does not exist anymore. By default, Create should be detected and copper and zinc ores should be enabled.

**Comment by InstSnipe** [comment]
> As noted on the CurseForge page, the wiki is out of date. That config does not exist anymore. By default, Create should be detected and copper and zinc ores should be enabled.

I am currently using SkyFactory One Remade
I think i am better off removing thermal which is what conflicts with create 
I also am unable to smelt zinc ore chunks
