### ISSUE TITLE
Break the infected leaves without dropping the string

### ISSUE THREAD

**Issue by joe-vettek** [NovaMachina/ExNihiloSequentia#289]
I use the latest version, but use crook to break the infected leaves without falling.

[AB#106](https://dev.azure.com/novamachina/9b4371f9-393b-4d7d-8cb9-1f6c864e3511/_workitems/edit/106)

**Comment by joe-vettek** [comment]
exnihilosequentia-1.16-20211123-032540 works.
exnihilosequentia-1.16-20211128-042122 not.

**Comment by ghost** [comment]
Use a previous version until we fix the issue

**Comment by joe-vettek** [comment]
Very pleasantly surprised by the speed of response. Expect it to be repaired！

**Comment by ghost** [comment]
No problem
