### ISSUE TITLE
[Visual] No liquid in containers

### ISSUE THREAD

**Issue by Quenteez** [NovaMachina/ExNihiloSequentia#294]
**Describe the bug**:
When I put organic matter in a barrel, or rain fills the barrel, there is no texture of liquid / fullness of the barrel.
Exactly the same with the crucible.

**To Reproduce**:

1. Put down the barrel
2. Turn on the rain
3. Observe how it remains empty, without water (visually).

- Put down the barrel
- Put organic matter in it for composting
- Observe how it remains empty, without green organic textures (visually).
- After composting there, of course, there will still be a block of dirt.

1. Place the burnt crucible above the lava block.
2. Throw a boulder into it.
3. Observe the cobblestone inside it until it is completely melted (then the crucible will be empty inside, without lava, again visually).

- Place the wooden crucible above the torch.
- Throw the sprouts into it.
- Observe the sprouts inside it until they are completely squeezed out (then the crucible will be empty inside, without water, again visually).

**Expected behavior**:
I expected to see what should be (organic matter, water, lava)

**Screenshots**:
https://ibb.co/R92tLDV
https://ibb.co/jMZSpxD
https://ibb.co/wWRz3Tw
https://ibb.co/fYZRWDk

**Version**:
Minecraft Version: 1.16.5
Forge Version: 36.1.1
Ex Nihilo: Sequentia Version: 1.16-20211223-220618

**Additional context**:
I can't provide anything else, at most a list of installed mods (https://ibb.co/LNFKNFG)

I will also add that the sieve perfectly displays the textures of gravel, etc. However, I previously used version 1.16-2.0.2.3 of the mod and there the sieve did not show gravel, there were also problems with barrels and crucible. The only thing that worked was a composting barrel (it showed organic textures).

**Comment by remplerus** [comment]
this is not 100% right. this one only happens, if you relog to server or singleplayer. but i can confirm that. trying to fix is asap

**Comment by Quenteez** [comment]
I didn't quite understand what you meant. But I just created a single world (new), put all the problematic containers, there is also no visual.

But I hope that you will fix it soon, thank you.

**Comment by remplerus** [comment]
pretty easy. i create a new world, place barrels, crucibles and sieves. put something in them and relog. as long as they have something to do, they should have "visuals". you'll see that on sieves if you dont sieve till the end (the block isn't sieved completly). just relog and that block doesn't update.

**Comment by Quenteez** [comment]
Ah, I got it, good.  However, when can you fix this "visual" problem?  I am currently developing a SkyBlock server for players on my project, I would really like them to visually distinguish the processes in barrels / crucibles.  It would be convenient, after all.

**Comment by Quenteez** [comment]
**Amazing! Everything is fixed.**

(version: exnihilosequentia-1.16-20220115-185452)
