### ISSUE TITLE
Possibility to customise breakable block with hammer

### ISSUE THREAD

**Issue by J0b0w** [NovaMachina/ExNihiloSequentia#297]
Hello,

It's possible to add hammer recipe with datapack, but breakable block list isn't configurable.
ie. : I can add hammer recipe for blackstone, but a can't harvest  blackstone with hammer.

It's possible to add this feature ?

**Comment by remplerus** [comment]
this feature won't be added to 1.16 version as it is out of forge's LTS. Therefore we won't make this possible for 1.16 version. Closed.
