### ISSUE TITLE
no interacting with bucket from Ceramics

### ISSUE THREAD

**Issue by GalaxyOfZero** [NovaMachina/ExNihiloSequentia#299]
**Describe the bug**
i can not pick up  Water from the Barrel withe a bucket from Ceramics

**To Reproduce**
1. Barrel with water
2. Right click on 'Barrel with a bucklet from Ceramics'
3. Do thing '...'
4. nothing happens

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.2.22
Ex Nihilo: Sequentia Version: 1.16-20220115-185452

**Comment by NovaMachina** [comment]
Duplicate of #201

**Comment by remplerus** [comment]
can you give more information on what version of ceramics and mantle you use?

**Comment by GalaxyOfZero** [comment]
i use Ceramics-1.16.5-1.6.3 and Mantle-1.16.5-1.6.157
