### ISSUE TITLE
wood crucible does not convert leaves or saplings to water latest build of minecraft forge and exnihiliosequentia

### ISSUE THREAD

**Issue by fistidgious** [NovaMachina/ExNihiloSequentia#30]
**Describe the bug**

**To Reproduce**
1. Place block '...'
2. Right click on '...'
3. Do thing '...'

**Expected behavior**

**Screenshots**

**Version**
Minecraft Version: 1.15.2
Forge Version: 31.1.61
Ex Nihilo: Sequentia Version: 2020-08-09-11-59-99

**Additional context**
Stack traces and log files are nice to have. Submit all files through [Gist](https://gist.github.com/) or [Pastebin](https://pastebin.com/) and place the links here.

**Comment by NovaMachina** [comment]
Which version? 1.15 or 1.16?

**Comment by NovaMachina** [comment]
According to my testing, all the latest versions of the mod and forge work as intended.

**Comment by fistidgious** [comment]
not sure what has changed but crucible is now giving water so no fix required think it may have been a mod conflict thanx for help
