### ISSUE TITLE
Better hitboxes

### ISSUE THREAD

**Issue by IchHabeHunger54** [NovaMachina/ExNihiloSequentia#302]
**Is your feature request related to a problem? Please describe.**
In Minecraft 1.13 and up, Mojang started to make hitboxes actually resemble the block model - think of how chests used to be full blocks, but are not anymore. Therefore, I'd love to see those kinds of hitboxes arrive in Ex Nihilo as well.

**Describe the solution you'd like**
I think the solution is obvious. The "empty" spaces of a model should correspond with the hitbox. For some blocks, e.g. the Crucible, vanilla hitboxes could be reused (cauldron in this case), while others would need to be done from scratch.

**Describe alternatives you've considered**
Well... the alternative is just to continue using the normal block hitbox? I guess?

**Additional context**
If you don't have the time, I'd be willing to do this on my own and PR it in. I'd just wanna get your approval before I start.

**Comment by ghost** [comment]
New models arent in the game yet,hitboxes will be optimized when new models are in the mod

**Comment by IchHabeHunger54** [comment]
Ah, alright. I wasn't aware that new models are coming in the first place.

**Comment by ghost** [comment]
new assets & models are coming soon

**Comment by remplerus** [comment]
this one should be fixed in 1.19, just need some confirmation
