### ISSUE TITLE
ichor dirt recipe fix for exnihilo tinkers

### ISSUE THREAD

**Issue by gorgan184** [NovaMachina/ExNihiloSequentia#303]
cant find the right repo. put it here for now...
for 1.16.5
tinkers uses a weird name for fluid magma cream they call it "magma" not "magma_cream" this change will make this recipe work.

exnihilotinkers-1.16-1.0.0.0.jar\data\exnihilotinkers\recipes\tinkers\casting_ichor_slime_dirt.json

```
{
  "type": "tconstruct:casting_basin",
  "cast": {
    "item": "minecraft:dirt"
  },
  "cast_consumed": true,
  "fluid": {
    "name": "tconstruct:magma_cream",
    "amount": 1000
  },
  "result": "tconstruct:ichor_slime_dirt",
  "cooling_time": 40
}
```

should be

```
{
  "type": "tconstruct:casting_basin",
  "cast": {
    "item": "minecraft:dirt"
  },
  "cast_consumed": true,
  "fluid": {
    "name": "tconstruct:magma",
    "amount": 1000
  },
  "result": "tconstruct:ichor_slime_dirt",
  "cooling_time": 40
}
```
this is where i got the name from:
[https://github.com/SlimeKnights/TinkersConstruct/blob/1.16/src/main/java/slimeknights/tconstruct/fluids/TinkerFluids.java](url)

**Comment by remplerus** [comment]
we already know that, and have fixed it in our repo. we haven't punlished yet because we're adding some new stuff and this needs some testing.

**Comment by remplerus** [comment]
i haven't forgot this. we just decided to release an update for now (with old textures!).
