### ISSUE TITLE
Add Draconic Evolution interoperability  (1.16)

### ISSUE THREAD

**Issue by Travis9x** [NovaMachina/ExNihiloSequentia#306]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
Similar to 1.14, allow for drops of Draconium dust from sifting crushed netherrack and crushed end stone.

**Describe alternatives you've considered**
I tried to see if there was a way to manually add custom drops/ores to the sieves (such as by editing the config, etc.), but I couldn't find a way.

**Additional context**
I think in 1.14, Draconium drops were already limited to diamond meshes only, and I'd recommend keeping it that way, or perhaps even push Draconium up one tier, to Emerald meshes or higher only (since those new mesh tiers were added in 1.16).
I'd also recommend setting the drop rate to be similar to the actual ore spawn rates.  For example, Draconium ore is extremely rare in the overworld, but a little easier to find in the Nether (but still rare), and a common find in the End.  So likewise, getting Draconium dust from sifting stone should be extremely rare (or not at all), uncommon but not too difficult to get from sifting crushed netherrack, and relatively common to get from sifting crushed end stone.
Finally, this change may not even need an extra add-on mod, since it would be as simple as just adding Draconium dust as a drop in the sieve/mesh output.  As far as I'm aware, no other changes would be needed, unless you want to add something like a Draconium-tier mesh or whatever.

**Comment by remplerus** [comment]
using datapack is the way to go. you need a mod to load up datapacks that can add your custom recipes for exnihilo (and other mods). looking at this site you can set that up: https://ex-nihilo-sequentia.readthedocs.io/en/1.16/data_pack/

**Comment by NovaMachina** [comment]
To echo what @remplerus said, you can add sieve drops for Draconic Evolution using either datapacks or CraftTweaker.

**Comment by Travis9x** [comment]
I ended up adding CraftTweaker to my modpack, and using that to add the custom sieve recipes.  However, I would still recommend adding official DE support...ie., possibly some endgame-tier items/machines/equipment utilizing DE resources.  (Draconium hammer?  Draconium mesh?  Draconium crook?  You get the idea... 😉)
