### ISSUE TITLE
Keep getting "Autoclicker Bad" message by just holding right click on mouse while sieving

### ISSUE THREAD

**Issue by LinkTheLinker** [NovaMachina/ExNihiloSequentia#308]
**Describe the bug**
The bug is that if someone sieves massive amounts of gravel, sand, dust, or any sievable block, the chat gets filled at some point with "Autoclicker Bad" without using an autoclicker, only holding right-click on a mouse. An acquaintance of mine has also experienced this. The worst I've had it was that it activated 10 times, just flooding my chat. 

**To Reproduce**
1. Have 8 sieves (you could use more or less realistically)
2. Hold right-click while sieving blocks like gravel or sand as an example (preferably at least 3-8 stacks)
3. Get "Autoclicker Bad" and eventually floods your chat at the end of the sieving session.

**Expected behavior**
What should happen is that "Autoclicker Bad" should only appear if a person is using auto clicker, but not when a regular player is just holding right-click on their mouse.

**Screenshots**

![Picture](https://user-images.githubusercontent.com/25944116/161758679-b77ea39d-aec5-42dc-a5a5-78c1fc325f09.PNG)

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.2.22
Ex Nihilo: Sequentia Version: 20220115-185452

**Additional context**
For context, I am playing the Sky Bees Modpack and on a server where my ping is < 50ms.

**Comment by Lynden-Sylvester** [comment]
I have also been running into this issue.

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.2.21
Ex Nihilo: Sequentia Version: 1.16.20220205-012521

**Additional Context**
I have been developing my own mod pack and everything else works fine except for sieving when I hold down the Right Mouse Button for an extended period of time.

I do not use Macros or auto clickers.

**Comment by Ivniinvi** [comment]
Same issue, I have rebound right click to R because I use a trackpad, and just hold the R key. Please give us a config option to disable it on single player, at least.

**Comment by Diagnul** [comment]
I have also run into this issue while hosting a server. Manually holding right click on an area of sieves for a duration can lead to "Autoclicker Bad" messages being spammed to the client. If this feature cannot be tuned to resolve false positives then please provide an option in the mod config to allow disabling this feature in the future.

**Comment by NovaMachina** [comment]
Hi all, not sure how I missed this bug report. I'll work on a fix for this.
