### ISSUE TITLE
started a new void world with no script just this mod and imersive engineer had the compatibility on in config for imersive ores in sieve played for approx 72 hrs worked up to diamnod mesh had no output of imersive ores.

### ISSUE THREAD

**Issue by fistidgious** [NovaMachina/ExNihiloSequentia#31]
**Describe the bug**

**To Reproduce**
1. Place block '...'
2. Right click on '...'
3. Do thing '...'

**Expected behavior**

**Screenshots**

**Version**
Minecraft Version: 1.15.2
Forge Version: 31.1.61
Ex Nihilo: Sequentia Version: 2020-08-09-11-59-99

**Additional context**
Stack traces and log files are nice to have. Submit all files through [Gist](https://gist.github.com/) or [Pastebin](https://pastebin.com/) and place the links here.

**Comment by fistidgious** [comment]
started a flat world with no grass dirt or bedrock so no ore spawn available and no villages spawning have immersive engineering  also worked up to dimond mesh but getting no ores from sieve for imersive engineering have config set to true for compatibilty for this mod

Forge 34.1.0 , minecraft 1.16.3, gravestone mod 1.16.3-1.0.1, imersive engineering 1.16.3-4.0.1-121, ex nihilio sequentia 1.16- 1.2.1.1

**Comment by NovaMachina** [comment]
I know what the issue is, but are you at least getting other ores?
