### ISSUE TITLE
Empty Tag for Forge ores Cobalt ( Tinkers Addon)

### ISSUE THREAD

**Issue by GalaxyOfZero** [NovaMachina/ExNihiloSequentia#311]
**Describe the bug**
Ex Nihilo: Sequentia - Ex Nihilo: Sequentia - Tinkers Addon
Empty Tag for Forge ores Cobalt and no Cobalt Ore Piece/Chunk in JEI or in the sieve.
it looks like as has Cobalt Piece/Chunk not exists, the Issue page  over cureforge dont work 

**Screenshots**
![image](https://user-images.githubusercontent.com/57020876/167261632-7ac25955-50e7-4fad-aab8-0f1eab36808f.png)

**Version**
Minecraft Version: 1.16,5
Forge Version: 36.2.33
Ex Nihilo: Sequentia Version: 2020-08-09-11-59-99
Ex Nihilo: Sequentia - Tinkers Addon Version: 1.16-20220506-204910.

**Comment by remplerus** [comment]
what modpack do you use?

**Comment by remplerus** [comment]
I'll investigate the problem. until then i achieved the update so noone can download it

**Comment by GalaxyOfZero** [comment]
Your question: what modpack do you use?
A: its my Own modpack call Sky Friends.
i saw a Update for the addon and Crafttweaker say me "recipe does not work"

**Comment by remplerus** [comment]
yeah, i have fixed it with newest version. it should work now. just give feedback if it worked

**Comment by GalaxyOfZero** [comment]
yes its work but now all tools a remove :(

**Comment by remplerus** [comment]
ok, then i'll remove the update completly as it's too game breaking and the updates come with 1.18 update. thanks for testing anyway

**Comment by GalaxyOfZero** [comment]
thanks for breaking  1 houer of work, but its good did  the addon  work now

**Comment by remplerus** [comment]
i already removed the addon, i wont add it back to curse. updates come with 1.18 update
