### ISSUE TITLE
CraftTweaker: Remove Recipe by Input doesn't work

### ISSUE THREAD

**Issue by IHAHAI** [NovaMachina/ExNihiloSequentia#312]
The sieve does not have any input, and I just can delete the output of the sieve. Plz add an input of the sieve and that I can delete the input and change the recipe.

**Comment by remplerus** [comment]
https://ex-nihilo-sequentia.readthedocs.io/en/1.16/crafttweaker/#sieve-recipes

**Comment by remplerus** [comment]
https://docs.blamejared.com/1.16/en/mods/ExNihiloSequentia/Sieving#removal

**Comment by friendlyhj** [comment]
I want to remove **by input**.
For example,
`<recipetype:exnihilosequentia:sieve>.removeRecipeByInput(<item:minecraft:gravel>)` to remove all sieve recipes that the input is gravel. (to remove all ore piece outputs)
But your recipe classes don't override `IRecipe#getIngredient`, CraftTweaker thinks your recipes don't have input, so it can't remove anything.
The method you posted is remove **by output**, I certainly can use it to remove recipes. But I have to list all ore pieces. It is annoying.

**Comment by remplerus** [comment]
well, the title isn't that clear, neither is the description. i reopen the issue as i can't resolve that rn

**Comment by remplerus** [comment]
just for my information: does this issue still exists? in 1.16 and 1.18 version?

**Comment by friendlyhj** [comment]
Sorry for delay, this issue still exists in version `1.16-20220530-185402` and `1.18.2-20220714-011314`.

**Comment by remplerus** [comment]
we'll won't fix that for 1.16 as we decided to make that last version final. your PR for 1.18 looks promising tho.

**Comment by maxel23** [comment]
I think we simply can't remove recipes rn. When I try to remove any recipe, it says "No such member: removeRecipe".

**Comment by remplerus** [comment]
Yes it's not possible until the PR for 1.18 will be merged.
