### ISSUE TITLE
Feature Request: Mystical Agriculture Compatibility

### ISSUE THREAD

**Issue by dBHI-zz** [NovaMachina/ExNihiloSequentia#313]
Hello,

could you please add compatibility for Mystical Agriculture? Mainly add Prosperity Shards to Sieves, e.g. for Crushed Endstone.

Best regards and thanks,
dbHI

**Comment by remplerus** [comment]
You can add prosperity shards to sieve using datapack or crafttweaker.
https://ex-nihilo-sequentia.readthedocs.io/en/1.16/crafttweaker/#sieve-recipes and https://ex-nihilo-sequentia.readthedocs.io/en/1.16/data_pack/#sieve
any discussion will go to discord or the pinned issue!
