### ISSUE TITLE
[1.18+] Addon Request Clarification and Thread

### ISSUE THREAD

**Issue by remplerus** [NovaMachina/ExNihiloSequentia#314]
We move all requests into discussion thread here: #316 
All requests in Issues Tab will be closed without any comment!

Over the past several months, our team has seen many users request addons for various mods. Thanks to the data pack and tag systems put in place by Mojang and the Minecraft Forge team, we do not have to create and addon to be compatible with every mod that exists. We will however discuss creating addons for mods that meet at least one of the following criteria:
- Have a custom ore type that is not included in vanilla Ex Nihilo: Sequentia (i.e., Thermal Foundation or Tinker's Construct)
- Have a custom wood or stone type that is not included in vanilla Ex Nihilo: Sequentia (i.e., Oh The Biomes You'll Go or Biomes O'Plenty)
- Other conditions that may be added as discussion warrants and deems necessary (this conditions list will be modified as appropriate)
- 
This thread will be used for requesting addons that meet at least one of the above criteria, or for discussion about why a mod should receive and addon rather than a data pack.

Any issues requesting compatibility will be close and directed to this thread.

**Comment by Blackout03** [comment]
Mods where both the conditions match be like:

**Comment by NovaMachina** [comment]
Also see the Discussion thread: https://github.com/NovaMachina-Mods/ExNihiloSequentia/discussions/316

**Comment by remplerus** [comment]
closed as pinned and added discussion thread.
