### ISSUE TITLE
[BUG] Right clicking stone barrel full of lava with glowstone dust, does not produce End stone

### ISSUE THREAD

**Issue by iLLHunter** [NovaMachina/ExNihiloSequentia#318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

stone barrel full of lava, right click holding glowstone dust, does nothing. Does not produce end stone, lava remains in barrel

### Expected Behavior

end stone block produced

### Steps to Reproduce

Place stone barrel
use lava bucket on barrel, barrel is full of lava
select glowstone dust in hotbar, right click on lava in barrel

### Minecraft Version

1.18.2

### Forge Version

40.1.20

### Ex Nihilo: Sequentia Version

20220530-183458

### Additional Context

[debug.log](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/8840556/debug.log)

**Comment by remplerus** [comment]
just for my information: does this issue still persist with latest version of ex nihilo?
