### ISSUE TITLE
Crafttweaker: Can't remove sieve recipes 1.18.2

### ISSUE THREAD

**Issue by ElBread3** [NovaMachina/ExNihiloSequentia#319]
[The Crafttweaker 1.16 sieve doc](https://docs.blamejared.com/1.16/en/mods/ExNihiloSequentia/Sieving) says you can remove recipes.
Trying to follow that in 1.18.2 (and latest mod version) with:
<recipetype:exnihilosequentia:sieve>.removeRecipe(<item:minecraft:diamond>);
fails with ex_nihilo_recipes.zs:16:0: ex_nihilo_recipes.zs:16:0: No such member: removeRecipe.
Plz fix

**Comment by NovaMachina** [comment]
You're trying something from 1.16 in 1.18. The versions are not compatible.

**Comment by ElBread3** [comment]
Well is there a way to remove sieve recipes in 1.18 with crafttweaker?

**Comment by remplerus** [comment]
https://docs.blamejared.com/1.18/en/vanilla/how_to/crafting_table#removing-a-recipe
