### ISSUE TITLE
[BUG] <Incompatibility with Bucket Lib>

### ISSUE THREAD

**Issue by TimeheroTH** [NovaMachina/ExNihiloSequentia#323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i pick up a liquid from an exnihilo barrel the liquids could be taken correctly but when i want to put a liquid from the wooden bucket to the exnihilo barrel doesn't work; the liquid stay stucked in the bucket and don't fill the barrel:

https://github.com/NovaMachina/ExNihiloSequentia/blob/1.18/src/main/java/novamachina/exnihilosequentia/common/blockentity/barrel/mode/FluidsBarrelMode.java#L201
BucketLib buckets are not a BucketItem. To be more compatible, ExNihilo needs a change here.
The author of BucketLib told to me that this is the incompatibility

### Minecraft Version

1.18.2

### Forge Version

40.1.23

### Ex Nihilo: Sequentia Version

20220530-183458

### Additional Context

https://github.com/NovaMachina/ExNihiloSequentia/blob/1.18/src/main/java/novamachina/exnihilosequentia/common/blockentity/barrel/mode/FluidsBarrelMode.java#L201
BucketLib buckets are not a BucketItem. To be more compatible, ExNihilo needs a change here.

**Comment by TimeheroTH** [comment]
Hi i've downloaded the new version of exnihilo and installed it but continue to not work

**Comment by remplerus** [comment]
does the issue still exist?

**Comment by remplerus** [comment]
as far as i have tested it, the issue doesn't exist anymore.

**Comment by cech12** [comment]
No info needed here: https://github.com/NovaMachina-Mods/ExNihiloSequentia/pull/324 fixed it
