### ISSUE TITLE
Osmium missing exnihilosequentia:pieces tag

### ISSUE THREAD

**Issue by oly2o6** [NovaMachina/ExNihiloSequentia#325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i guess this is because its not apart of the base exnihilo, just would help alot with people automating using for example a mod with a tag filter for extracting 

### Expected Behavior

exnihilosequentia:pieces tag present on the osmium piece

### Minecraft Version

1.18.2

### Forge Version

40.1.30

### Ex Nihilo: Sequentia Version

20220620-173540

**Comment by remplerus** [comment]
do you still have this issue with latest versions of ex nihilo and mekanism addon?

**Comment by remplerus** [comment]
as i can confirm, this issue has been resolved
