### ISSUE TITLE
[Request] KubeJS Documentation and/or KubeJS custom constructor

### ISSUE THREAD

**Issue by GamingInfinite** [NovaMachina/ExNihiloSequentia#326]
### Is there an existing suggestion for this?

- [X] I have searched the existing suggestions

### Feature Description

Other mods such as the create mod include a constructor directly referencing the recipe type for KubeJS, implemented as:
event.crushing();
My proposal is for similar KubeJS integration here written something like the following:
event.sieving()
and the implemented function would include things for the input, required mesh, output and chance for said output.

at the very least if you won't consider doing the aforementioned feature, at least include documentation on how one should expect to add or remove recipes from the mod using KubeJS

How to Add:
```
event.custom({
    type: "exnihilosequentia:sieve",
    rolls: [
      {
        chance: 0.03,
        mesh: "string",
      },
    ],
    input: {
      item: "minecraft:gravel",
    },
    result: {
      item: "exnihilosequentia:gold_pieces",
    },
  });
```

I haven't figured out how to remove specific recipes by filtering the input or output yet because this mods recipes use computed json objects, which prevents me from just saying filter by item input.

### Provided Benefit

It will make it easier for potential modpack makers that are using KubeJS primarily to include code to modify the balance of their pack and manipulate the usage of this mod far easier for the pack creator.

**Comment by remplerus** [comment]
there's a PR for it. #336

**Comment by remplerus** [comment]
closed. added with newest version. wiki here: [https://jacob-williams.me/docs/configuration/kubejs](https://jacob-williams.me/docs/configuration/kubejs)
