### ISSUE TITLE
[Request] Usage of Wood Crucible for fluid transformation that can take place in Oak Barrel

### ISSUE THREAD

**Issue by GamingInfinite** [NovaMachina/ExNihiloSequentia#327]
### Is there an existing suggestion for this?

- [X] I have searched the existing suggestions

### Feature Description

This feature is already pre-existing in Ex Nihilo Adscencio (or at least it was added for Skyfactory 3), where you could create clay from water created in an oak or other wooden crucible.

### Provided Benefit

Mainly for when a Skyfactory modpack comes out, it primarily adds an avenue to getting clay buckets and shears early, allowing for the creation of cobblestone generators and bypassing the need for sieving dirt into cobblestone.  At the very least add functionality for item transformation recipes on a wood crucible, so that it can be added via CraftTweaker and/or Kubejs

**Comment by remplerus** [comment]
as far as i can tell: we won't add clay to ex nihilo. second of all, ex compressum adds that feature (what is used in skyfactory 3). Depends on @NovaMachina if he wants to add that.

**Comment by NovaMachina** [comment]
By allowing the crucible to have the same functionality as the barrel we remove the need for the barrel. I would rather not do that.
