### ISSUE TITLE
Re add Applied Energistics integration

### ISSUE THREAD

**Issue by ToMe25** [NovaMachina/ExNihiloSequentia#33]
## Is your feature request related to a problem? Please describe.
The original Ex Nihilo, Ex Nihilo Omnia, and i think also Ex Nihilo Creatio had Applied Energistics 2 integration allowing the creation of Certus Quarts and Sky Stone.

### Sieve:
|Input|Mesh|Output|Chance|
|-------|-------|---------|----------|
|Dust |Flint |Sky Stone Dust|12%|
|Dust |Iron+|Sky Stone Dust|16%|
|Dust |Flint |Certus Quartz Dust|8%|
|Dust |Iron |Certus Quartz Dust|12%|
|Dust |Diamond|Certus Quartz Dust|15%|
|Sand|Flint |Certus Quartz Crystal|13%|
|Sand|Iron+|Certus Quartz Crystal|17%|
|Sand|Diamond|Charged Certus Quartz|2%|
|Sand|Diamond|Pure Certus Quartz Seed|1%|
### Barrel:
Lava + Sky Stone Dust -> Sky Stone

## Describe alternatives you've considered
I considered just suggesting to copy either the original, or the Ex Nihilo: Creatio solution, but imo neither of them really fits here.

### New Blocks: 
Crushed Sky Stone
### Sieve:
|Input|Mesh|Output|Chance|
|-------|-------|---------|----------|
|Dust |Flint |Sky Stone Dust|10%|
|Dust |Iron  |Sky Stone Dust|20%|
|Dust |Diamond|Sky Stone Dust|30%|
|Dust |Iron+|Certus Quartz Dust|15%|
|Crushed Sky Stone|Iron|Certus Quartz Crystal|70%|
|Crushed Sky Stone|Diamond|Certus Quartz Crystal|80%|
|Crushed Sky Stone|Diamond|Charged Certus Quartz Crystal|10%|
|Crushed Sky Stone|String|Pure Certus Quartz Seed|35%|
|Crushed Sky Stone|Flint+|Pure Certus Quartz Seed|45%|
### Barrel:
Lava + Sky Stone Dust -> Sky Stone
### Hammer:
Sky Stone -> Crushed Sky Stone

### Sieve:
|Input|Output|Chance|
|-------|---------|----------|
|Dust |Sky Stone Dust|13%|
|Dust |Certus Quartz Dust|14%|
|Sand|Certus Quartz Crystal|17%|
|Sand|Charged Certus Quartz Crystal|1%|
### Barrel:
Lava + Sky Stone Dust -> Sky Stone

---
### New Blocks: 
Crushed Sky Stone
### Sieve:
|Input|Mesh|Output|Chance|
|-------|-------|---------|----------|
|Dust |Flint |Sky Stone Dust|10%|
|Dust |Iron  |Sky Stone Dust|20%|
|Dust |Diamond|Sky Stone Dust|30%|
|Crushed Sky Stone|Iron|Certus Quartz Crystal|70%|
|Crushed Sky Stone|Diamond|Certus Quartz Crystal|80%|
|Crushed Sky Stone|Diamond|Charged Certus Quartz Crystal|10%|
|Crushed Sky Stone|String/Flint|Pure Certus Quartz Seed|50%|
|Crushed Sky Stone|Iron|Pure Certus Quartz Seed|30%|
### Barrel:
Lava + Sky Stone Dust -> Sky Stone
### Hammer:
Sky Stone -> Crushed Sky Stone

**Comment by BedrockLegends** [comment]
I agree with this

**Comment by ToMe25** [comment]
You agree with what?
That ExNihiloSequentia should have AE2 integration?
That it should be more or less like the first integration that i suggested?
Or with the second integration i suggested, which i personally consider less fitting?

**Comment by BedrockLegends** [comment]
Hopefully @NovaMachina consider adding this to the mod

**Comment by NovaMachina** [comment]
@BedrockLegends I am currently working on a few other updates, and I am currently in school as well. I will get around to this soon.

**Comment by BedrockLegends** [comment]
Okay

**Comment by NovaMachina** [comment]
I have added in the crushed skystone to the mod. I have also implemented datapack support, so all of these recipes can be added that way.

**Comment by NovaMachina** [comment]
Added as part of AE2 Addon
https://www.curseforge.com/minecraft/mc-mods/ex-nihilo-sequentia-ae2-addon
