### ISSUE TITLE
[BUG] Sieves nonfunctional and ore chunks missing.

### ISSUE THREAD

**Issue by Annon9007723** [NovaMachina/ExNihiloSequentia#333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Ore chunks are missing and sieves do not function upon attempting to sieve through gravel and such. In JEI pressing U on them doesn't show recipes either. 

### Expected Behavior

Upon placing down a sieve and a mesh, you should be able to sift through dirt, gravel, sand, etc. Nothing works. Pressing U in JEI shows how they are made and how they can be upgraded, yet nothing is shown on what they can produce.

### Steps to Reproduce

1. Place down sieve.
2. Place down mesh. 
3. Attempt to sieve. Block is not consumed. 

### Minecraft Version

1.18.2

### Forge Version

40.1.60

### Ex Nihilo: Sequentia Version

20220709-191714

### Additional Context

Currently using a modpack, but nothing inside of the modpack should attempt to crash anything relating to Ex Nihilo. 
![image](https://user-images.githubusercontent.com/26782997/178174634-e85e2d80-bfdb-41b4-ab64-5e42e2f70e07.png)

**Comment by NovaMachina** [comment]
Can you please supply a log file with this behavior?

**Comment by Annon9007723** [comment]
[latest.log](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/9080381/latest.log)
Will this do? I saw something in here about "missing ore chunk"

**Comment by Annon9007723** [comment]
Slight update, I...might need to look closer at the latest.log there but when using the base mod itself along with the tinkers addon (I was planning to use both on a server) both seem to function fine in a solo instance without the other mods in the way.

**Comment by NovaMachina** [comment]
Are you using a dedicated server? There are no errors created by Ex Nihilo. The only thing that I'm seeing is that Ex Nihilo Tinkers Addon is missing on the server.

**Comment by Annon9007723** [comment]
That was the latest log from the single player one. I tried loading a single player world after testing out in the server, since the server wouldn't boot up when trying to use the tinkers addon with it. Both the single player and server wouldn't have sieves function as intended.

**Comment by NovaMachina** [comment]
So you created a new world with the Tinkers addon? Or did you copy the server world into a single player world?

**Comment by Annon9007723** [comment]
New world that had both the tinkers addon in there as well. The client for some reason works with the tinkers addon installed and the rest of the mods. I say works but I mean that it doesn't crash upon boot. 

The sieve is still broken.

**Comment by Annon9007723** [comment]
...this looks important. This was in the latest.log file from there. 
![image](https://user-images.githubusercontent.com/26782997/178176861-11d9c912-2be1-4ed5-be56-3e41a352ca9d.png)

**Comment by NovaMachina** [comment]
Can you do me a favor and start up a pack with just the following:

- Ex Nihilo: Sequentia
- Ex Nihilo: Sequetnia - Tinkers Addon
- Mantle
- Tinkers Construct

I don't see any errors on my end so I would just like to make sure that its something outside of Ex Nihilo causing issues.

**Comment by NovaMachina** [comment]
Also, what launcher are you using?

**Comment by Annon9007723** [comment]
MultiMC is what I'm using. As for doing that secondary pack, I did test that already when I mentioned I need to look over the latest.log again. As ExNihilo, and the tinkers addon, along with tinkers itself, don't cause any errors on their own. It's something outside of ex nihilo I think.

**Comment by NovaMachina** [comment]
So, does everything work as expected when isolating Ex Nihilo and Tinkers?

**Comment by Annon9007723** [comment]
When isolated, yes. What needs to be figured out now is what's conflicting with Ex Nihilo and Tinkers. if we can find what's conflicting with Ex Nihilo, that might solve the Tinker's addon for Ex Nihilo.

**Comment by NovaMachina** [comment]
You may have some luck looking through the errors here: https://mclo.gs/2hA66NP

**Comment by NovaMachina** [comment]
Try removing Mystical Agriculture. I'm seeing a lot of errors connected to it, especially around recipes.

**Comment by Annon9007723** [comment]
Lemme give it a shot.

**Comment by Annon9007723** [comment]
Huh...so, that worked. Not even sure what I might need Mystical Agriculture for now. Guess I can remove that. Thanks for the help!

**Comment by NovaMachina** [comment]
No problem! You may want to take this to Mystical Agriculture so they know about it.
