### ISSUE TITLE
[BUG] Ex Nihilo Tinkers Crash and then some

### ISSUE THREAD

**Issue by Annon9007723** [NovaMachina/ExNihiloSequentia#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently what is happening is that in the server, Ex Nihilo Tinkers addon is causing the server to crash. Client side functions fine, the server is always giving the error. 
![image](https://user-images.githubusercontent.com/26782997/178185685-123d76cd-ec46-4290-bc78-759cd3fe5a37.png)
Though another issue is that, aside from this crashing... when this mod is removed it was possible to make the server world before...it's constantly stuck at loading spawn 0% now. I'm unsure if this is relating to the mods but this is after removing mystical agriculture. Not sure if this one needs to be solved, but the main issue here is that Ex Nihilo Tinkers is causing the server to crash due to an error on its end. 

### Expected Behavior

Mod is intended to function.

### Steps to Reproduce

Install mod on server

Server crashes.

### Minecraft Version

1.18.2

### Forge Version

40.1.60

### Ex Nihilo: Sequentia Version

20220709-191714

### Additional Context

Ex Nihilo Tinkers is running 20220709-234710. Client side functions as intended. When attempting to launch a server, the server crashes.

**Comment by NovaMachina** [comment]
Please provide the log file.

**Comment by Annon9007723** [comment]
[latest (1).log](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/9080841/latest.1.log)
Took me a bit to get it. Sorry about that.

**Comment by NovaMachina** [comment]
Found the issue and pushed a fix. Should be available shortly.
