### ISSUE TITLE
[BUG] Can't Break Infested Leaves

### ISSUE THREAD

**Issue by Darmstadtium271** [NovaMachina/ExNihiloSequentia#335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I use Ex Nihilo and it's tconstruct addon. When I want to break any infested leaves, it doesn't work. I can't break it.

### Steps to Reproduce

1. Place any infested leaves.
2. Change to survival mode.
3. Use TConstruct's crook or this mod's crook to break it.

### Minecraft Version

1.18.2

### Forge Version

40.1.60

### Ex Nihilo: Sequentia Version

20220709-191714

**Comment by NovaMachina** [comment]
I do not see this functionality in my testing. Please supply a log file.

**Comment by remplerus** [comment]
we still need your log file to resolve this issue or is it resolved?

**Comment by Darmstadtium271** [comment]
It's resolved. I think is an another mod's wrong.

**Comment by Darmstadtium271** [comment]
So sorry

**Comment by remplerus** [comment]
If you find out which mod, we can look at compat issues. Until then i close the issue
