### ISSUE TITLE
Hammering cobble caused crash

### ISSUE THREAD

**Issue by Georg255** [NovaMachina/ExNihiloSequentia#337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Created nerd pole of cobble with intent to hammer it all down into gravel, got all the way to the top, whipped out hammer and crash occurred.

### Expected Behavior

I expected to hammer my cobblestone nerd pole into gravel.

### Steps to Reproduce

Create nerd pole, try to hammer cobble, get crash.

### Minecraft Version

1.18.2

### Forge Version

40.1.68

### Ex Nihilo: Sequentia Version

Current version as of 7-22-2022 for 1.18.2

### Log File

https://crashy.net/wxQ9RYmcjs08vAdMT0yL

Uploaded crash file to that site.

**Comment by wontactcivilized** [comment]
Which mod are you using to veinmine blocks?

**Comment by remplerus** [comment]
have you changed/added a hammer recipe? to help you more, we need the log file, not just the crash

**Comment by Georg255** [comment]
> Which mod are you using to veinmine blocks?

The closest is Serillium's (is that how it's spelled?) Tree Harvester.  Otherwise, no vein miner.

**Comment by Georg255** [comment]
[2022-07-21-2.log](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/9168819/2022-07-21-2.log)

I think this is it.  I reloaded that save and hammering worked normally, so I don't know what happened either.

**Comment by Georg255** [comment]
[latest.log](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/9168829/latest.log)

Just in case, here's the latest one.

**Comment by Georg255** [comment]
Also, I haven't changed any hammer recipes.  I only added a sieve recipe to get vinteum dust from sand.

**Comment by wontactcivilized** [comment]
Is this issue still occuring?

**Comment by remplerus** [comment]
Update forge to at least 40.1.73 and look, if the issue still exists. until then, i'll close this.
