### ISSUE TITLE
Lacking setWaterloged() method in exnihilosequentia.sieve() (KubeJS)

### ISSUE THREAD

**Issue by BogusAlgorithm** [NovaMachina/ExNihiloSequentia#340]
### Is there an existing suggestion for this?

- [X] I have searched the existing suggestions

### Feature Description

Ability to add custom waterloged recipes through KubeJS scripts.

### Provided Benefit

Additional compatability with KubeJS.

**Comment by remplerus** [comment]
can confirm that, actually missed that implementation

**Comment by remplerus** [comment]
this is fixed in new version by #344
