### ISSUE TITLE
[BUG] Seives not accepting gravel/sand/dust 

### ISSUE THREAD

**Issue by KroniQPlayer** [NovaMachina/ExNihiloSequentia#345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a 3x3 of sieves setup and i created this pack on august 9th, sieveing worked fine, but since update to latest version ExNihiloSequentia-1.18.2-20220818-010806 it wont even accept any resources to even try and sieve. upon investigating further in my logs, the crafttweaker log is saying ( [ERROR]: Duplicate ZenCode Name 'mods.exnihilosequentia.ZenSieveRecipe' in classes 'novamachina.exnihilosequentia.common.compat.crafttweaker.builder.ZenSeiveRecipe' and 'net.blay09.mods.excompressum.compat.crafttweaker.builder.ZenBaseRecipe' ). I am assuming this is disabling the drops from sieving.

### Expected Behavior

right click gravel, sand, dust on sieve with mesh, get drops in return.

### Steps to Reproduce

1. create new world.
2.  grab any sieve and any mesh and a stack of any sievable block.
3.  right click sieve with selected block
4.  nothing happens

### Minecraft Version

1.18.2

### Forge Version

40.1.73

### Ex Nihilo: Sequentia Version

20220818-010806

### Log File

[crafttweaker.log](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/9385441/crafttweaker.log)

**Comment by NovaMachina** [comment]
Based on the CraftTweaker log I'm going to suggest that this is an issue with Ex Compressum conflicting with Ex Nihilo recipe types.

**Comment by KroniQPlayer** [comment]
that is what I figured, but how do I fix it or do I have to wait for one of the mods to update

**Comment by NovaMachina** [comment]
Watching: https://github.com/ModdingForBlockheads/ExCompressum/issues/357

**Comment by BlayTheNinth** [comment]
Fixed in Ex Compressum
