### ISSUE TITLE
[BUG] 1.18.2 mod downloaded from Curseforge doesn't load

### ISSUE THREAD

**Issue by Undercoverer** [NovaMachina/ExNihiloSequentia#346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've tried a few different versions, but none of them actually load in to the game. They aren't present in the mods menu and there doesn't seem to be anything wrong in the logs to give any idea of what's going on

### Expected Behavior

The mod to load

### Minecraft Version

1.18.2

### Forge Version

40.1.73

### Ex Nihilo: Sequentia Version

20220818-010806

### Log File

https://0x0.st/o98B.txt

**Comment by NovaMachina** [comment]
Unfortunately there is not enough information to be able to replicate this issue. It sounds like it may be an issue with PolyMC. I would suggest going to them.
