### ISSUE TITLE
[BUG] <bucket lib - wooden or ceramic milk bucket doesn't fill up barrel>

### ISSUE THREAD

**Issue by TimeheroTH** [NovaMachina/ExNihiloSequentia#347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you right click with a milk wooden or ceramic bucket the empy barrel doesn't fill up;
while doing this if  i have a milk wooden or ceramic bucket and the barrel is full of another liquid, the bucket take this liquid and empty the barrel and when i right click the empty barrel the second fluid go into the barrel while milk is always in the bucket.

### Expected Behavior

If you right click with a milk wooden or ceramic bucket the empy barrel doesn't fill up;
while doing this if  i have a milk wooden or ceramic bucket and the barrel is full of another liquid, the bucket take this liquid and empty the barrel and when i right click the empty barrel the second fluid go into the barrel while milk is always in the bucket.

### Steps to Reproduce

If you right click with a milk wooden or ceramic bucket the empy barrel doesn't fill up;
while doing this if  i have a milk wooden or ceramic bucket and the barrel is full of another liquid, the bucket take this liquid and empty the barrel and when i right click the empty barrel the second fluid go into the barrel while milk is always in the bucket.

### Minecraft Version

1.18.2

### Forge Version

40.1.68

### Ex Nihilo: Sequentia Version

20220818.010806

### Log File

No log file

**Comment by cech12** [comment]
I fixed the strange behaviour that wooden/ceramic milk buckets could be filled with other fluids in BucketLib 1.18.2-0.5.3.8 and 1.19-1.0.3.1.
As far as I can see, milk cannot be placed in barrels, so this is not an issue.^^

**Comment by remplerus** [comment]
yep, milk can't be placed in barrels (yet?) I close this and create a discussion on discussion thread.

**Comment by TimeheroTH** [comment]
Milk could be placed in barrels with a normal minecraft bucket but with ceramic/wooden buckets don't work yet @cech12 @remplerus

**Comment by remplerus** [comment]
just to be clear: milk does only render, but is no fluid! as far as i have tested it, you can insert any fluid bucket into barrel besides milk. (as it is no fluid)

**Comment by remplerus** [comment]
i reopen the issue, as it turns out, that it IS possible to place any fluid into the barrel besides milk, when it's inserted by bucket lib buckets...

**Comment by cech12** [comment]
The information that another mod enables the Forge milk fluid was missing initially. It will be fixed on BucketLib side. :)

**Comment by cech12** [comment]
I fixed the fluid handler of the BucketLib milk buckets when the milk fluid of Forge is enabled. The versions 1.18.2-0.5.3.9 and 1.19-1.0.3.2 of BucketLib contain the changes. Thanks for your report and your help in finding the source of the issue. :)
