### ISSUE TITLE
Wrong output sieve registry

### ISSUE THREAD

**Issue by G-Stav** [NovaMachina/ExNihiloSequentia#35]
**Describe the bug**
Sieve registry gives wrong output with red sand.

**To Reproduce**
  {
    "input": "minecraft:sand",
    "result": "notreepunching:sandstone_loose_rock",
    "rarity": 0.5,
    "mesh": "STRING",
    "isWaterlogged": false
  },
  {
    "input": "minecraft:red_sand",
    "result": "notreepunching:red_sandstone_loose_rock",
    "rarity": 0.5,
    "mesh": "STRING",
    "isWaterlogged": false
  },

**Expected behavior**
Expect sand to output sandstone rocks and red sand to output red sandstone rocks

**Screenshots**
![2020-10-03_11 42 38](https://user-images.githubusercontent.com/18726116/94988343-c256b000-056c-11eb-9387-a702980af815.png)

**Version**
Minecraft Version: 1.16.3
Forge Version: 34.1.1
Ex Nihilo: Sequentia Version: 1.16.1.2.1.2

**Comment by G-Stav** [comment]
I think this may have to do with tags. Since sand and redsand both have the tag minecraft:sand. Tried using the tag forge:sand/colorless in place of minecraft:sand but now it instead outputs nothing, and the red sand recipe does work.

**Comment by NovaMachina** [comment]
Can you include a log report? This will tell what the issue is, but I believe you are right.

**Comment by G-Stav** [comment]
Like a debug crash log? https://pastebin.com/C5ECw94g here you go in that case.
I'm sorry if you mean something else. Not very knowledgeable about these things.

**Comment by NovaMachina** [comment]
You're all good. You're on the right track. Minecraft keeps a log of the game even when it is working correctly. After running a game that is working, go to the Minecraft folder and there is a log folder inside of it. There should be one called "latest". That would be the one I would like to see.

**Comment by G-Stav** [comment]
https://pastebin.com/fLKPJGMx Here you go! I think. Using the twitch launcher but this is from latest.log in the modpack folder in the instances folder.

**Comment by NovaMachina** [comment]
Perfect! I'm not seeing a warning about bad JSON files, do you have the config option "useJson" set to true?

**Comment by G-Stav** [comment]
"#Registry Configs
[registry]
	#Should use JSON registries. Will generate JSON files if they do not exist. (Default: false)
	useJson = true"

Yep. Although on a side note, I just realized that silver pieces and chunks aren't showing up in JEI despite Immersive Engineering ores are enabled. (It does appear in uses however, ie furnace smelting it into ingots etc)

"	#Should Immersive Engineering ores be enabled? (Default: false)
	enableImmersiveEngineering = true"

**Comment by NovaMachina** [comment]
OK, I will have to do some digging into this one to figure out what's going on.

**Comment by G-Stav** [comment]
If there's anything else I can do to help please let me know! I was planing on doing a whole lot more work on the pack before I uploaded an alpha to curse, but if it would help I'd gladly upload it now as is.

**Comment by NovaMachina** [comment]
The next update should fix this problem entirely.
