### ISSUE TITLE
[Request] Add "[Sieve] Allow Macro/AutoClicker" config option

### ISSUE THREAD

**Issue by gurmiguel** [NovaMachina/ExNihiloSequentia#353]
### Is there an existing suggestion for this?

- [X] I have searched the existing suggestions

### Feature Description

Can a flag be added to config to allow Macros/Auto Clicker to sieve, instead of hard blocking it, maybe to a maximum number of clicks.

Affected code: `src/main/java/novamachina/exnihilosequentia/common/blockentity/SieveEntity.java:69`

### Provided Benefit

It is interesting to have that in a more casual game style, where you don't want to lose too much time sieving (even more on later game states), giving the player the option to choose whether to play in "easy mode" (or "faster").

**Comment by Blackbird-Modder** [comment]
This feature would be absolutely amazing to have. I will look into the folders and see if I find anything. If I do i'll reply with a solution.

**Comment by NovaMachina** [comment]
This more or less breaks the mod. Unless there is an overwhelming request for this, we won't be adding this.
