### ISSUE TITLE
[VISUAL] <title>1.18.2-20220818-010806 No Dust texture

### ISSUE THREAD

**Issue by OceanRift** [NovaMachina/ExNihiloSequentia#354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I just installed the mod, and I dont have a dust texture in it. 

### Minecraft Version

1.18.2

### Forge Version

40.1.16

### Ex Nihilo: Sequentia Version

1.18.2-20220818-010806

### Log File

[latest.log](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/9500637/latest.log)

**Comment by OceanRift** [comment]
![image](https://user-images.githubusercontent.com/83827782/188735785-1b0a7dba-6094-45bc-87e2-acff0be61b70.png)

**Comment by remplerus** [comment]
This isn't an issue from ex nihilo. It's from ResourcesForDays.
