### ISSUE TITLE
Thermal Addon: Blitz, Blizz, and Basalz powders from dust in seive

### ISSUE THREAD

**Issue by Angular-Angel** [NovaMachina/ExNihiloSequentia#355]
### Is there an existing suggestion for this?

- [X] I have searched the existing suggestions

### Feature Description

First off, the thermal addon mod page links to it's github repo for issues - but that repo is archived, so no new issues may be submitted. Hence, I am submitting this issue here.

As for the request at hand, I think the sieve should drop these powders in addition to blaze powder from dust, when the thermal addon is installed.

### Provided Benefit

It will make the mod more consistent, and more compatible with the Thermal mods.

**Comment by NovaMachina** [comment]
These items can be added to the sieve drops with data packs, CraftTweaker, or KubeJS. Since the addon provides the mobs to make the drops, this is something that pack developers can add if they so choose.
