### ISSUE TITLE
[Request] Allow third party pack launchers

### ISSUE THREAD

**Issue by HalJordan** [NovaMachina/ExNihiloSequentia#357]
### Is there an existing suggestion for this?

- [X] I have searched the existing suggestions

### Feature Description

What reason could you possibly have for blocking this? Certainly it's not the default and you forgot?

### Provided Benefit

Less headache when trying to play popular packs

**Comment by AlfredoPorfaverta** [comment]
Please allow this. Im trying to make a modded server with this mod but I can't since it doesn't allow third party things
