### ISSUE TITLE
[BUG] Barrel making sea water instead of witch water

### ISSUE THREAD

**Issue by pnieuwkamp** [NovaMachina/ExNihiloSequentia#358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm playing All The Mods 7 To The Sky. I made a 9x9 patch of mycelium, and placed a bunch of barrels on it. It started to rain, the barrels filled up, and most of them transformed to witch water. A few however, transformed to sea water.

Clicking the witch water with sand gave me soul sand, the barrels start to fill back up, and now more barrels transform to sea water. There's definitely NOT sand underneath the barrel...

After 5 stacks of sand 22 out of 54 barrels contain sea water.
![2022-09-23_11 19 06](https://user-images.githubusercontent.com/13655588/192227545-48047607-a657-4dba-9404-3781f168e604.png)

I've also tried using @Pipez fluid pipes and an @CookingForBlockheads sink, and the same happens. The first iteration all 54 barrels transformed into witch water, the second iteration (after clicking the barrels with sand to get soul sand) 5 out of 54 transformed into soul sand

### Expected Behavior

I would expect all barrels to transform to witch water, and none of them to transform to sea water

### Steps to Reproduce

Place mycellium blocks
Place barrels on top
Fill barrel with water
Wait until it transforms to witch water
Doubleclick the barrels with sand in your hand
Fill barrels with water
See that some barrels transform into sea water

### Minecraft Version

1.18.2

### Forge Version

40.1.79

### Ex Nihilo: Sequentia Version

20220818-010806

### Additional Context

ATM 7 To The Sky 1.0.8

### Log File

[logs.zip](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/9644449/logs.zip)

**Comment by NovaMachina** [comment]
Please take this to the ATM team first.

**Comment by pnieuwkamp** [comment]
I could, but I doubt that will help as I tested some more and I can recreate that with just vanilla MC, Forge and ExNS (using MultiMC). It happens when I rightclick a barrel with sand while the barrel is only partially filled on mycelium or with any amount of water in it (including full) when not placed on mycelium (or probably sand; haven't tried that yet).

New steps to reproduce:
Pace mycelium block (doesn't matter where, can be in mid-air)
Place barrel on top
Fill the barrel somewhere between 1mB and 1000 mB with water (I didn't test all levels; mainly used rain and water bottles).
Right-click the barrel with sand
Wait 10 seconds
Barrel is full (1000 mB) with sea water

Some further testing reveals clicking a partially filled barrel with mycelium yields witch water... Looking at ExNihiloSequentia-1.18\src\main\java\novamachina\exnihilosequentia\common\blockentity\barrel\mode\FluidsBarrelMode.java line 158 this seems intentional? (btw, I's sorry if there's a better way to guide you there, I don't know enough about Github to come up with a better way). Even then, I suppose it should only work on a full barrel?

It does not appear to affect automation, probably because a pipe trying to put something into an inventory is nothing like "catalyst = player.getItemInHand(handIn).getItem();", so it's a bug/feature I can live with :)

**Comment by remplerus** [comment]
this is true, we never check in this method if the amount is full, so you can make fluids with less fuild amount than it should. so this is duping on next level D:
will make PR with some minor changes later
