### ISSUE TITLE
[Request] Add compability tags please.

### ISSUE THREAD

**Issue by adamkad1** [NovaMachina/ExNihiloSequentia#359]
### Is there an existing suggestion for this?

- [X] I have searched the existing suggestions

### Feature Description

I know there are compability mods that havent been updated to 1.19 yet but with proper tags they probably wouldnt be neccesary.

### Provided Benefit

Proper tags would make extra mods unnecessary. (though to be honest, the ores that are useless without other mods should just be shifted away from the main mod.)

### Additional Context

![javaw_YGtEllK39B](https://user-images.githubusercontent.com/22750535/192915068-2de885f9-fa74-4211-97ad-cde09c19c4b7.jpg)
![javaw_gC5HeLzXcO](https://user-images.githubusercontent.com/22750535/192915081-ba8cc917-3bac-4a12-90b3-2d8f1fcdb5e8.jpg)
The tags of a working ingot and exnihilo ingot. 
A forge:ingots/(materialname) tag usually makes ingots useable with most recipes, without requiring a secondary compability mod
Example:
![javaw_ZJp2lWPcnC](https://user-images.githubusercontent.com/22750535/192915358-0ffcd905-b140-409f-827a-6425edf8f055.jpg)

**Comment by remplerus** [comment]
can confirm, this line has nothing to create those tags. in 1.18 they exist: https://github.com/NovaMachina-Mods/ExNihiloSequentia/blob/017fe5bff9e1960966e066a9fa6e8a71e3df823d/src/datagen/main/java/novamachina/exnihilosequentia/api/datagen/AbstractItemTagGenerator.java#L52

**Comment by adamkad1** [comment]
Also I dunno if I should make a new post but it seems minor enough. Its aluminium, not aluminum.

**Comment by Blackout03** [comment]
> Also I dunno if I should make a new post but it seems minor enough. Its aluminium, not aluminum.

In America it is aluminum

**Comment by adamkad1** [comment]
> > Also I dunno if I should make a new post but it seems minor enough. Its aluminium, not aluminum.
> 
> In America it is aluminum

TIL

**Comment by AndreAugustoDev** [comment]
According to this https://github.com/NovaMachina-Mods/ExNihiloSequentia/blob/9f1a8826d3a864ba237dbd84139d148b863aef9a/src/main/java/novamachina/exnihilosequentia/api/tag/ExNihiloTags.java#L58-L60 the raw ores are incorrectly tagged, pointing to tag `forge:ores` instead of `forge:raw_materials`
Nuggets are also untagged

I made a KubeJS script to fix this until the fix is ​​done

I could have done it, but I can't compile the code to test it, it always gives CraftTweaker error on game startup

<details>
<summary>KubeJS script</summary>

```js
ServerEvents.tags('item', event => {
    const raw_ores = event.get('forge:ores').getObjectIds();
    const raw_to_fix = Ingredient.of(/.*exnihilosequentia:raw_.*/);

    raw_ores.forEach(ore => {
        const ore_str = ore.toString();
        if (raw_to_fix.test(ore)) {

            event.removeAllTagsFrom(ore_str);

            event.add('forge:raw_materials', ore_str);

            const material = ore_str.substring(ore_str.lastIndexOf("_") + 1);

            event.add('forge:raw_materials/' + material, ore_str);

            const nugget = `exnihilosequentia:${material}_nugget`

            event.add('forge:nuggets', nugget);

            event.add('forge:nuggets/' + material, nugget);
        }
    })
})
```

</details>

This removes the tag `forge:ores` and put `forge:raw_materials`

**Comment by kurotom** [comment]
Hello, if changes `return forgeLoc("ores/" + ore);` to `return forgeLoc("raw_materials/" + ore);`, will it worked?.

**Comment by NovaMachina** [comment]
Did not know that forge added a raw ores tag. I will update.

**Comment by NovaMachina** [comment]
Fixed in latest version
