### ISSUE TITLE
[BUG] Missing recipe unlocks

### ISSUE THREAD

**Issue by PliskintheSaltyFork** [NovaMachina/ExNihiloSequentia#360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Can't craft meshes.  Mod is missing recipe unlocks for some of it's items/blocks.

### Expected Behavior

To be able to craft the meshes and other items/blocks from the mod.

### Steps to Reproduce

1. Collect ingredients
2. Open crafting grid or table
3. Add ingredients to grid or use vanilla's recipe book to craft item/block
4. Item is unable to be crafted do to player missing recipe unlock (missing from the recipe book), but recipe still shows up in JEI.
![2022-10-09_16 57 05](https://user-images.githubusercontent.com/6131437/194779250-c2aa19ac-1c3a-422d-bc4d-d95f391d17e7.png)
![2022-10-09_16 57 20](https://user-images.githubusercontent.com/6131437/194779270-dd645510-ef36-46d8-a6bf-6281f2672e54.png)

### Minecraft Version

1.18.2

### Forge Version

40.1.80

### Ex Nihilo: Sequentia Version

20220926-000123

### Log File

[2022-10-09-1.log.gz](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/9742525/2022-10-09-1.log.gz)

**Comment by remplerus** [comment]
This is no Bug as this wasn't intended to Do first. Ans second: duplication of #356
