### ISSUE TITLE
[BUG] Flux Sieve not recognizing output inventory

### ISSUE THREAD

**Issue by WhyTheF8CKis-ICMan-NotAvailable** [NovaMachina/ExNihiloSequentia#363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am running the latest version of ATM7 To The Sky (Oct 23).

The Flux Sieve is not working properly.  It has power going to it, and no matter what side I place chests or barrels on (including on top and on the bottom), it still says no output inventory.  It happens when I place the chest/barrel first, or when I place the Flux Sieve first.

### Expected Behavior

It should recognize when an inventory has been placed beside it.

### Steps to Reproduce

Place Sieve
Add RF power (using @Pipez)
Place chest on any side.
Open Flux Sieve GUI
Mouse over the "X" in the middle of the screen
It says "Missing Inventory on Output Side"
Try placing the chest on any side of the device, same message.
Try clicking on the X
No change.

### Minecraft Version

1.18.2

### Forge Version

40.1.80

### Ex Nihilo: Sequentia Version

20220926-000123

### Additional Context

N/A

### Log File

N/A

**Comment by NovaMachina** [comment]
The Flux Sieve is not part of Ex Nihilo: Sequentia. It is part of Ex Machinist owned by the ATM team.
