### ISSUE TITLE
mesh custom

### ISSUE THREAD

**Issue by RobinErza** [NovaMachina/ExNihiloSequentia#369]
### Is there an existing suggestion for this?

- [X] I have searched the existing suggestions

### Feature Description

add config for add custom mesh for modspack? i can give good idea i think

### Provided Benefit

created new mesh custom for add to sieve after netherite any color or texture

**Comment by NovaMachina** [comment]
Dynamic item generation via a configuration file is not supported by Forge. Items and blocks have to be statically registered and frozen before configuration files are loaded.
