### ISSUE TITLE
Hammer "silktouches" blocks

### ISSUE THREAD

**Issue by G-Stav** [NovaMachina/ExNihiloSequentia#37]
**Describe the bug**
Using the hammer on a block that isn't in the HammerRegistry gives a silktouched version. Such as coal ore doesn't drop coal, grass blacks don't drop coal.

**To Reproduce**
Pretty much says it up top.

**Expected behavior**
Expect it to act like an open hand or pickaxe without silk touch.

**Screenshots**

**Version**
Minecraft Version: 1.16.3
Forge Version: 34.1.23
Ex Nihilo: Sequentia Version: 1.16-1.2.1.2.jar

**Additional context**
I have a hunch thinking it may have something to do with the loot table only accepting blocks and not items. Not sure though because that doesn't explain grass not droping dirt. Either way it would be a nice QoL addition to be able to get items from hammering blocks like previous versions of Ex Nihilo.

**Comment by NovaMachina** [comment]
Fixed in next update.
