### ISSUE TITLE
[BUG] <1.18.2 Fluid Transformation (for Clay, Netherrack) is not working>

### ISSUE THREAD

**Issue by xFirefalconx** [NovaMachina/ExNihiloSequentia#371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Stone barrel is not producing clay.

### Expected Behavior

Right-click on water-filled stone barrel with a dust block should consume dust and produce clay, as the recipe says.

### Steps to Reproduce

1. Place "Stone Barrel"
2. Fill with a water bucket
3. Hold dust in your hand and right click. Nothing happens.

### Minecraft Version

1.18.2

### Forge Version

40.1.74

### Ex Nihilo: Sequentia Version

20221105-143505

### Log File

[latest.log](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/9948079/latest.log)

- might not be working, last change was recorded... 1h ago but I'm in-game right now.

**Comment by xFirefalconx** [comment]
Update, same behaviour for trying to get Netherrack by right-clicking redstone on a Lava-filled barrel. 

If this is not intended, it blocks usage of this mod greatly.

**Comment by remplerus** [comment]
does this only appear on stone barrel? i can look into this at the weekend and make an important PR

**Comment by xFirefalconx** [comment]
Tested it on water filled birch barrel, same event with function not happening. 
If you need my mod list to sort out any compatibility issues, please let me know.

**Comment by Rensik** [comment]
Can confirm All Fluid Transformation fails with 1.19.2-4.0.0.46, not even Witch Water or Sea Water.

**Comment by remplerus** [comment]
i could confirm this too, not just fluid transformation, even fluid item and fluid block recipes are affected. made PRs for both versions, hope they'll be merged fast.

**Comment by NovaMachina** [comment]
PR's have been merged. Should be fixed soon.
