### ISSUE TITLE
[Request] <project distribution>

### ISSUE THREAD

**Issue by ShreemantYaPro** [NovaMachina/ExNihiloSequentia#378]
### Is there an existing suggestion for this?

- [X] I have searched the existing suggestions

### Feature Description

Can u allow project distribution of ex nihilio sequentia on server hosting websites like aternos please i want to play with my friends and all as this is a really good resource automation mod

![ex nihilio](https://user-images.githubusercontent.com/113830386/201570086-d7e2f90d-ed81-4ad6-93fe-13758d0ab9fd.png)

### Provided Benefit

You can get more millions of downloads as aternos is a very popular free server hosting websites

### Additional Context

please allow

**Comment by remplerus** [comment]
closed. discussed on #349
