### ISSUE TITLE
[BUG] [1.19] Unable to add blocks/items to full fluid barrels

### ISSUE THREAD

**Issue by Emofsevencrows** [NovaMachina/ExNihiloSequentia#379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Items such as dust and redstone are not able to be added to full barrels of water/lava consistent with 'Fluid Item Transformation' type recipes.

The recipes appear when using jei.

The 'placing' hand animation plays when attempting to insert the item but no other effects occur and the item transformation does not take place.

https://user-images.githubusercontent.com/118207126/201724668-f6085551-dd26-4701-a405-3047a657170e.mp4

(footage taken from a privately hosted multiplayer server, however this behavior is consistent with a single player world running the same versions)

### Expected Behavior

I have played previous versions of Ex Nihilo so was expecting to be able to simply place the item inside the filled barrel to complete the crafting process

### Steps to Reproduce

Barrel filled with fluid (water used in example above)
Attempt to place an item with right-click into the barrel consistent with a fluid item transformation recipe (dust used in example above)

### Minecraft Version

1.19.X

### Forge Version

43.1.30

### Ex Nihilo: Sequentia Version

1.19.2-4.0.0.46-beta

### Log File

Here is the log file, by the looks of it ex nihilo is registering when the interaction is attempted (entry: [14Nov2022 17:35:48.977])

But there doesn't seem to be a section for loading the barrel recipes when [novamachina.exnihilosequentia.common.init.ExNihiloInitialization/] is running but that may be a result of the way the mod is coded idk.
[debug.log](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/10005589/debug.log)

**Comment by NovaMachina** [comment]
Please update to the latest version. This is a bug that was introduced in 4.0.0.46.
