### ISSUE TITLE
SieveRegistry issue

### ISSUE THREAD

**Issue by BedrockLegends** [NovaMachina/ExNihiloSequentia#38]
**Describe the bug**
When I added two things to the Sieve Registry, it showed up under a different mesh then what I had set it to. Example in image below

![2020-10-18_18 08 14](https://user-images.githubusercontent.com/48525410/96388229-2d0f0a80-116d-11eb-92ff-415ccd3adb42.png)
  {
    "input": "minecraft:gravel",
    "result": "ars_nouveau:mana_gem",
    "rarity": 0.02,
    "mesh": "IRON",
    "isWaterlogged": false
  },
  {
    "input": "minecraft:gravel",
    "result": "forbidden_arcanus:arcane_crystal",
    "rarity": 0.02,
    "mesh": "IRON",
    "isWaterlogged": false
  },

**To Reproduce**
1. Place block '...'
2. Right click on '...'
3. Do thing '...'

**Expected behavior**

**Screenshots**

**Version**
Minecraft Version: 1.15.2
Forge Version: 31.1.61
Ex Nihilo: Sequentia Version: 2020-08-09-11-59-99

**Additional context**
Stack traces and log files are nice to have. Submit all files through [Gist](https://gist.github.com/) or [Pastebin](https://pastebin.com/) and place the links here.

**Comment by NovaMachina** [comment]
That's happening because you have the config flattenSieveRecipes set to true. JEI will show all the meshes that it can be produced from. Can you confirm that it doesn't show on flint or sting meshes? If this is the case, and it is only showing up on iron and diamond meshes, then this is the intended behavior.

**Comment by BedrockLegends** [comment]
Fixed disabled  flattenSieveRecipes
