### ISSUE TITLE
[BUG] Registry object not present: exnihilosequentia:acacia_sieve

### ISSUE THREAD

**Issue by EmirLogas** [NovaMachina/ExNihiloSequentia#382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/76751818/204087187-b52a5f16-cb69-4a58-8fb4-f46332f98a0a.png)

### Minecraft Version

1.18.2

### Forge Version

40.1.85

### Ex Nihilo: Sequentia Version

20221113-044349

### Log File

Latest : https://mclo.gs/blwtU9r
Crash : https://mclo.gs/wG6xLvA

**Comment by remplerus** [comment]
not enough information. add latest.log and crash log please

**Comment by remplerus** [comment]
and you're not using latest version: 

Mod Version: 1.18.2-20221109-230920
Ex Nihilo: Sequentia Version
20221113-044349

**Comment by EmirLogas** [comment]
I edit logs and version.

**Comment by remplerus** [comment]
does this also happen without optifine installed?

**Comment by EmirLogas** [comment]
yes same issue without optifne.

**Comment by remplerus** [comment]
have you tried to redownload the mod?

**Comment by EmirLogas** [comment]
Yep! Many times.

**Comment by remplerus** [comment]
ok last but not least: have you tried it without any other mods installed?

**Comment by EmirLogas** [comment]
Yes, the same errors occurred when I tried to open it alone.

**Comment by remplerus** [comment]
can't confirm the problem. try to reinstall your instance 
![image](https://user-images.githubusercontent.com/44590574/204089454-4f2715be-3e3b-44bc-9b4a-54a5cdcb7ace.png)
