### ISSUE TITLE
mycilium get destroyed by barrel.

### ISSUE THREAD

**Issue by sasaavirus** [NovaMachina/ExNihiloSequentia#386]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

when placing a barrel on top of mycilium to make witchwater, the mycilium will become dirt because the barrel is a "full block"

### Expected Behavior

the mycilium should not transfor into dirt

### Steps to Reproduce

place a barrel on top off mycilium

### Minecraft Version

1.19.X

### Forge Version

43.2.0

### Ex Nihilo: Sequentia Version

4.0.0.49-beta

### Additional Context

I guess its because the barrel is a full block.

### Log File

dont have one, does'nt crash the game

**Comment by remplerus** [comment]
same issue as #381

**Comment by sasaavirus** [comment]
yes correct, sorry must have been keen on finding witchwater or mysilium in the title
