### ISSUE TITLE
[BUG] Ingots not working with other mods

### ISSUE THREAD

**Issue by dscrafted** [NovaMachina/ExNihiloSequentia#388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you would smelt the mod specific ore chunks it gives you an ingot that can't be used with any other recipes 

### Expected Behavior

When you smelt your sifted recourses it should give an ingot that can be used in other mods and not only be convertible into nuggets and back

### Steps to Reproduce

sift
craft ore pieces like nickel into chunks
smelt these chunks
be unable to use these ingots because they don't have any forge tag

### Minecraft Version

1.19.X

### Forge Version

43.2.3

### Ex Nihilo: Sequentia Version

4.0.0.49

### Log File

[2022-12-30-2.log.gz](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/10327719/2022-12-30-2.log.gz)

**Comment by NovaMachina** [comment]
This is indeed a bug. Somehow the tag generation got removed for ingots. I will fix this when I get back from traveling.

**Comment by NovaMachina** [comment]
Fixed in latest version
