### ISSUE TITLE
I am missing a possibilty to get some items from sieving

### ISSUE THREAD

**Issue by sasaavirus** [NovaMachina/ExNihiloSequentia#389]
### Is there an existing suggestion for this?

- [X] I have searched the existing suggestions

### Feature Description

I run a a skyblock server for a few friends and there is no possibilty to get:
any other sapling then the ones you start with
sweet berrys
cactus
bamboo
sugarcane
kelp

and I would love to see patato's and carrots added too, with a option to disable them maybe.
because those two can be obtained by a mob spawner.
And people may like the difficult route to get them.

I tried making a custom datapack to add these for sieving but was not succesful.
is this disabled, or not possible?

I resolved the issue for now by creating a datapack to add the items trough the "splashing" feature in .create

### Provided Benefit

The benefit would be more vanilla items that are usefull in the "vanilla game" and other mods (kelp in create for example)
and other types of wood to have more options in building blocks.

### Additional Context

mods we use in modpack

AdvancedPeripherals-0.7.22b.jar
appliedenergistics2-forge-12.8.6.jar
AutoDropper-1.19-10.0.1.jar
cc-tweaked-1.19.2-1.101.1.jar
CodeChickenLib-1.19.2-4.3.0.470-universal.jar
cofh_core-1.19.2-10.0.0.29.jar
constructionwand-1.19.1-2.8.jar
cookedapplea-1.2.0-1.19-1.19.2.jar
create-1.19.2-0.5.0.g.jar
createaddition-1.19.2-20221220a.jar
createdeco-1.2.12-1.19.2.jar
curios-forge-1.19.2-5.1.1.0.jar
elevatorid-1.19.2-1.8.9.jar
EnderStorage-1.19.2-2.10.1.181-universal.jar
exmachinis-1.19.2-2.0.1.jar
ExNihiloSequentia-1.19.2-4.0.0.49-beta.jar
ExNihiloAE-1.19.2-4.0.0.48-beta.jar
FastLeafDecay-30.jar
inventorysorter-1.19.2-21.0.4.jar
jei-1.19.2-forge-11.4.0.286.jar
JustEnoughResources-1.18.2-0.14.1.171.jar
LibX-1.19.2-4.2.5.jar
liquidburner-1.19.2-0.2.jar
littlecontraptions-forge-1.19.2.0.jar
littlelogistics-mc1.19.2-v1.3.1.jar
OreExcavation-1.11.166.jar
SkyblockBuilder-1.19.2-4.2.6.jar
TwerkItMeal-2.2.2.jar

**Comment by NovaMachina** [comment]
We can definitely add better vanilla support. In the mean time, please check the wiki for info on how to add recipes via data packs, crafttweaker or kubejs: wiki.jacob-williams.me

**Comment by sasaavirus** [comment]
> We can definitely add better vanilla support. In the mean time, please check the wiki for info on how to add recipes via data packs, crafttweaker or kubejs: wiki.jacob-williams.me

I have but must have made a typo or something I guess.

**Comment by suspicious-pineapple** [comment]
for some reason it still seems to be impossible to get kelp from waterlogged sifting, even though the recipe apparently exists
