### ISSUE TITLE
[BUG] <Ex Nihilo Heat Recipe Bug>

### ISSUE THREAD

**Issue by FooterManDev** [NovaMachina/ExNihiloSequentia#393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to create a Heat recipe with KubeJS, I get an unknown error. 
`server_scripts:general/sequentia/Ex Nihilo/heat.js:2: Failed to create recipe for type 'exnihilosequentia:heat' with args [{"type":"exnihilosequentia:heat","block":"minecraft:blast_furnace","amount":10.0,"state":{"lit":"true"}}]: java.lang.IncompatibleClassChangeError: Method 'net.minecraft.world.item.ItemStack dev.latvian.mods.kubejs.item.ItemStackJS.of(java.lang.Object)' must be InterfaceMethodref constant`

When adding a recipe through a Datapack json however, works just fine.

![2023-02-11_10 37 39](https://user-images.githubusercontent.com/71946346/218267635-2bce1b08-9802-4ebb-95f7-e5e4fd7d65ab.png)
This ^^ is an image of an instance with just Sequentia and Kube, along with the recipe loaded. There are no errors or warnings, but it also doesn't generate fluid.
The instance where it doesn't work completely and gives the error is a pack with 176 mods loaded.
The folks on Lat's discord were unable to help me fix it, and directed me here. 

Here are the scripts used:
`{
	"type": "exnihilosequentia:heat",
	"block": "minecraft:blast_furnace",
	"amount": 10,
	"state": {
		"lit": "true"
	}
}`
Working ^^
`ServerEvents.recipes(event =>{
event.recipes.exnihilosequentia.heat("minecraft:blast_furnace", 10, {lit:true})
})`
Not Working ^^

### Expected Behavior

Heat Recipe to be created and working.

### Steps to Reproduce

Without error:
Create a new Modpack instance with just Kube, Sequentia, and their addons.
Add the Kube script provided.
Load a new world and attempt to use a Crucible.

Unfortunately I'm not sure how to do it with the amount of mods. If you want a mod-list I'd be happy to provide.

### Minecraft Version

1.19.X

### Forge Version

43.2.4

### Ex Nihilo: Sequentia Version

4.1.0.55

### Additional Context

Using the AE2 and Mekanism addons.

### Log File

[server.txt](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/10714011/server.txt)
KubeJS Server Log ^
[latest.log](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/10714013/latest.log)
Latest Log ^

**Comment by NovaMachina** [comment]
Can you post the full KubeJS Script?

**Comment by FooterManDev** [comment]
That is the full Kube script.

**Comment by remplerus** [comment]
couldn't reproduce the error using forge 43.2.0 and kubejs build.142

**Comment by FooterManDev** [comment]
Well, I still get the issue on my end. I can give y'all my instance if you'd like, I'm not sure what would be causing something like this, so I don't know what else to do.

**Comment by remplerus** [comment]
would be neat, so i can figure out more

**Comment by FooterManDev** [comment]
https://github.com/TheGangModpacks/Fun-in-the-Sky/releases/tag/Alpha-0.0.1
