### ISSUE TITLE
[BUG] Addon Hammers not working in ATM7(TTS)

### ISSUE THREAD

**Issue by Speecker** [NovaMachina/ExNihiloSequentia#396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hammers from ExNaturea (part of ATM7 by default) and the Tinkers Addon (NOT in ATM7 by default) do not work and (shows the red x in theoeprobe /) acts like an incorrect tool to be used on hammerable blocks. Hammers from ExNihilo itslef work fine.
When blocks are mined they just get voided.

### Expected Behavior

ExNaturea and TiCon (ExNihilo-)Hammers (NOT Sledgehammers) should work as tool for hammering down blocks like cobblestone -> gravel -> sand -> etc. And give the repective outputs from doing so.
(Note: Isolating TinkersConstruct and ExNihilo with all their Addons for each also work fine so some other mod or config may cause this issue. Also there are "exnihilosequentia:hammer" tags on all tested hammers that wont work in ATM7)

### Steps to Reproduce

1. Run the ModPack "All The Mods 7 - To The Sky"
2. Place some Cobblestone
3. Give yourself some ExNihilo Hammers from Main mod and from Addon Mods
4. Try hammering down the cobblestone

### Minecraft Version

1.18.2

### Forge Version

40.2.1

### Ex Nihilo: Sequentia Version

20221113-044349

### Additional Context

Also ExNaturae does sometimes work from load to load but Tinkers does  never.
I did not yet test this with other ModPacks having ExNihilo and said Addons but it seems to be a Pack related issue as it works fine standalone. (Might consider posting it to the ATM7 authors as well if ExNihilo and its Addons isnt the root of the issue)
![44DD18EB-6532-48D1-9C1E-542AB3D8FEA8](https://user-images.githubusercontent.com/5236959/221996152-9b46af86-8620-445f-859d-b594e7ae943d.jpg)
![IMG_9196](https://user-images.githubusercontent.com/5236959/221996163-5bd7d2d0-79e1-4f79-af83-0c7392de5a8f.jpg)
![IMG_9195](https://user-images.githubusercontent.com/5236959/221996172-25a3b04e-e4ad-4971-8c86-a42379d99ca7.jpg)

### Log File

none as there is no crash

**Comment by Speecker** [comment]
Oak Wood Nihilo Hammer from ExNihilo:Sequentia - Tinkers Addon
![2023-02-28_23 30 24](https://user-images.githubusercontent.com/5236959/221996421-8ed3c5ae-f336-4d7b-a80a-8990c4fb88fe.png)

Living Wood Nihilo Hammer from ExNaturae - Tinkers Addon
![2023-02-28_23 30 29](https://user-images.githubusercontent.com/5236959/221996424-bd2ce35c-4659-447a-a89a-4808b8ac0366.png)

Stone Hammer from ExNihilo:Sequenti (Main Mod)
![2023-02-28_23 30 32](https://user-images.githubusercontent.com/5236959/221996425-52f0997d-da99-4989-b39e-2beb872c870c.png)

**Comment by Speecker** [comment]
Also the Tinkers Hammers are missing ExCompressum-tag: might that be in issue ?

**Comment by remplerus** [comment]
![grafik](https://user-images.githubusercontent.com/44590574/226977530-f5e94508-9eb3-4740-938e-fb5aebb244cb.png)
this seems suspicious. something is removing the tags from cobblestone... have you tried to make a new world with the mod installed?
