### ISSUE TITLE
[BUG] Nickel nuggets behave differently than other nuggets in Compacting Drawers

### ISSUE THREAD

**Issue by Jack-McKalling** [NovaMachina/ExNihiloSequentia#397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you insert a nickel ingot into an empty compacting drawer, it doesn't automatically allocate the nugget too. It only allocates ingots and blocks. You have to insert the nugget first to get all three forms of the metal.

This is not the case for any other metal. You can for instance insert a bronze ingot and it also allocates the nugget. Even if you attempt to insert it into the bottom right slot.

It appears that the nickel nugget/ingot might be missing a conversion recipe, from this observed behaviour.

### Expected Behavior

Regardless of whichever slot of the empty compacting drawer you insert the nickel ingot into, it should automatically allocate the block in the top slot, ingot in the bottom left, nugget in the bottom right.

### Steps to Reproduce

Wrong:
1. Place an empty compacting drawer
2. Take a nickel ingot
3. Right-click with it on the bottom right slot of the drawer (it goes into the left, but no nuggets)

Correct:
1. Place an empty compacting drawer
2. Take a bronze ingot
3. Right-click with it on the bottom right slot of the drawer (it goes into the left, along with nuggets on the right)

### Minecraft Version

1.19.X

### Forge Version

43.2.3

### Ex Nihilo: Sequentia Version

1.19.2-4.1.0.55-beta

### Additional Context

If you attempt to insert the nickel nugget first, it then does work as expected, but for other materials this isn't necessary.

### Log File

[latest.log](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/10870346/latest.log)

**Comment by Jack-McKalling** [comment]
There could be more metals that have this effect, I don't exactly know why this happens when some others behave normally.
I'm not sure how I could make a list of all affected items without brute force testing all dosens of ingots.

I think Lead, Tin and Silver also have this issue, but not Uranium. (all ingots from this mod I found on first glance)

**Comment by remplerus** [comment]
![2023-03-22_14 44 13](https://user-images.githubusercontent.com/44590574/226923510-80d297c7-74ad-4c00-9414-85cf6a906d58.png)
i couldn't reproduce your problem. i used kubejs to create some dummy blocks, added recipes for block->ingots and ingots->block and did exactly what you did.

**Comment by Jack-McKalling** [comment]
It appears to be specific in Seaopolis2, I also cannot reproduce it in a clean environment. So I'm guessing this is up to the modpack to solve. May bad.
