### ISSUE TITLE
[BUG] Stick Bomb

### ISSUE THREAD

**Issue by FooterManDev** [NovaMachina/ExNihiloSequentia#406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/71946346/229608548-45bf6582-dbc0-446f-8b20-88bc01177168.png)
Ex Nihilo is adding recipes for all ingots made directly from sticks, including ingots from other mods. The crafting ID's being along the lines of:
`exnihilosequentia:ens_someingot_from_nugget`

Edit: I just noticed this actually affects some other stuff in the mod, like Crooks. Even the Smithing recipe for the Netherite Crook takes a stick instead.
![image](https://user-images.githubusercontent.com/71946346/229610545-6e39b670-123e-41eb-9194-4d11842f2e3d.png)

### Expected Behavior

Sticks not being the primary item for Sequentia crafting recipes.

### Steps to Reproduce

Open an instance with Sequentia, JEI / REI
Check recipes, attempt to craft the stick recipe. For us, it was a Tin ingot.
Check Crook, Hammer, Barrel, any recipes added by Sequentia.

### Minecraft Version

1.19.X

### Forge Version

43.2.6

### Ex Nihilo: Sequentia Version

4.1.0.55

### Log File

[latest.log](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/11141846/latest.log)

**Comment by remplerus** [comment]
do you have a resource pack installed?

**Comment by NovaMachina** [comment]
In addition, are you playing with any other mods or is this just Ex Nihilo by itself? All the default recipes for Ex Nihilo work as expected.

**Comment by remplerus** [comment]
closing this, as it's not the mods fold. create an issue here: [https://github.com/TheGangModpacks/Fun-in-the-Sky/issues](https://github.com/TheGangModpacks/Fun-in-the-Sky/issues)

**Comment by FooterManDev** [comment]
> do you have a resource pack installed?

No of course not

> In addition, are you playing with any other mods or is this just Ex Nihilo by itself? All the default recipes for Ex Nihilo work as expected.

Yes, same project as my last issue.

**Comment by remplerus** [comment]
try to rebuild that modpack, it seems that it's corupted.
