### ISSUE TITLE
桶接上漏斗放树苗无法正常工作

### ISSUE THREAD

**Issue by Aimli** [NovaMachina/ExNihiloSequentia#41]
漏斗给桶加材料无法制造泥土

**Comment by Irgendwer01** [comment]
@Aimli if possible, please write the issue in english.

**Comment by Blackout03** [comment]
Google translate shows this
"Adding materials to the bucket by the funnel cannot make dirt"
Which I presume would be
"Adding materials to the barrel by a hopper cannot make dirt"

**Comment by NovaMachina** [comment]
If this is the case then it is connected to #39.

**Comment by yzl210** [comment]
yes, it's correct

**Comment by NovaMachina** [comment]
Fixed in next version.
