### ISSUE TITLE
[BUG] Crash with ExNihiloSequentia-1.19.2-4.2.99

### ISSUE THREAD

**Issue by Darkmega18** [NovaMachina/ExNihiloSequentia#412]
### Is there an existing issue for this?
No. almost all your issues are from a few days ago or later. :V this was released like 5 hours ago according to curseforge

### Current Behavior
I updated Ex nihilo today and immediately was greeted by a crash about "RAW_IRON" while loading with the provided crash report. doesn't get to main menu. Previous beta version before latest works fine and loads properly when backdated to.

### Expected Behavior
that it will work. :V

### Steps to Reproduce
literally start the game with latest version from 5 hours ago and go boom.

### Minecraft Version
1.19.X

### Forge Version
43.2.7

### Ex Nihilo: Sequentia Version
1.19.2-4.2.99

### Log File
[crash-2023-04-13_19.00.32-fml.txt](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/11220269/crash-2023-04-13_19.00.32-fml.txt)

**Comment by NovaMachina** [comment]
This is an issue with the build process. I have rolled back the changes. Use the latest version on CurseForge.
