### ISSUE TITLE
Crash on startup (1.19.2)

### ISSUE THREAD

**Issue by Gitcrafter** [NovaMachina/ExNihiloSequentia#413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I start the game it crashes showing the following screen:

![grafik](https://user-images.githubusercontent.com/81863925/231731019-9c79d388-b5e6-44cb-bb9e-7f147e41152c.png)

### Expected Behavior

The game to start normally

### Steps to Reproduce

Start the game with:
Minecraft Forge 1.19.2 43.2.6
Ex Nihilo Sequentia 1.19.2 4.2.99

### Minecraft Version

1.19.X

### Forge Version

1.19.2 43.2.6

### Ex Nihilo: Sequentia Version

1.19.2 4.2.99

### Additional Context

It happened after I updated JEI, because the latest ExNihiloSequentia version needs a newer JEI version, than the one I was using before, but I did an isolated test with only Ex Nihilo Sequentia to produce a clean log and crash report

### Log File

[latest.log](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/11221257/latest.log)

[crash-2023-04-13_12.41.27-fml.txt](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/11221206/crash-2023-04-13_12.41.27-fml.txt)

**Comment by NovaMachina** [comment]
This is an issue with the build process. I have rolled back the change. Use the latest version on CurseForge.
