### ISSUE TITLE
[CRASH] ExNihiloSequentia-0.1.10 mc1.19.3

### ISSUE THREAD

**Issue by DarcMage** [NovaMachina/ExNihiloSequentia#414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error while moving with clay

### Expected Behavior

Continue normally

### Steps to Reproduce

I was walking and happen to crash.

### Minecraft Version

1.19.X

### Forge Version

FABRIC

### Ex Nihilo: Sequentia Version

0.1.10

### Log File

[latest.log](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/11267102/latest.log)
[crash-2023-04-18_18.19.41-client.txt](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/11267104/crash-2023-04-18_18.19.41-client.txt)

**Comment by NovaMachina** [comment]
Ex Nihilo: Sequentia does not support Fabric. You are probably looking for this repository: https://github.com/LordDeatHunter/FabricaeExNihilo
