### ISSUE TITLE
[BUG] <Fluid issue in crucibles>

### ISSUE THREAD

**Issue by Hyrcas** [NovaMachina/ExNihiloSequentia#419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever i put something in a crucible to create a liquid ( either lava or water) , the liquid looks black and can't be taken with a bucket, if i pump it out using pipes it turns back to the normal liquid but the transfer rate seems limited to 1mb/t.

and when making water after putting the first item the crucible stops filling up.

### Steps to Reproduce

1 place crucible (normally or on an heat source)
2 use item to create liquid by right clicking on the crucible with said item in hand
3 water and lava look black 

### Minecraft Version

1.19.X

### Forge Version

43.2.11

### Ex Nihilo: Sequentia Version

4.0.1.55

### Log File

[latest.log](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/11469752/latest.log)

**Comment by remplerus** [comment]
will be fixed in version 4.2, just be patient. should be soon tho

**Comment by Hyrcas** [comment]
thank you for the response. is the slow transfer rate of liquid a bug too or can that be changed in the config?

**Comment by remplerus** [comment]
that's changeable in config, just look for ticksBetweenMelts and lower that. else you can also use other heat sources.

**Comment by remplerus** [comment]
Completed in v4.2
