### ISSUE TITLE
Support for Custom Meshes and add option for Mesh durability

### ISSUE THREAD

**Issue by Irgendwer01** [NovaMachina/ExNihiloSequentia#42]
**Is your feature request related to a problem? Please describe.**
an problem for pack devs that want adding that.

**Describe the solution you'd like**
Adding support for adding Custom Meshes and an option for Mesh durability in the config to make that pack devs can configure the mod in their pack alot more.

**Comment by NovaMachina** [comment]
Unfortunately, due to how Minecraft has changed from 1.12, custom meshes are not possible. However, I was able to implement mesh durability.
