### ISSUE TITLE
[BUG] <No Waterlogged property>

### ISSUE THREAD

**Issue by FooterManDev** [NovaMachina/ExNihiloSequentia#421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using KubeJS compat recipes (`event.recipes.exnihilosequentia`) and attempting to make it Waterlogged, this error is thrown: "TypeError: Cannot find function "waterlogged" in object". Doesn't matter if given a Boolean or not, the recipe never works. Using `event.custom()` works, but really obnoxious.

### Expected Behavior

Working Waterlogged Sieve recipe, without the use of `event.custom()`.

### Steps to Reproduce

Load the game with KubeJS and Sequentia.
Add this script to a Recipes event: `event.recipes.exnihilosequentia.sieve('minecraft:dirt', 'exnihilosequentia:calcite_pebble') .addRoll(0.70, 'string').addRoll(0.50, 'string').addRoll(0.20, 'string').waterlogged(true)`.
Reload and get the error.

### Minecraft Version

1.19.X

### Forge Version

43.2.8

### Ex Nihilo: Sequentia Version

4.1.0.55

### Additional Context

Modpack reference - https://github.com/TheGangModpacks/Fun-in-the-Sky
Reproducible in an instance with KubeJS, Sequentia, JEI and dependencies only (5 mods in total) and flattenSieveRecipes set to "false".

### Log File

[latest](https://gist.github.com/FooterMan15/e28c837ef0475cafdced8e0885924267)
[kjs server log](https://gist.github.com/FooterMan15/f2a12ab5f463699d134284ee56fee494)

**Comment by NovaMachina** [comment]
Please read the documentation: https://novamachina-mods.github.io/docs/configuration/kubejs/#sieve-recipes

The function is `setWaterlogged()`.

**Comment by FooterManDev** [comment]
I don't think so. When using it, it gives me a different error.
`Error occurred while handling event 'ServerEvents.recipes': Can't find method novamachina.exnihilosequentia.common.compat.kubejs.SieveRecipeJS.setWaterlogged(boolean). `

**Comment by remplerus** [comment]
The issue is you are using setWaterlogged(true) instead of setWaterlogged()

**Comment by FooterManDev** [comment]
Nope, still doesn't work.

**Comment by NovaMachina** [comment]
@FooterMan15 What is the script you are using where you are getting the error?

**Comment by FooterManDev** [comment]
Apologies, I forgot to respond earlier. I was able to get the waterlogged property to work.
