### ISSUE TITLE
[BUG] Hammers are not doing hammer things.

### ISSUE THREAD

**Issue by Darkmega18** [NovaMachina/ExNihiloSequentia#428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For some reason currently, maybe after some mod updates over the course of making my modpack the hammers have suddenly stopped working.
They used to have JEI recipes shown and such and work fine, breaking cobble to gravel etc, however I've recently noticed a distinct lack of a hammer conversion recipes tab in JEI and as a result a complete lack of functionality for the hammer other than the ability to hit stuff and use them as slightly cheaper pickaxes.

### Expected Behavior

That I can hammer the things and see the recipes and it works.

### Steps to Reproduce

it just happens. I load into game, and check recipes for hammers, there are no recipes. and hammering cobble doesn't work.

Searching the console doesn't come up with anything.

There are some minor modifications I've made to the hammers through another mod called attributizer. mainly to slow them down and increase damage so they can be proper effective weapons with posture damage for war dance. 
They are also sorted into a tag by another datapack so that they can be twohanded wielded by an origin feature I made.
I haven't fiddled with anything related to their recipes etc however.

However I wouldn't think any of that should change them so drastically it doesn't pick up what they are?

### Minecraft Version

1.19.X

### Forge Version

43.2.14

### Ex Nihilo: Sequentia Version

1.19.2-4.2.0.53

### Additional Context

There is... quite a sizeable modpack and various datapack related changes going in behind all this.

### Log File

[latest.log](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/12079007/latest.log)

Latest log is for my game paused in the background after testing some hits and noticing something wrong.

**Comment by Darkmega18** [comment]
ok, never mind. the entire functionality of the mod has gone... theres no recipes for sieves and crooks aren't doing anything either, despite still existing in the game.

**Comment by Darkmega18** [comment]
So I... updated forge and then got a GUI related bug fixed by another modder and in the process of either of those being patched, the mod fixed itself. wtf?

**Comment by NovaMachina** [comment]
So is this issue now resolved or do I need to continue to look into it?

**Comment by Darkmega18** [comment]
it's probably solved for now, but I'll keep an eye out for if it came back. cause that was a kinda annoying bug. although I got no idea where it came from. cause it just started happening after some point. so it may well could have been me not updating forge and some other mod was causing a bug cascade or something.
