### ISSUE TITLE
Update KJS Integration to be compatable with KJS 6.1 (1.19)

### ISSUE THREAD

**Issue by Drackion** [NovaMachina/ExNihiloSequentia#429]
### Is there an existing suggestion for this?

- [X] I have searched the existing suggestions

### Feature Description

I am requesting the current KJS integration to get updated to work with kjs 6.1 as currently it doesn't work with kjs 6.1.

### Provided Benefit

The update will allow people on 1.19 to use kjs 6.1 which fixes all the issues in kjs 6

**Comment by NovaMachina** [comment]
This was done. Missed closing the ticket.
