### ISSUE TITLE
Sieve Recipes Server not Showing

### ISSUE THREAD

**Issue by Valdan20** [NovaMachina/ExNihiloSequentia#43]
In Singleplayer World is see in jei the recipes for how to create for example gravel with the hammer or what item it get out of the sieve. On Multiplayer only the crafting Recipes are Showing in Jei, but i can use it.

**Expected behavior**
See all Recipes on a Server in Jei

**Screenshots**
![2020-11-06_15 05 12](https://user-images.githubusercontent.com/48634337/98375139-047a8200-2042-11eb-8c68-93b30096cb59.png)

**Version**
Minecraft Version: 1.16.3
Forge Version: 34.1.42
Ex Nihilo: Sequentia Version: exnihilosequentia-1.16-1.2.1.2.jar

**Comment by NovaMachina** [comment]
The next version should fix this issue.

**Comment by quinn-brittain** [comment]
I am having the same issue. The recipes were working for a short bit on the server originally but now do not appear.

Ex Nihilo: Sequentia Version: 1.16-20220205-012521
Forge Version: 36.2.33
Minecraft Version: 1.16.5

Singleplayer: Diamond Mesh usage
![image](https://user-images.githubusercontent.com/44992697/164147289-cbf949c3-da7e-47a4-9c3e-83b825fbd84c.png)

Multiplayer: Diamond Mesh usage
![image](https://user-images.githubusercontent.com/44992697/164147092-87ac4c92-4316-48ec-b391-37fba40456db.png)
