### ISSUE TITLE
Config to disable pebbles being throwable

### ISSUE THREAD

**Issue by ghost** [NovaMachina/ExNihiloSequentia#431]
### Is there an existing suggestion for this?

- [X] I have searched the existing suggestions

### Feature Description

Just add a config option that can disable pebbles being throwable, for example: 
```json
"trowable_pebbles": false
```
If it's set to false, non of the players will be able to trow pebbles

### Provided Benefit

More customizablity

**Comment by NovaMachina** [comment]
Added in latest version
