### ISSUE TITLE
Editing Sieving Loot Drops

### ISSUE THREAD

**Issue by ItsChase7** [NovaMachina/ExNihiloSequentia#432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This isnt actually a bug but I need help. I am try to create a modpack and want to edit the loot drops for flint mesh. I have cant figure out how to only remove iron pieces from the flint mesh and not all, also how to change the chances of them. And how to add a drop for only one mesh and not all. Also its actually 1.16.5. Ive linked what I have.

### Expected Behavior

s

### Steps to Reproduce

s

### Minecraft Version

1.18.2

### Forge Version

1212121

### Ex Nihilo: Sequentia Version

121212

### Additional Context

sss

### Log File

[removeall.txt](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/12156129/removeall.txt)

**Comment by remplerus** [comment]
first of all, this is a issue tracker, not a help forum. if you need help come to our [discord](https://discord.gg/CJyAkuw).
