### ISSUE TITLE
[BUG] 2 Sieves using the same data of state they are filled with. 

### ISSUE THREAD

**Issue by Xelbayria** [NovaMachina/ExNihiloSequentia#438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

_CAUSE:_ 2 Sieves are using the same data of what state they are filled with. 

When I add a leave block (Oak Leave) to one of 2 Sieves. The **second Sieve** is filled with the same leave. I continually add another leave block to the **first Sieve**. The **second sieve** gets the same leave filled. Both sieves have the same amount. 

### Expected Behavior

Two Sieves must have their own data. In other words. adding one leave to one of 2 Sieves.   and the second Sieve stays empty while I am using **First Sieve**.

### Steps to Reproduce

1. Get 2 Sieve
2. Place them and make sure they are 1 block apart from each other. 
3. Add String Mesh
4. Add leaves to one of 2 Oak Sieve and continue adding. 
5. Watch the other Oak Sieve (the same leave gets added, too) 

### Minecraft Version

1.18.2

### Forge Version

40.2.10

### Ex Nihilo: Sequentia Version

ExNihiloSequentia-1.18.2-20230528-221633

### Additional Context

![exnilioBUG](https://github.com/NovaMachina-Mods/ExNihiloSequentia/assets/12866666/b3dc1b5b-3288-4d7b-96c5-f95f4f5373ca)

I have been looking at the **First Sieve** and continually added the leaves to it, but never once did I look at the **Second Sieve** (RIGHT SIDE). The picture will explain everything. I also checked other WOOD TYPEs, same result. 

### Log File

[latest.log](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/13059333/latest.log)

**Comment by NovaMachina** [comment]
This is expected behavior. The sieve does a rudimentary check for sieves in a nearby radius (`sieveRange` in the config file). Could it be better? Yes, I will see about improving this in future version.

**Comment by Xelbayria** [comment]
ah got it. I understand. Thanks for the explanation
