### ISSUE TITLE
[BUG] Takes longer to break a stone block with a ENS hammer than a vanilla pickaxe

### ISSUE THREAD

**Issue by ghost** [NovaMachina/ExNihiloSequentia#439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Breaking any stone block with an ENS hammer takes about twice as long as a vanilla pick axe. From my testing this includes, stone, cobblestone, andesite, diorite, and granite.

The material of the hammer doesn't affect how long it takes to break the block. It takes the same time to break a cobblestone block with a stone hammer as it does with a diamond hammer.

Sand blocks seems to break just fine. When using a hammer on sand it appears to break in the same amount of time to would take to use a shovel. A diamond hammer breaks sand faster then a stone hammer.

Dust blocks also take longer to break with a hammer then using a shovel.

It seems hammers outright destroy smooth sandstone blocks as well.

### Expected Behavior

Breaking any stone block with a hammer should take the same time as a vanilla pick axe. Also, the material of the hammer should reduce the time it takes to break that block.

I would expect a hammers to break dust blocks as fast as a shovel and break smooth sandstone blocks just like a normal vanilla pick axe.

In general, my expectation is that hammers should break blocks at the same speed as their vanilla counterparts.

### Steps to Reproduce

1. Place a cobblestone block
2. Equip any ENS hammer
3. Break the placed cobblestone block with the equipped hammer
4. Place another cobblestone block
5. Equip any vanilla pick axe
6. Break the placed cobblestone block with the equipped pick axe
7. Notice the difference in times it takes to break the different blocks

### Minecraft Version

1.20.X

### Forge Version

NeoForge 47.1.79

### Ex Nihilo: Sequentia Version

5.0.0

### Additional Context

https://www.youtube.com/watch?v=mIr1lKNKlmU

Here's a quick video I made. Hopefully it demonstrates the problem clearly.

### Log File

[latest.log](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/13310298/latest.log)

**Comment by ghost** [comment]
I wish I could figure out if the problem is with ex nihilo 5 or with neo forge. I tested build 4 and build 3 of ex nihilo and the problem exists for both versions. I made a quick 1.19.2 pack with ex nihilo 4 and old Forge 43.3.0 and the problem didn't exist.

**Comment by NovaMachina** [comment]
Fixed in latest version
