### ISSUE TITLE
can't make soul sand in a barrel full of witch water if the barrel is fed with a hopper

### ISSUE THREAD

**Issue by Algester** [NovaMachina/ExNihiloSequentia#44]
**Describe the bug**
Using hoppers on barrels to make soul sand just replaces the witchwater into sand

**To Reproduce**
1. place a barrel on top of mycelium
2. place a hopper connected to the barrel
3. place water and wait for it to transform into witch water
4. place sand in hopper
5. witch water just becomes sand and not soul sand

**Expected behavior**
Sand becomes soul sand

**Screenshots**
![2020-11-08_20 54 25](https://user-images.githubusercontent.com/6236070/98465765-389ea000-2206-11eb-8b0d-1916db37e3c1.png)

**Version**
Minecraft Version: 1.16.3
Forge Version: 34.1.42
Ex Nihilo: Sequentia Version: 1.16-1.2.1.2.jar

**Additional context**
I'm not sure about added logs

**Comment by Algester** [comment]
ok after further inspection it seems that automation in the new ex nihilo will need some "autoclickers"... not sure if this is intended consequence with new mechanics

**Comment by NovaMachina** [comment]
It's not intended that hoppers will insert items to start the transformation process. However, the overwriting of the fluid is an issue.

**Comment by NovaMachina** [comment]
Fixed in next update.
