### ISSUE TITLE
Forge 1.20+ Port?

### ISSUE THREAD

**Issue by hallool** [NovaMachina/ExNihiloSequentia#440]
### Is there an existing suggestion for this?

- [X] I have searched the existing suggestions

### Feature Description

im wondering if ExNihiloSequentia  is going to forge again bcs i dont see on modrinth and cursedforge a forge version only neoforge

### Provided Benefit

Forge support?

### Additional Context

and addon mods like ex machinis has forge version

**Comment by NovaMachina** [comment]
Ex Nihilo: Sequentia will only be supporting NeoForge for 1.20.1 and newer.
