### ISSUE TITLE
[BUG] <mangrove barrel>

### ISSUE THREAD

**Issue by Kvakochka** [NovaMachina/ExNihiloSequentia#441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://youtu.be/j-IIL4O58Bg

### Expected Behavior

mangrove barrel should work too

### Steps to Reproduce

everything is shown in the video

### Minecraft Version

1.20.X

### Forge Version

47.2.1

### Ex Nihilo: Sequentia Version

5.0.0

### Log File

..

**Comment by NovaMachina** [comment]
Fixed in latest version
