### ISSUE TITLE
[BUG] <Hammers don`t works right>

### ISSUE THREAD

**Issue by Kvakochka** [NovaMachina/ExNihiloSequentia#443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://youtu.be/_Y15gm1xiGw
The video shows that I use different hammers, here are their IDs
```
Item.of('exnihilosequentia:diamond_hammer', '{Damage:0}')
Item.of('exnihilosequentia:diorite_hammer', '{Damage:0}')
Item.of('exnihilosequentia:dripstone_hammer', '{Damage:0}')
Item.of('exnihilosequentia:dripstone_hammer', '{Damage:0}')
Item.of('exnihilosequentia:wooden_hammer', '{Damage:0}')
```
same problem with other hammers

### Expected Behavior

all hammers shown in the video work at the same speed, although it should vary depending on the material

### Minecraft Version

1.18.2

### Forge Version

47.2.1

### Ex Nihilo: Sequentia Version

5.0.0

### Log File

.

**Comment by remplerus** [comment]
Duplication of #439
