### ISSUE TITLE
[Request] Tag pebbles

### ISSUE THREAD

**Issue by a-a-GiTHuB-a-a** [NovaMachina/ExNihiloSequentia#449]
### Is there an existing suggestion for this?

- [X] I have searched the existing suggestions

### Feature Description

This would simply give the different stone pebbles the `pebbles` tag (like the way pieces are tagged).

### Provided Benefit

Currently, I'm using a Logistical Sorter from the Mekanism mod to filter out the pieces, but it currently doesn't have an item _name_ filter, and filtering by individual items would be needlessly tedious.

**Comment by NovaMachina** [comment]
Added in latest version
