### ISSUE TITLE
Barrel filled with witchwater? disappear from the world once broken

### ISSUE THREAD

**Issue by Algester** [NovaMachina/ExNihiloSequentia#45]
**Describe the bug**
I'm not sure if it was meant for the witch water to "leak" into the world when you break the barrel but they just get erased by the world

**To Reproduce**
1. fill a barrel with witchwater
2. break the barrel with a pickaxe forexample

**Expected behavior**
Witchwater is known to do wacky stuff to the player maybe not yet fully implemented

**Version**
Minecraft Version: 1.16.2
Forge Version: 34.1.42
Ex Nihilo: Sequentia Version: 1.2.1.2

**Comment by NovaMachina** [comment]
Does the barrel drop? Because if so, this is intended.

**Comment by Algester** [comment]
nope

**Comment by NovaMachina** [comment]
Fixed in the next version.
