### ISSUE TITLE
Waterlogged Sieves show wrong drops in JEI

### ISSUE THREAD

**Issue by PhilippeDunbar** [NovaMachina/ExNihiloSequentia#452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Some drops listed on JEI don't actually drop from waterlogged sieves. 

Symptoms with all waterlogged meshes except diamond when sifting sand. 

JEI shows items with "Drop Chance" instead of an actual drop chance, these items will never drop from sifting. 

Items shown like this will never drop, its listed with no drop chance. 
<img width="801" alt="Screenshot 2023-12-29 at 12 36 40 PM" src="https://github.com/NovaMachina-Mods/ExNihiloSequentia/assets/5523224/8affb677-b0ee-4723-b9f9-275aa15d84d9">

In order for it to drop it should show a drop chance like this.
<img width="803" alt="Screenshot 2023-12-29 at 12 37 34 PM" src="https://github.com/NovaMachina-Mods/ExNihiloSequentia/assets/5523224/8a3c8b7c-4137-4bac-b1da-ee69b54840f1">

Some meshes are separated into two categories in JEI, like this diamond mesh. The top list cant drop, and the bottom list does drop. 
<img width="809" alt="Screenshot 2023-12-29 at 12 44 06 PM" src="https://github.com/NovaMachina-Mods/ExNihiloSequentia/assets/5523224/51c378a1-bb7b-4faf-9d52-9f5cd72769c6">

Minimal modlist to reproduce bug. 
Ex Nihilo: Sequentia 1.20.1-5.0.0-build.4
Novacore 1.20.1-1.0.0-build.3
JEI 15.2.0.27 for Forge 1.20.1

No Datapacks.

### Expected Behavior

A mesh can drop any item listed in JEI, and if there is no drop chance it shouldn't be listed. 

### Steps to Reproduce

Test 1.

Check sand in JEI for waterlogged meshes.

Test 2. 
Sifted 9 stacks of sand into flint mesh to confirm no drops. 

### Minecraft Version

1.20.X

### Forge Version

Neoforge 47.1.84

### Ex Nihilo: Sequentia Version

1.20.1-5.0.0-build.4

### Log File

https://mclo.gs/CmoOKwq

**Comment by GH-YinXiaoMin** [comment]
Thanks ,I thought it was my bad luck that I didn't sift it out
