### ISSUE TITLE
[Request] Allow Infesting Via Tag or Custom Block List

### ISSUE THREAD

**Issue by Darkosto** [NovaMachina/ExNihiloSequentia#454]
### Is there an existing suggestion for this?

- [X] I have searched the existing suggestions

### Feature Description

Hello! 

Would it be possible to allow Ex Nihilo to work with leaves blocks that do not extend `LeavesBlock` by using a tag or config option instead? Currently, I have some mods in my pack that cannot work with Infesting but, as a pack dev, it would be useful to setup custom blocks via a config or tags. 

Other mods are able to create valid leaves blocks that are fairly compatible in most situations: https://github.com/Lothrazar/ColouredStuff/blob/trunk/1.20/src/main/resources/data/minecraft/tags/blocks/leaves.json

It looks like this is where the code is located: 
https://github.com/NovaMachina-Mods/ExNihiloSequentia/blob/1.20/src/main/java/novamachina/exnihilosequentia/world/level/block/InfestingLeavesBlock.java#L75

### Provided Benefit

This would allow much more compatibility with mods and make pack dev a lot simpler. Let me know if you have any questions!

Thank you!

**Comment by NovaMachina** [comment]
Leaf infestation is now included under the tag "exnihilosequentia:infestable". Please note that at this time the infestation process replaces the block with an infested leaves block. I do plan on using a dynamic renderer in the future, but I have not gotten there yet.
