### ISSUE TITLE
Forge 

### ISSUE THREAD

**Issue by FilipKompaniets** [NovaMachina/ExNihiloSequentia#458]
### Is there an existing suggestion for this?

- [ ] I have searched the existing suggestions

### Feature Description

Make the mod available for Forge please.

### Provided Benefit

Most mods on many builds still work with the forge, and even my mod build will not be able to use this mod :( and if I or others use neoforge, then with some mods the build will not start :(.

**Comment by NovaMachina** [comment]
The decision was made that starting with version 5.0.0 (Minecraft 1.20.1), Ex Nihilo: Sequentia, and all other mods produced by NovaMachina Mods, will only support NeoForge. We will continue to support 1.19.X (Forge) until 1.21 is released, at which point 1.19 (Forge) will no longer be supported.
