### ISSUE TITLE
[BUG] Incompatible with latest JEI version

### ISSUE THREAD

**Issue by eldritch-cookie** [NovaMachina/ExNihiloSequentia#459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

neoforge won't start with latest JEI if i have the latest version(15.3.0.1)

### Steps to Reproduce

1 try to run game with jei 15.3.0.1 and ex nihilo: sequentia installed

### Minecraft Version

1.20.X

### Forge Version

47.1.97

### Ex Nihilo: Sequentia Version

5.0.0.0

### Log File

[latest.log](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/14154483/latest.log)

**Comment by CraftyZombie** [comment]
Can confirm this as well, it states that it's incompatible with JEI 15.3.0.0 and above.

**Comment by eldritch-cookie** [comment]
#461 should fix this so i am closing

**Comment by zxczxczbfg** [comment]
Closing this may have been premature. On my end, the mod (downloaded from Modrinth via PrismLauncher) is still demanding a version of JEI below 15.3 at the time of this writing.

**Comment by eldritch-cookie** [comment]
> Closing this may have been premature. On my end, the mod (downloaded from Modrinth via PrismLauncher) is still demanding a version of JEI below 15.3 at the time of this writing.

which version are you using? and for which MC version i've previously had issues with this mod refusing to backport fixes to prior versions. unless i am mistaken this arrived on 6.0.0 and that is for MC 1.20.4

**Comment by zxczxczbfg** [comment]
Ah, I'm playing on 1.20.1 since that's where almost all my other mods are. That would explain it, yeah.
