### ISSUE TITLE
Mod doesn't function?

### ISSUE THREAD

**Issue by VoidDemon12** [NovaMachina/ExNihiloSequentia#463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I had assembled a large modpack, and while using it, I discovered that Ex Nihilo Sequentia simply did not work. Hammers? nope. Crucible? nothing. Barrels? not a chance. It's other mods like compressum work just fine, but Sequentia doesn't work.
The modpack is in 1.18.2, but it won't let me choose that.

### Minecraft Version

1.19.X

### Forge Version

40.2.18

### Ex Nihilo: Sequentia Version

1.18.2-20230528-221633

### Log File

There's no crash, just simply not being functional.

**Comment by NovaMachina** [comment]
1.18.X is no longer supported.

**Comment by ProGamer2508-0** [comment]
"Create: Biomimicry" cause this bug (also affect 1.20.1)
