### ISSUE TITLE
[BUG] Missing Items/Recipes 

### ISSUE THREAD

**Issue by Silvertail4764** [NovaMachina/ExNihiloSequentia#465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Clay Bucket, and its recipe is completely missing from the mod, I checked in creative and with JEI, even differerent versions of JEI, since theyre having a problem with version numbers. And also, the plugin for jei is not showing recipies for any of the new crafting blocks (Sieves, Barrels, Crucibles), idk if thats on your end, or JEI's 

### Minecraft Version

1.20.X

### Forge Version

20.4.237

### Ex Nihilo: Sequentia Version

6.0.0 build 17

### Log File

[latest.log](https://github.com/user-attachments/files/16037522/latest.log)

**Comment by remplerus** [comment]
1. Clay Bucket was never an item of ex nihilo
2. I'll need to recheck the JEI addon to confirm the problem
