### ISSUE TITLE
[BUG]  {1.21} Neoforge crash with latest mod version 

### ISSUE THREAD

**Issue by Periam** [NovaMachina/ExNihiloSequentia#466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After installing the latest mod version the game crash.

### Expected Behavior

I should launch

### Steps to Reproduce

1-Install the mod
2-Launch the game

### Minecraft Version

1.20.X

### Forge Version

21.0.95

### Ex Nihilo: Sequentia Version

ExNihiloSequentia-1.21-7.0.0-build.1-beta.jar

### Additional Context

![image](https://github.com/user-attachments/assets/9967be95-ed41-4e4b-b0ca-438cdd2c0138)

### Log File

[debug.log](https://github.com/user-attachments/files/16248449/debug.log)
[latest.log](https://github.com/user-attachments/files/16248450/latest.log)
[crash-2024-07-16_09.06.12-fml.txt](https://github.com/user-attachments/files/16248452/crash-2024-07-16_09.06.12-fml.txt)

**Comment by NovaMachina** [comment]
This is due to a change in NeoForge. Please revert NeoForge to 21.0.81 or older. Please keep in mind that NeoForge for 1.21 is still in beta and may make changes that will break mods. I will update Ex Nihilo when I get the chance.

**Comment by Kerrybuck-17** [comment]
> 这是由于 NeoForge 的变更导致的。请将 NeoForge 恢复到 21.0.81 或更早版本。请注意，1.21 版 NeoForge 仍处于测试阶段，可能会进行一些会导致模组无法运行的更改。我会在有空的时候更新 Ex Nihilo。

I hope to update to 1.21.1 because I want to play with Create.
