### ISSUE TITLE
[BUG] Failed to Load Correctly

### ISSUE THREAD

**Issue by Silvertail4764** [NovaMachina/ExNihiloSequentia#467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When Booting on NeoForge 1.21 (21.0.146) and only Nova Core & Ex Nihilo, it fails to load properly, Im linking the crash report
Exception message: java.lang.NoSuchMethodError: 'void net.neoforged.neoforge.common.ModConfigSpec.setConfig(com.electronwill.nightconfig.core.CommentedConfig)'
[crash-2024-07-31_13.08.14-fml.txt](https://github.com/user-attachments/files/16445656/crash-2024-07-31_13.08.14-fml.txt)

### Minecraft Version

1.20.X

### Forge Version

Neo 21.0.146

### Ex Nihilo: Sequentia Version

7.0.0

### Additional Context

There's no option to select 1.21 or neoforge on github btw

### Log File

[latest.log](https://github.com/user-attachments/files/16445671/latest.log)

**Comment by remplerus** [comment]
duplication of #466
