### ISSUE TITLE
[BUG] Game crash at startup

### ISSUE THREAD

**Issue by DrJons75** [NovaMachina/ExNihiloSequentia#470]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

When launching minecraft, the game crashes with the following message:

Ex Nihilo: Sequentia (exnihilosequentia) has failed to load correctly
		java.lang.NoSuchMethodError: 'void net.neoforged.neoforge.common.ModConfigSpec.setConfig(com.electronwill.nightconfig.core.CommentedConfig)'

Minecraft 1.21.1
Neoforge 21.1.39 

Mods: 
Ex-Nihilo Sequentia 1.21-7.0.0-build.1-beta
Novacore 1.21-3.0.-build.2

### Expected Behavior

The mod should be loaded successfully.

### Minecraft Version

1.20.X

### Forge Version

21.1.39

### Ex Nihilo: Sequentia Version

7.0.0 Build 1 Beta

### Log File

[crash-2024-09-06_15.39.51-fml.txt](https://github.com/user-attachments/files/16908962/crash-2024-09-06_15.39.51-fml.txt)

**Comment by remplerus** [comment]
Issue closed due to duplicate issue.
