### ISSUE TITLE
Duplication Bug with CarryOn Mod

### ISSUE THREAD

**Issue by remplerus** [NovaMachina/ExNihiloSequentia#50]
**Describe the bug**
If CarryOn is installed and you pickup a sieve with mesh, the sieve drops a mesh and if you place it again, the mesh shows no mesh. But if you break the sieve, another mesh drops.

**To Reproduce**
1. Place sieve with any mesh
2. Shift+Rightclick sieve
3. Place sieve
4. Break sieve
5. Result: 2 meshes, 1 sieve

**Expected behavior**
Just 1 mesh and 1 sieve.

**Screenshots**

**Version**
Minecraft Version: 1.16.3
Forge Version: 34.1.42
Ex Nihilo: Sequentia Version: 1.16-1.2.1.2

**Additional context**
Well I havent found anything useful in logs, but it's easy to replicate.

**Comment by remplerus** [comment]
and if you want, you can add 1.16.4 tag in curseforge. just tested it with latest forge 1.16.4 and it "works" (the bug also happens there)

**Comment by accessdenied0** [comment]
Same with Barrels. If the Barrels are filled with for example Clay or Dust, the Barrel still has Clay in it.

I also notice that a bug happens with Pipes:
The barrel is filled with any liquid, any solid goes in, transforms, get extracted. Barrel remains empty.
Right clicking fills it with liquid again.
[In this particular Setup](http://puu.sh/GPXOr/7960785091.jpg)
I was even able to sustain to create infinte Soulsand out of 6 pieces of sand, constantly creating after Witch-water is formed.
Still with the bug, that it is not possible to extract with a pipe.

I can provide logs if needed or make a separate issue.

**Comment by remplerus** [comment]
well i found out, that is not only a bug with ex nihilo, but with MANY other mods too, so i just decided to add "exnihilosequentia:*" to the forbidden tiles in carryon-server.toml (and moved a copy in defaultconfig folder)

**Comment by NovaMachina** [comment]
Perfect. I've been chatting with some other developers and that's kind of what I had discovered as well. I'm going to go ahead and close this since it is probably a Carry On issue.
