### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by benbenlaw** [NovaMachina/ExNihiloSequentia#53]
**Describe the bug**
worlds not loading

**To Reproduce**
Install update try to open a world

**Expected behavior**
World opens

**Version**
Minecraft Version: 1.16.3
Forge Version: 31.1.42
Ex Nihilo: Sequentia Version: latest

[crash-2020-11-16_09.27.11-server.txt](https://github.com/NovaMachina/ExNihiloSequentia/files/5545309/crash-2020-11-16_09.27.11-server.txt)

**Comment by cyberpunkbln** [comment]
Same Bug
MC 1.16.4
Forge 35.0.17
Mod Latest

**Comment by NovaMachina** [comment]
According to the crash report that you submitted, this is not an Ex Nihilo issue, but rather a Cooking For Blockheads issue.

**Comment by benbenlaw** [comment]
i removed that mod and it just changed to another mod that was crashing.  I downgraded ex nihilo and it worked as intended all i changed in my pack was updating ex nihilo

**Comment by NovaMachina** [comment]
If you will enable the 'enableDebugLogging' config and then submit the debug.log file, I might be able to see what's going on.

**Comment by benbenlaw** [comment]
Wheres debug logging?

**Comment by remplerus** [comment]
exnihilosequentia-common.toml

**Comment by benbenlaw** [comment]
and where is the debug file saved

**Comment by benbenlaw** [comment]
[crash-2020-11-16_14.52.15-server.txt](https://github.com/NovaMachina/ExNihiloSequentia/files/5547052/crash-2020-11-16_14.52.15-server.txt)

**Comment by benbenlaw** [comment]
[crash-2020-11-16_09.22.48-server.txt](https://github.com/NovaMachina/ExNihiloSequentia/files/5547054/crash-2020-11-16_09.22.48-server.txt)
without cooking for blockheads

**Comment by NovaMachina** [comment]
If this is on the client you will have to add -Dforge.logging.mojang.level=debug as a JVM Argument and then the debug.log file will generate in the logs folder. If this is on the server, then the debug.log should generate by default.

**Comment by benbenlaw** [comment]
![image](https://user-images.githubusercontent.com/42780877/99267903-6eeaa980-281c-11eb-926c-503fda72a729.png)
there on twitch?

**Comment by NovaMachina** [comment]
From the Installations tab on Minecraft Launcher. You will click edit on a profile and then it will be under more options.

**Comment by benbenlaw** [comment]
ok just booting it now

**Comment by benbenlaw** [comment]
no debug log made

**Comment by benbenlaw** [comment]
![image](https://user-images.githubusercontent.com/42780877/99269076-d523fc00-281d-11eb-850c-c4584a2c7028.png)

does it only genrerate if the world opens cause the work doies not open

**Comment by NovaMachina** [comment]
No, it should generate regardless. It seems that this may be a Twitch issue with the JVM Arguments. I was able to duplicate a crash with the same error, so I am looking into it.

**Comment by benbenlaw** [comment]
ok cool thanks

**Comment by NovaMachina** [comment]
This should now be fixed
