### ISSUE TITLE
[1.16.4] Trees Silkworm Output

### ISSUE THREAD

**Issue by TwilightPSN** [NovaMachina/ExNihiloSequentia#59]
**Describe the bug**
It seems that trees are dropping an over excessive amount of silk worms. A single small tree is dropping anywhere from 1-3 stacks of worms.

**To Reproduce**
1. Make Crook
2. Harvest leaves 

**Expected behavior**
Receive a few worms

**Version**
Minecraft Version: 1.16.4
Forge Version: 35.0.16
Ex Nihilo: Sequentia Version: 1.3.0.2

**Comment by NovaMachina** [comment]
In my testing I am not seeing this behavior. Have you changed the recipes for the crook at all?

**Comment by TwilightPSN** [comment]
Have not nothing was changed at all within the mod 

Also having an issue with when you use the hammers with ftbultimine and getting way more output than we should

**Comment by NovaMachina** [comment]
This appears to be an issue with FTB Ultimine installed. I'll look into it.
