### ISSUE TITLE
Wiki/Guide on using Ex Nihilo Sequentia with datapacks

### ISSUE THREAD

**Issue by G-Stav** [NovaMachina/ExNihiloSequentia#61]
**Is your feature request related to a problem? Please describe.**
I'm having a bit of trouble mostly due to not being used to working with datapacks. I'm not sure if it's a bug or I'm just doing something wrong, but I've copied the sieve registrys from the jar into the openloader/data/pack/data/exnihilosequentia/recipes/sieve folder.
What I'm wanting to do is clear a lot of the pre-generated recipes and replace with custom recipes for the pack. What I've gathered is to clear the text from the json and keep the name to replace it with an empty recipe (not sure if this is correct, but replacing the output with "minecraft:air" just disabled ALL the sieve recipes). The /reload command doesn't appear to work, not sure if it's supposed to. But exiting the world and reentering has worked on other mods datapack recipes, but the sieve seems to need a full reset of the pack. 

**Describe the solution you'd like**
Would be nice with a clear walkthrough on the curseforge page or here on github in a wiki on how to properly modify/remove recipes.

[AB#96](https://dev.azure.com/novamachina/9b4371f9-393b-4d7d-8cb9-1f6c864e3511/_workitems/edit/96)

**Comment by NovaMachina** [comment]
Now that I have addon support for Ex Nihilo, I plan on focusing on getting good documentation out for this.

**Comment by NovaMachina** [comment]
I know this is an old request, but I've updated the Wiki that will hopefully resolve this issue. https://ex-nihilo-sequentia.readthedocs.io/
