### ISSUE TITLE
Mutiple drops

### ISSUE THREAD

**Issue by FearowGaming** [NovaMachina/ExNihiloSequentia#62]
Describe the bug
It seems that when hammering cobble  is dropping anywhere from 1-3 stacks of gravel

To Reproduce
Steps to reproduce the behavior.

1. Make hammer
2. Smash cobble

Expected behavior
Revive gravel

Version
Minecraft Version: 1.16.3
Forge Version:  34.1.41 
Ex Nihilo: Sequentia Version: 1.2.1.2

**Comment by NovaMachina** [comment]
I am not seeing this behavior with the configuration you have described. Do you have other mods installed? Does this happen with Ex Nihilo installed by itself?

**Comment by FearowGaming** [comment]
Carry on and other mods

**Comment by Thedrummonger** [comment]
I am also experiencing this issue, however the dupe only happens when I mine a large amount of cobble at once using FTB ultimine, or at least that's the only time I've noticed it.

**Comment by NovaMachina** [comment]
@FearowGaming Do you have FTB Ultimine installed?

**Comment by benbenlaw** [comment]
this seems to happed on servers as well. as well as there being now recipes to make sand from gravel using a hammer

**Comment by benbenlaw** [comment]
yeah really strange things happen so if i open a single player world reipe ect are all fine. joining a server recipes not all working, quiting and going back to single player recipe show shoing in jei and stuff

**Comment by benbenlaw** [comment]
![image](https://user-images.githubusercontent.com/42780877/99820375-986f4200-2b48-11eb-87cd-252d29945d11.png)
there something not working here is now duplicating jei results

**Comment by FearowGaming** [comment]
Yeah i have ftb ultimine installed
