### ISSUE TITLE
auo clicker crash with barrels

### ISSUE THREAD

**Issue by benbenlaw** [NovaMachina/ExNihiloSequentia#63]
**Describe the bug**
when using the mod "click machines" "auto clicker"game crafhes when auto clickerr is used on barrel of transforming witch water

**To Reproduce**
1. place barrel and auto input water to make witchwater
2. have a click machine try and add sand to transforming witch water
3. then crash

**Expected behavior**
clicker should not be able to add an item whilst the transfoming is happening
**Screenshots**

![image](https://user-images.githubusercontent.com/42780877/99701053-deb29b80-2a8b-11eb-9f03-f3c722398d02.png)

**Version**
Minecraft Version: 1.16.3
Forge Version: 31.142
Ex Nihilo: Sequentia Version: latest

**Additional context**
[crash-2020-11-19_17.48.38-server.txt](https://github.com/NovaMachina/ExNihiloSequentia/files/5568596/crash-2020-11-19_17.48.38-server.txt)

**Comment by NovaMachina** [comment]
Which mod does the autoclicker come from?

**Comment by benbenlaw** [comment]
click machine
https://www.curseforge.com/minecraft/mc-mods/click-machine
