### ISSUE TITLE
Fired crucible doesn't work with Superheating Element

### ISSUE THREAD

**Issue by MushuPlatypus** [NovaMachina/ExNihiloSequentia#64]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Superheating element from Mekanism doesn't work with the fired crucible

#### Steps to reproduce:
1. Place a superheating element with a fired curicble on top
2. Put cobblestone into the crucible
3. Heat says 0

#### Version (make sure you are on the latest version before reporting):
**Forge:** 34.1.41
**Mekanism:** Mekanism-1.16.4-10.0.17.444
**Other relevant version:** exnihilosequentia-1.16-1.3.0.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by accessdenied0** [comment]
This is not a bug... you need define the superheating element as Variable source.

Most mod-pack devs made it themselfs. I did it, too and it works for me, just fine.

with Crafttweaker and the newest version of Ex Nihilo 1.3.0.2 its this:
`<recipetype:exnihilosequentia:heat>.addJSONRecipe("heat_superheating",
{
    "type": "exnihilosequentia:heat",
    "block": "mekanism:superheating_element",
    "amount": 15
);`
You would have to define it with a data Pack.
the 
`{
    "type": "exnihilosequentia:heat",
    "block": "mekanism:superheating_element",
    "amount": 15
}`
should work in a separate Json, too.

**Comment by NovaMachina** [comment]
To echo what @accessdenied0 said, this is not a bug. I chose only to add heat sources from vanilla since I cannot know what mods users will use.
