### ISSUE TITLE
Recipes stop working after they are used a few times

### ISSUE THREAD

**Issue by Thedrummonger** [NovaMachina/ExNihiloSequentia#65]
**Describe the bug**
This bug is really strange. Upon booting into a world I am able to use the sieve and hammer normally, but after a few uses they stop dropping any items. For example, I load into the world, hammer about 40 cobblestone and it will drop gravel as expected but the next piece of cobblestone I break drops nothing, same for all the cobblestone after until I restart my client. The sieve also behaves this way but what's stranger is I still get some drops but not all of them. For example the first stack of Gravel I sieve will drop everything, but then after that I will only get Diamonds, lapis and emeralds. The JEI tab for the sieve also goes blank after this happens.

**To Reproduce**
1. Load a new world
2. Sieve about a stack of gravel
3. The rest of the gravel will drop nothing

**Expected behavior**
The recipes will drop items consistently.

**Screenshots**
The JEI tab for cobble in a sieve after the bug starts
https://imgur.com/a/JO82lkK

**Version**
Minecraft Version: 1.16.4
Forge Version: 35.0.18
Ex Nihilo: Sequentia Version: 1.16-1.3.0.2
This bug exists in all 3.0+ versions. As soon as I drop below 3.0 it behaves as it should

**Additional context**
latest.log and debug.log
https://gist.github.com/Thedrummonger/470d9ff199211aade6effb1d09243633

**Comment by NovaMachina** [comment]
It appears that this has been fixed in the latest commit. I wasn't able to replicate JEI going blank, but I did get to the point where drops would not occur with the sieve. Can you confirm that this is fixed in this build? I had to put it in a zip so GitHub would accept it.
[exnihilosequentia-1.16-1.3.1.0-rc1.jar.zip](https://github.com/NovaMachina/ExNihiloSequentia/files/5577009/exnihilosequentia-1.16-1.3.1.0-rc1.jar.zip)

**Comment by Thedrummonger** [comment]
I sieved through 9 stacks of gravel and hammered about 9 stacks of cobble and it looks like everything is working as intended using that version.

**Comment by NovaMachina** [comment]
Awesome! Thanks for checking that!

**Comment by accessdenied0** [comment]
I tried the version you linked @NovaMachina,
and it fixes both [the JEI bug](https://github.com/NovaMachina/ExNihiloSequentia/issues/66) **and** [the Resource bug](https://github.com/NovaMachina/ExNihiloSequentia/issues/65). 👍 
Only issue which is left is, that it has no benifit to make a Emerald- or Netherite Mesh. The pre-defined resources are identical with the Diamond Mesh.

**Comment by NovaMachina** [comment]
On that note. If you wanted to make a suggestion on the benefits of those meshes, I would consider them!

**Comment by accessdenied0** [comment]
It depends what is planed in which direction you have planned for the mod to go...
For instance is the logical conclusion now that it only gives increased drops or maybe only increased drops on valuables like diamonds or maybe even Netherite fragments.
If Enchants are planned, the enchant-ability could be a possibility to make them somehow appealing.
I also see alot of potential for Waterlogging for normal Sieving, it could increase the drop-rate of Gems, Nuggets but reduces dusts to 0 or reduces the chance for fragments.

In general I personally like the idea of new Mesh-Types. I see alot of potential for them to get used.
I think especially for the Netherite one. should be something special to be possible... like getting "wither skeleton" or Basalt fragments, from Soulsand or like mentioned above Netherite fragments. 

(_Fragments: 1/9th of a part eg. 9x Netherite fragments = 1 Netherrite Scrap_)
