### ISSUE TITLE
no such method error and exception in server tick loop when eating end cake in a server?

### ISSUE THREAD

**Issue by Algester** [NovaMachina/ExNihiloSequentia#68]
**Describe the bug**
maybe the end isnt generating?

**To Reproduce**
1. eat an end cake in a server
2. the server should crash 
3. See error

**Expected behavior**
The player should be sent to the end somehow

**Version**
Minecraft Version: 1.16.4
Forge Version: 35.1.0
Ex Nihilo: Sequentia Version: 1.16-1.3.0.2

**Additional context**
https://pastebin.com/fZ39KsxJa

**Comment by NovaMachina** [comment]
Does this occur in the latest version of Ex Nihilo?
