### ISSUE TITLE
"waterlogged" Not Working in Datapacks

### ISSUE THREAD

**Issue by Drakma** [NovaMachina/ExNihiloSequentia#79]
When using datapacks to add items to sieves the "waterlogged" variable does nothing.  Regardless of true or false it always creates the new sieve-able item in waterlogged sieves only.

below you can see through JEI:
https://i.imgur.com/FBDpI3O.png

My datapack:

`{
    "type": "exnihilosequentia:sieve",
    "rolls": [{
        "chance": 0.15,
        "mesh": "diamond"
    }],
    "input": {
        "item": "exnihilosequentia:crushed_end_stone"
    },
    "result": {
        "item": "astralsorcery:aquamarine"
    },
    "waterlogged": false
}`

Minecraft Version: 1.16.4
Forge Version: 35.1.13
Ex Nihilo: Sequentia 1.16-1.3.2.0

**Comment by remplerus** [comment]
well, i just investigated it. and if you just don't use the "waterlogged" tag, it just places it correctly. so if you write it "waterlogged" in your datapack, it gets waterlogged, and if you don't, it won't (wow that's very bad english lol)

**Comment by Drakma** [comment]
I don't know why I didn't think of trying that as well.  I'll changed if this was the intended method.

**Comment by NovaMachina** [comment]
There is a bug here. However, a work around for the moment is to just not include the waterlogged tag if you don't want it to be waterlogged. I'll be fixing it shortly.
