### ISSUE TITLE
Make mesh stackable by 32 or 64

### ISSUE THREAD

**Issue by Switch-Back18** [NovaMachina/ExNihiloSequentia#80]
**Is your feature request related to a problem? Please describe.**
I'm frustrated by the full inventory of mesh

**Describe the solution you'd like**
I want to fix this with inscrease the stacksize of mesh

MathisSkate

**Comment by Darkosto** [comment]
It would be pretty useful in my opinion to allow to amount of stacked meshes to be configurable in the config file.

**Comment by lazynessmind** [comment]
> It would be pretty useful in my opinion to allow to amount of stacked meshes to be configurable in the config file.

yeah, that would be great, but in Minecraft, you can't stack items with durability. The only solution that I can think of is:
* if the player wants to play with `enableMeshDurability` the meshes don't stack.
* if the player wants to play with stackable meshes, `enableMeshDurability` is turned off if is turned on.
