### ISSUE TITLE
Add Support for AE2

### ISSUE THREAD

**Issue by maltewtf** [NovaMachina/ExNihiloSequentia#82]
I am working on a sky factory style mod pack in 1.16.4. Currently, the sieve will not drop any sky stone dust or certus quartz dust. This makes building an ME-System pretty much impossible (besides the missing presses).

Please add a compatibility option for EA2 materials, such as certus quartz dust and sky stone dust.

**Comment by NovaMachina** [comment]
Support has been added for version 1.4.0.0 of Ex Nihilo through an addon: https://www.curseforge.com/minecraft/mc-mods/ex-nihilo-sequentia-ae2-addon
