### ISSUE TITLE
Ore pieces/chunks/ingots datapack support

### ISSUE THREAD

**Issue by Ludi87** [NovaMachina/ExNihiloSequentia#83]
**Describe the solution you'd like**
Some way to define our own ore pieces/chunks/ingots to add more modsupport. From looking at
ExNihiloSequentia/src/main/java/novamachina/exnihilosequentia/common/item/ore/EnumOre.java
it seems like we'd only need to supply a name and color for it..?

My alternative would be contenttweaker/kubejs, but then I'd have to make textures :)

**Comment by NovaMachina** [comment]
Unfortunately, from what I understand, the current philosophy for Minecraft and Forge is that all items must be registered before the initialization phase takes place. This means that dynamically generating items is not possible.
