### ISSUE TITLE
Way to remove all sieve output with CraftTweaker ?

### ISSUE THREAD

**Issue by Switch-Back18** [NovaMachina/ExNihiloSequentia#87]
Hello !

Did there is a way to remove all sieve output with CraftTweaker ?

I'm with the 2.0.

Thanks you !

**Comment by NovaMachina** [comment]
Please check the CraftTweaker documentation: https://docs.blamejared.com/1.16/en/recipes/recipe_managers/

**Comment by Switch-Back18** [comment]
Thank you !
