### ISSUE TITLE
All Mesh inherits of the lower tier

### ISSUE THREAD

**Issue by Switch-Back18** [NovaMachina/ExNihiloSequentia#88]
**Describe the bug**
I start use CraftTweaker to create custom output for Sieves.
I wanna drop Flint for only the String Mesh
I wrote this :

https://pastebin.com/VF2wtgrg

But this works in other Mesh (Iron, Flint, Diamond, Emerald, Netherite).

**To Reproduce**
Use this ZenScripts

**Expected behavior**
I just want to drop this from String Mesh.

**Version**
Minecraft Version: 1.16.4
Forge Version: 35.1.36
Ex Nihilo: Sequentia Version: 2.0.0

**Comment by remplerus** [comment]
can confirm this. also if you add it to a higher tier, those recipes also appear in all tiers above the selected.

**Comment by Switch-Back18** [comment]
If you create a output from  Iron Mesh, that not create for String and Flint Meshs that's false "remplerus" !

In the config in exnihilosequentia-common.toml

There is "flattenSieveRecipes = true"

Change to false and that solve it for the higher mesh !

**Comment by NovaMachina** [comment]
This is the intended behavior. Higher tier meshes inherit the drops of all lower tier meshes. To disable this functionality set `flattenSieveRecipes=false` in the configs.
