### ISSUE TITLE
Can't add HeatSource with CT

### ISSUE THREAD

**Issue by remplerus** [NovaMachina/ExNihiloSequentia#89]
**Describe the bug**
You can't add HeatSource with "latest" CraftTweaker version 7.1.0.82.

**To Reproduce**
1. Create any script that would add a new HeatSource
2. Script just doesn't load with error: "No such member: setBlock"

**Expected behavior**
Adds HeatSource.

**Version**
Minecraft Version: 1.16.4
Forge Version: 35.1.13
Ex Nihilo: Sequentia Version: 2.0.0.0
CraftTweaker Version: 7.1.0.82

Here's something I found in crafttweaker.log
https://gist.github.com/remplerus/1320979da66cd1debad3ba526c195e8a

**Comment by Switch-Back18** [comment]
Paste the zenscript here we can help you

**Comment by remplerus** [comment]
If it helps you, that's the script
https://gist.github.com/remplerus/fd5dfecea107a9a21f62b0bbeabd19c6

**Comment by NovaMachina** [comment]
Which version of CraftTweaker are you using?

**Comment by NovaMachina** [comment]
It would appear that CraftTweaker changed their API since the version I used to develop support for CraftTweaker.
