### ISSUE TITLE
The stone recipes are not present.

### ISSUE THREAD

**Issue by Black-Aengel** [NovaMachina/ExNihiloSequentia#90]
The old Minecraft stone recipes for acquiring Diorite (nether quarts plus cobblestone), Granite (Diorite and nether quarts) and Andesite (Cobblestone and diorite) are gone. Not sure if it is a feature or a bug, but it seriously slows down my production lines as I make extensive use of andesite specifically and to acquire a decent amount I have to work with the sieve for far longer than I am used to. Likewise with the Create Mod I am also in greater need of Andesite than before. Could you please check that for me good sir? Restore those recipes, and check if any are also affected?

**Comment by NovaMachina** [comment]
it would appear that I inadvertently overrode them. I will address this in an update.
