### ISSUE TITLE
Moving Osmium and Bismuth to Addons

### ISSUE THREAD

**Issue by papaworld** [NovaMachina/ExNihiloSequentia#91]
Howdie... Moving osmium and bismuth to addons is a problem because I don't have AE2 installed, nor would I want to. Game launch requires AE2 with addon. Is it possible to separate mekanism and silentmech to their own respective addon or the addon to ignore AE2 not being installed?

**Comment by Blackout03** [comment]
idk what you mean Osmium and Bismuth are not in the AE2 addon at all 

A mekanism addon can be seen in development on the repositories for https://github.com/NovaMachina-Mods

**Comment by papaworld** [comment]
Apologies for the misunderstanding, Osmium is moved to the AE2 addon... "2.0.0.0 - Remove Osmium and Bismuth (moved to addons)". I have Mekanism and SilentMech installed, but not AE2... so I can not sieve for osmium or bismuth.

**Comment by papaworld** [comment]
Version 2.0.0.0 the change-log states (in part): "2.0.0.0 - Remove Osmium and Bismuth (moved to addons)".

With the 2.0.0.0 and 2.0.0.1 updates, osmium and bismuth pieces and chunks are not available.

I don't use AE2, so the "addon" can not be installed in order to get osmium and bismuth.

The Curse Forge Ex Nihilo Sequentia "addons" link is for AE2 which, presumably, also includes Osmium and Bismuth... let me know if I'm wrong please.

In any case, how can I get osmium and bismuth if I don't have AE2?

I see the Mekanism addon with the github link... is this going to be available on curse forge? Because the download links on github are 404 (not found).

**Comment by Blackout03** [comment]
The Mekanism addon has not been released yet, but should come out soon, the osmium and bismuth are not in the ae2 addon

**Comment by papaworld** [comment]
Gotz it! thank you.

**Comment by NovaMachina** [comment]
Mekanism addon has been released, so that should solve part of the issue.

**Comment by papaworld** [comment]
Great, thank you. I'll give it a go.

**Comment by papaworld** [comment]
Installed ExSeq 2.0.1.0 and ExMeka 1.0.0.0... just so ya know, ExSeq needs to be installed first, then drop out, then install ExMeka. If installed at the same time there is game load crash.

All is good with Osmium pieces and chucks... is Bismuth going to be in the works?

**Comment by remplerus** [comment]
just a question, what the heck is bismuth and which mod is using it? i never used that in any exnihilo modpacks out there
