### ISSUE TITLE
Found Another one. Prismarine Shards for Doll

### ISSUE THREAD

**Issue by Black-Aengel** [NovaMachina/ExNihiloSequentia#93]
I see a way how to acquire Prismarine Shards (Sand into the sieve with iron, diamond etc mesh) but i don't see anything for the Prismarine Crystals (which so far I know are only dropped by guardians) but the recipe for creating the Protecting Doll requires Prismarine Crystals.... so.... i don't know. Is there an actual means of finding them without the guardians?

**Comment by NovaMachina** [comment]
I may have overlooked this. I will see if there is a good place to add them in. If you have suggestions on what would be a good balance, please let me know.

**Comment by Blackout03** [comment]
Prismarine shards are dropped from iron and diamond from sand.

prismarine crystals could by from sand on just a diamond mesh?

**Comment by Black-Aengel** [comment]
I agree with Blackout03. Prismarine Crystals should require a bit more oomph to produce. But with the Shards it should be easier. Iron and and above for Shards. Diamond for the Crystals
