### ISSUE TITLE
Support for other mods stones and plants

### ISSUE THREAD

**Issue by Angular-Angel** [NovaMachina/ExNihiloSequentia#97]
**Is your feature request related to a problem? Please describe.**
So, I threw this mod into ~~Enigmatica 2~~ Enigmatica 6 and am really liking it. However, it does have the downside that it only gives stuff from vanilla - I can't get any of the mod trees or crops from the sieve, or pebbles for any of the mod stones. Now, I'm not sure how easy it would be to add support for all that - if it requires manually creating a texture for every entry, then it might add up to a lot of work. But, it would be really cool to have this integrated. In particular, the plants from Biomes You Go would be nice to have accessible, and the stones from that mod, Quark, and Create.

**Describe the solution you'd like**
Making items from these mods accessible via the Sieve, and probably in other ways too.

**Describe alternatives you've considered**
It might be better for the other mods to add compatibility on their end? I think Ex Nihilo makes this pretty easy, but I'm not sure. :/

**Comment by Blackout03** [comment]
Isn't enigmatica 2 for 1.12?

**Comment by Angular-Angel** [comment]
Whoops my bad, yeah I threw it into Enigmatica 6!

**Comment by NovaMachina** [comment]
There are add-ons that are being created that will hopefully add support for other mods. However, it would be pretty easy to create a datapack or a CraftTweaker script that would add these items.
